apiVersion: 1

deleteDatasources:
  - name: Jaeger
    orgId: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      tracesToMetrics:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
        metrics: true
