/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Abie;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Acc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AccManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AccManifestTag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AgencyIdList;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AgencyIdListManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AgencyIdListValue;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AgencyIdListValueManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatConversation;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatMemory;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatMutationConfirmation;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatStep;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppOauth2User;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppUser;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Asbie;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AsbieBizterm;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Asbiep;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AsbiepSupportDoc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Ascc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AsccBizterm;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AsccManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Asccp;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AsccpManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AsccpManifestTag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Bbie;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BbieBizterm;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BbieSc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Bbiep;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Bcc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BccBizterm;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BccManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Bccp;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BccpManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BccpManifestTag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BiePackage;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BiePackageTopLevelAsbiep;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BieUsageRule;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BieUserExtRevision;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BieViewOrder;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BizCtx;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BizCtxAssignment;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BizCtxValue;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BlobContent;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BlobContentManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BusinessTerm;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CdtPri;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CodeList;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CodeListManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CodeListValue;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CodeListValueManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Comment;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Configuration;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CtxCategory;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CtxScheme;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CtxSchemeValue;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Dt;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.DtAwdPri;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.DtManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.DtManifestTag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.DtSc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.DtScAwdPri;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.DtScManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.DtUsageRule;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Exception;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.FlywaySchemaHistory;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.GithubIssue;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.GithubIssueAccManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.GithubIssueAgencyIdListManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.GithubIssueAsccpManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.GithubIssueBccpManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.GithubIssueCodeListManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.GithubIssueDtManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Library;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Log;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Message;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Module;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleAccManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleAgencyIdListManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleAsccpManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleBccpManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleBlobContentManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleCodeListManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleDtManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleSet;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleSetRelease;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ModuleXbtManifest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Namespace;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasDoc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasDocSecurity;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasDocSecurityScope;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasDocTag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasExample;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasExternalDoc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasExternalDocDoc;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasHttpHeader;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasMediaType;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasMessageBody;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasOauthFlow;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasOauthScope;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasOperation;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasOperationSecurity;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasOperationSecurityScope;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasParameter;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasParameterLink;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasRequest;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasRequestParameter;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasResource;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasResourceTag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasResponse;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasResponseHeaders;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasSecurityScheme;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasServer;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasServerVariable;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.OasTag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Oauth2App;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Oauth2AppScope;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Release;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ReleaseDep;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.SeqKey;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Tag;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Tenant;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.TenantBusinessCtx;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.TextTemplate;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.TopLevelAsbiep;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.UsageRule;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.UsageRuleExpression;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.UserTenant;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Xbt;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.XbtManifest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Oagi extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi</code>
     */
    public static final Oagi OAGI = new Oagi();

    /**
     * The ABIE table stores information about an ABIE, which is a
     * contextualized ACC. The context is represented by the BUSINESS_CTX_ID
     * column that refers to a business context. Each ABIE must have a business
     * context and a based ACC.
     * 
     * It should be noted that, per design document, there is no corresponding
     * ABIE created for an ACC which will not show up in the instance document
     * such as ACCs of OAGIS_COMPONENT_TYPE "SEMANTIC_GROUP",
     * "USER_EXTENSION_GROUP", etc.
     */
    public final Abie ABIE = Abie.ABIE;

    /**
     * The ACC table holds information about complex data structured concepts.
     * For example, OAGIS's Components, Nouns, and BODs are captured in the ACC
     * table.
     * 
     * Note that only Extension is supported when deriving ACC from another ACC.
     * (So if there is a restriction needed, maybe that concept should placed
     * higher in the derivation hierarchy rather than lower.)
     * 
     * In OAGIS, all XSD extensions will be treated as a qualification of an
     * ACC.
     */
    public final Acc ACC = Acc.ACC;

    /**
     * The ACC_MANIFEST table is a release-specific handle to an ACC record,
     * pinning a particular ACC (a complex data structured concept such as
     * OAGIS's Components, Nouns, and BODs) to a RELEASE. It carries the
     * revision chain via the PREV_ACC_MANIFEST_ID and NEXT_ACC_MANIFEST_ID
     * self-references across releases, and also records the based (supertype)
     * and replacement manifests for the ACC in that release.
     */
    public final AccManifest ACC_MANIFEST = AccManifest.ACC_MANIFEST;

    /**
     * This is a many-to-many join table that assigns TAG rows to ACC_MANIFEST
     * rows, associating tags with a release-specific ACC.
     */
    public final AccManifestTag ACC_MANIFEST_TAG = AccManifestTag.ACC_MANIFEST_TAG;

    /**
     * The AGENCY_ID_LIST table stores information about agency identification
     * lists. The list's values are however kept in the AGENCY_ID_LIST_VALUE.
     */
    public final AgencyIdList AGENCY_ID_LIST = AgencyIdList.AGENCY_ID_LIST;

    /**
     * The AGENCY_ID_LIST_MANIFEST table is a release-specific handle to an
     * AGENCY_ID_LIST record; it pins the agency identification list to a
     * RELEASE and carries the revision chain (prev/next manifest) across
     * releases.
     */
    public final AgencyIdListManifest AGENCY_ID_LIST_MANIFEST = AgencyIdListManifest.AGENCY_ID_LIST_MANIFEST;

    /**
     * This table captures the values within an agency identification list.
     */
    public final AgencyIdListValue AGENCY_ID_LIST_VALUE = AgencyIdListValue.AGENCY_ID_LIST_VALUE;

    /**
     * A release-specific handle to an AGENCY_ID_LIST_VALUE record, pinning a
     * value within an agency identification list to a RELEASE and to its owning
     * AGENCY_ID_LIST_MANIFEST. It carries the revision chain, referencing the
     * corresponding AGENCY_ID_LIST_VALUE_MANIFEST records in the previous and
     * next releases.
     */
    public final AgencyIdListValueManifest AGENCY_ID_LIST_VALUE_MANIFEST = AgencyIdListValueManifest.AGENCY_ID_LIST_VALUE_MANIFEST;

    /**
     * User-owned AI chat conversation metadata.
     */
    public final AiChatConversation AI_CHAT_CONVERSATION = AiChatConversation.AI_CHAT_CONVERSATION;

    /**
     * Bounded connectCenter assistant model context.
     */
    public final AiChatMemory AI_CHAT_MEMORY = AiChatMemory.AI_CHAT_MEMORY;

    /**
     * One-time server-authoritative grants for AI mutation tool calls.
     */
    public final AiChatMutationConfirmation AI_CHAT_MUTATION_CONFIRMATION = AiChatMutationConfirmation.AI_CHAT_MUTATION_CONFIRMATION;

    /**
     * Complete connectCenter assistant trajectory in ATIF-reconstructable
     * steps.
     */
    public final AiChatStep AI_CHAT_STEP = AiChatStep.AI_CHAT_STEP;

    /**
     * This table captures the OpenID Connect claims (such as the sub, name, and
     * email) of a user authenticated through an external OAuth2 provider
     * registered in OAUTH2_APP, linking that identity to a record in APP_USER.
     * When the APP_USER reference is not set, the record is treated as a
     * pending one that has not yet been associated with an application user.
     */
    public final AppOauth2User APP_OAUTH2_USER = AppOauth2User.APP_OAUTH2_USER;

    /**
     * This table captures the user information for authentication and
     * authorization purposes.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * An ASBIE represents a relationship/association between two ABIEs through
     * an ASBIEP. It is a contextualization of an ASCC.
     */
    public final Asbie ASBIE = Asbie.ASBIE;

    /**
     * The asbie_bizterm table stores information about the aggregation between
     * the ascc_bizterm and ASBIE. TODO: Placeholder, definition is missing.
     */
    public final AsbieBizterm ASBIE_BIZTERM = AsbieBizterm.ASBIE_BIZTERM;

    /**
     * ASBIEP represents a role in a usage of an ABIE. It is a contextualization
     * of an ASCCP.
     */
    public final Asbiep ASBIEP = Asbiep.ASBIEP;

    /**
     * Table storing supporting documentations linked to ASBIEP records.
     */
    public final AsbiepSupportDoc ASBIEP_SUPPORT_DOC = AsbiepSupportDoc.ASBIEP_SUPPORT_DOC;

    /**
     * An ASCC represents a relationship/association between two ACCs through an
     * ASCCP. 
     */
    public final Ascc ASCC = Ascc.ASCC;

    /**
     * The ascc_bizterm table stores information about the aggregation between
     * the business term and ASCC. TODO: Placeholder, definition is missing.
     */
    public final AsccBizterm ASCC_BIZTERM = AsccBizterm.ASCC_BIZTERM;

    /**
     * A release-specific handle to an ASCC record, which represents a
     * relationship/association between two ACCs through an ASCCP. It pins the
     * ASCC to a RELEASE, resolves the association's FROM_ACC_MANIFEST_ID and
     * TO_ASCCP_MANIFEST_ID ends, and carries the revision chain
     * (PREV/NEXT_ASCC_MANIFEST_ID) across releases.
     */
    public final AsccManifest ASCC_MANIFEST = AsccManifest.ASCC_MANIFEST;

    /**
     * An ASCCP specifies a role (or property) an ACC may play under another
     * ACC.
     */
    public final Asccp ASCCP = Asccp.ASCCP;

    /**
     * A release-specific handle to an ASCCP, which specifies a role (or
     * property) an ACC may play under another ACC; it pins the ASCCP to a
     * RELEASE and carries the revision chain to the corresponding
     * ASCCP_MANIFEST records in the previous and next releases.
     */
    public final AsccpManifest ASCCP_MANIFEST = AsccpManifest.ASCCP_MANIFEST;

    /**
     * This is an intersection table that assigns TAG rows to ASCCP_MANIFEST
     * rows, allowing a release-specific ASCCP handle to be tagged with one or
     * more TAGs in a many-to-many relationship.
     */
    public final AsccpManifestTag ASCCP_MANIFEST_TAG = AsccpManifestTag.ASCCP_MANIFEST_TAG;

    /**
     * A BBIE represents a relationship/association between an ABIE and a BBIEP.
     * It is a contextualization of a BCC. The BBIE table also stores some
     * information about the specific constraints related to the BDT associated
     * with the BBIEP. In particular, the three columns including the
     * BDT_PRI_RESTRI_ID, CODE_LIST_ID, and AGENCY_ID_LIST_ID allows for
     * capturing of the specific primitive to be used in the context. Only one
     * column among the three can have a value in a particular record.
     */
    public final Bbie BBIE = Bbie.BBIE;

    /**
     * The bbie_bizterm table stores information about the aggregation between
     * the bbie_bizterm and BBIE. TODO: Placeholder, definition is missing.
     */
    public final BbieBizterm BBIE_BIZTERM = BbieBizterm.BBIE_BIZTERM;

    /**
     * Because there is no single table that is a contextualized counterpart of
     * the DT table (which stores both CDT and BDT), The context specific
     * constraints associated with the DT are stored in the BBIE table, while
     * this table stores the constraints associated with the DT's SCs. 
     */
    public final BbieSc BBIE_SC = BbieSc.BBIE_SC;

    /**
     * BBIEP represents the usage of basic property in a specific business
     * context. It is a contextualization of a BCCP.
     */
    public final Bbiep BBIEP = Bbiep.BBIEP;

    /**
     * A BCC represents a relationship/association between an ACC and a BCCP. It
     * creates a data element for an ACC. 
     */
    public final Bcc BCC = Bcc.BCC;

    /**
     * The bcc_bizterm table stores information about the aggregation between
     * the business term and BCC. TODO: Placeholder, definition is missing.
     */
    public final BccBizterm BCC_BIZTERM = BccBizterm.BCC_BIZTERM;

    /**
     * BCC_MANIFEST is a release-specific handle to a BCC, which represents a
     * relationship/association between an ACC and a BCCP that creates a data
     * element for an ACC. It pins the BCC to a RELEASE (linking the
     * FROM_ACC_MANIFEST and TO_BCCP_MANIFEST ends within that release) and
     * carries the revision chain to the corresponding records in the previous
     * and next releases.
     */
    public final BccManifest BCC_MANIFEST = BccManifest.BCC_MANIFEST;

    /**
     * An BCCP specifies a property concept and data type associated with it. A
     * BCCP can be then added as a property of an ACC.
     */
    public final Bccp BCCP = Bccp.BCCP;

    /**
     * A BCCP_MANIFEST is a release-specific handle to a BCCP record, pinning it
     * to a RELEASE and carrying the revision chain to the corresponding
     * BCCP_MANIFEST in the previous and next releases. A BCCP specifies a
     * property concept and the data type associated with it, which can then be
     * added as a property of an ACC; the manifest also binds the BCCP to the
     * BDT that specifies its data format through BDT_MANIFEST_ID (DT_MANIFEST).
     */
    public final BccpManifest BCCP_MANIFEST = BccpManifest.BCCP_MANIFEST;

    /**
     * This is an intersection table that assigns TAG rows to BCCP_MANIFEST
     * rows, allowing a many-to-many relationship between tags and BCCP
     * manifests.
     */
    public final BccpManifestTag BCCP_MANIFEST_TAG = BccpManifestTag.BCCP_MANIFEST_TAG;

    /**
     * The BIE_PACKAGE table stores information about a BIE package, which
     * groups a set of top-level BIEs (TOP_LEVEL_ASBIEP records, associated
     * through the BIE_PACKAGE_TOP_LEVEL_ASBIEP table) released together under a
     * common package version within a LIBRARY. It carries the revision life
     * cycle state and a chain to the previous version of the package, and may
     * reference a source BIE_PACKAGE from which it was created by a Copy or
     * Uplift action.
     */
    public final BiePackage BIE_PACKAGE = BiePackage.BIE_PACKAGE;

    /**
     * This is an intersection table that assigns TOP_LEVEL_ASBIEP records to a
     * BIE_PACKAGE, capturing the top-level BIEs that make up the package. The
     * referenced TOP_LEVEL_ASBIEP must belong to the same RELEASE as the
     * BIE_PACKAGE, and the PREV_TOP_LEVEL_ASBIEP_ID column tracks the previous
     * version of the Top-Level ASBIEP within the package.
     */
    public final BiePackageTopLevelAsbiep BIE_PACKAGE_TOP_LEVEL_ASBIEP = BiePackageTopLevelAsbiep.BIE_PACKAGE_TOP_LEVEL_ASBIEP;

    /**
     * This is an intersection table. Per CCTS, a usage rule may be reused. This
     * table allows m-m relationships between the usage rule and all kinds of
     * BIEs. In a particular record, either only one of the TARGET_ABIE_ID,
     * TARGET_ASBIE_ID, TARGET_ASBIEP_ID, TARGET_BBIE_ID, or TARGET_BBIEP_ID.
     */
    public final BieUsageRule BIE_USAGE_RULE = BieUsageRule.BIE_USAGE_RULE;

    /**
     * This table is a log of events. It keeps track of the User Extension ACC
     * (the specific revision) used by an Extension ABIE. This can be a named
     * extension (such as ApplicationAreaExtension) or the AllExtension. The
     * REVISED_INDICATOR flag is designed such that a revision of a User
     * Extension can notify the user of a top-level ABIE by setting this flag to
     * true. The TOP_LEVEL_ABIE_ID column makes it more efficient to when
     * opening a top-level ABIE, the user can be notified of any new revision of
     * the extension. A record in this table is created only when there is a
     * user extension to the the OAGIS extension component/ACC.
     */
    public final BieUserExtRevision BIE_USER_EXT_REVISION = BieUserExtRevision.BIE_USER_EXT_REVISION;

    /**
     * Instance-level, release-decoupled sibling sort weights for model browsing
     * and BIE editing (Issue #1638). NOT used for generated output.
     */
    public final BieViewOrder BIE_VIEW_ORDER = BieViewOrder.BIE_VIEW_ORDER;

    /**
     * This table represents a business context. A business context is a
     * combination of one or more business context values.
     */
    public final BizCtx BIZ_CTX = BizCtx.BIZ_CTX;

    /**
     * This is an intersection table that assigns business contexts to a
     * top-level ASBIEP. It provides the many-to-many associations between the
     * BIZ_CTX and TOP_LEVEL_ASBIEP tables.
     */
    public final BizCtxAssignment BIZ_CTX_ASSIGNMENT = BizCtxAssignment.BIZ_CTX_ASSIGNMENT;

    /**
     * This table represents business context values for business contexts. It
     * provides the associations between a business context and a context scheme
     * value.
     */
    public final BizCtxValue BIZ_CTX_VALUE = BizCtxValue.BIZ_CTX_VALUE;

    /**
     * This table stores schemas whose content is only imported as a whole and
     * is represented in Blob.
     */
    public final BlobContent BLOB_CONTENT = BlobContent.BLOB_CONTENT;

    /**
     * The BLOB_CONTENT_MANIFEST table is a release-specific handle to a
     * BLOB_CONTENT record, which stores a schema whose content is only imported
     * as a whole and is represented in Blob. It pins the BLOB_CONTENT to a
     * RELEASE and carries the revision chain via its previous and next manifest
     * self-references across releases.
     */
    public final BlobContentManifest BLOB_CONTENT_MANIFEST = BlobContentManifest.BLOB_CONTENT_MANIFEST;

    /**
     * The Business Term table stores information about the business term, which
     * is usually associated to BIE or CC. TODO: Placeeholder, definition is
     * missing.
     */
    public final BusinessTerm BUSINESS_TERM = BusinessTerm.BUSINESS_TERM;

    /**
     * This table stores the CDT primitives.
     */
    public final CdtPri CDT_PRI = CdtPri.CDT_PRI;

    /**
     * This table stores information about a code list. When a code list is
     * derived from another code list, the whole set of code values belonging to
     * the based code list will be copied.
     */
    public final CodeList CODE_LIST = CodeList.CODE_LIST;

    /**
     * The CODE_LIST_MANIFEST table is a release-specific handle to a CODE_LIST
     * record, pinning that code list to a particular RELEASE and carrying the
     * revision chain (the PREV/NEXT self-references linking the same code list
     * across releases). When a code list is derived from another, the
     * BASED_CODE_LIST_MANIFEST_ID self-reference records its base within the
     * release.
     */
    public final CodeListManifest CODE_LIST_MANIFEST = CodeListManifest.CODE_LIST_MANIFEST;

    /**
     * Each record in this table stores a code list value of a code list. A code
     * list value may be inherited from another code list on which it is based.
     * However, inherited value may be restricted (i.e., disabled and cannot be
     * used) in this code list, i.e., the USED_INDICATOR = false. If the value
     * cannot be used since the based code list, then the LOCKED_INDICATOR =
     * TRUE, because the USED_INDICATOR of such code list value is FALSE by
     * default and can no longer be changed.
     */
    public final CodeListValue CODE_LIST_VALUE = CodeListValue.CODE_LIST_VALUE;

    /**
     * A release-specific handle to a CODE_LIST_VALUE record, pinning a code
     * list value of a code list to a RELEASE (and to its owning
     * CODE_LIST_MANIFEST) and carrying the revision chain via the PREV/NEXT
     * self-references across releases.
     */
    public final CodeListValueManifest CODE_LIST_VALUE_MANIFEST = CodeListValueManifest.CODE_LIST_VALUE_MANIFEST;

    /**
     * This table stores user comments associated with a component, where the
     * associated component is identified by the REFERENCE column in the form of
     * the component type and its manifest ID (e.g., 'CODE_LIST-123'). Replies
     * are captured through the self-referencing PREV_COMMENT_ID chain, and a
     * comment with replies is hidden via IS_HIDDEN instead of being deleted so
     * the reply chain is preserved, while IS_DELETED marks a comment as
     * soft-deleted and excluded from queries rather than physically removing
     * it.
     */
    public final Comment COMMENT = Comment.COMMENT;

    /**
     * The table stores configuration properties of the application.
     */
    public final Configuration CONFIGURATION = Configuration.CONFIGURATION;

    /**
     * This table captures the context category. Examples of context categories
     * as described in the CCTS are business process, industry, etc.
     */
    public final CtxCategory CTX_CATEGORY = CtxCategory.CTX_CATEGORY;

    /**
     * This table represents a context scheme (a classification scheme) for a
     * context category.
     */
    public final CtxScheme CTX_SCHEME = CtxScheme.CTX_SCHEME;

    /**
     * This table stores the context scheme values for a particular context
     * scheme in the CTX_SCHEME table.
     */
    public final CtxSchemeValue CTX_SCHEME_VALUE = CtxSchemeValue.CTX_SCHEME_VALUE;

    /**
     * The DT table stores both CDT and BDT. The two types of DTs are
     * differentiated by the TYPE column.
     */
    public final Dt DT = Dt.DT;

    /**
     * This table captures the allowed primitives for a DT. The allowed
     * primitives are captured by three columns the XBT_MANIFEST_ID,
     * CODE_LIST_MANIFEST_ID, and AGENCY_ID_LIST_MANIFEST_ID. The first column
     * specifies the primitive by the built-in type of an expression language
     * such as the XML Schema built-in type. The second specifies the primitive,
     * which is a code list, while the last one specifies the primitive which is
     * an agency identification list. Only one column among the three can have a
     * value in a particular record.
     */
    public final DtAwdPri DT_AWD_PRI = DtAwdPri.DT_AWD_PRI;

    /**
     * The DT_MANIFEST table is a release-specific handle to a DT record (both
     * CDT and BDT, as stored in the DT table), pinning it to a particular
     * RELEASE. It carries the revision chain across releases through the
     * PREV_DT_MANIFEST_ID and NEXT_DT_MANIFEST_ID self-references, and records
     * the DT's base/supertype via BASED_DT_MANIFEST_ID.
     */
    public final DtManifest DT_MANIFEST = DtManifest.DT_MANIFEST;

    /**
     * A many-to-many join table that assigns TAG rows to DT_MANIFEST rows,
     * attaching tags to the release-specific manifest of a data type (DT).
     */
    public final DtManifestTag DT_MANIFEST_TAG = DtManifestTag.DT_MANIFEST_TAG;

    /**
     * This table represents the supplementary component (SC) of a DT. Revision
     * is not tracked at the supplementary component. It is considered intrinsic
     * part of the DT. In other words, when a new revision of a DT is created a
     * new set of supplementary components is created along with it. 
     */
    public final DtSc DT_SC = DtSc.DT_SC;

    /**
     * This table captures the allowed primitives for a DT_SC. The allowed
     * primitives are captured by three columns the XBT_MANIFEST_ID,
     * CODE_LIST_MANIFEST_ID, and AGENCY_ID_LIST_MANIFEST_ID. The first column
     * specifies the primitive by the built-in type of an expression language
     * such as the XML Schema built-in type. The second specifies the primitive,
     * which is a code list, while the last one specifies the primitive which is
     * an agency identification list. Only one column among the three can have a
     * value in a particular record.
     */
    public final DtScAwdPri DT_SC_AWD_PRI = DtScAwdPri.DT_SC_AWD_PRI;

    /**
     * A release-specific handle to a DT_SC record, pinning the supplementary
     * component (SC) of a data type to a RELEASE and linking it to the owning
     * DT_MANIFEST. It carries the revision chain to the corresponding
     * DT_SC_MANIFEST in the previous and next releases
     * (PREV_DT_SC_MANIFEST_ID/NEXT_DT_SC_MANIFEST_ID), though as noted for
     * DT_SC the supplementary component is an intrinsic part of the DT and is
     * re-created with each new revision of the data type.
     */
    public final DtScManifest DT_SC_MANIFEST = DtScManifest.DT_SC_MANIFEST;

    /**
     * This is an intersection table. Per CCTS, a usage rule may be reused. This
     * table allows m-m relationships between the usage rule and the DT content
     * component and usage rules and DT supplementary component. In a particular
     * record, either a TARGET_DT_ID or TARGET_DT_SC_ID must be present but not
     * both.
     */
    public final DtUsageRule DT_USAGE_RULE = DtUsageRule.DT_USAGE_RULE;

    /**
     * This table logs exceptions raised by the application, capturing the
     * exception message, its serialized stacktrace, and a searchable tag, along
     * with the APP_USER who was working when the exception occurred and the
     * time it was created.
     */
    public final Exception EXCEPTION = Exception.EXCEPTION;

    /**
     * The table <code>oagi.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * Independent registry of referenced GitHub issues (one row per
     * owner/repo/number) with cached metadata JSON. Issue #1533.
     */
    public final GithubIssue GITHUB_ISSUE = GithubIssue.GITHUB_ISSUE;

    /**
     * Links an ACC manifest to a GitHub issue (many-to-many).
     */
    public final GithubIssueAccManifest GITHUB_ISSUE_ACC_MANIFEST = GithubIssueAccManifest.GITHUB_ISSUE_ACC_MANIFEST;

    /**
     * Links an agency id list manifest to a GitHub issue (many-to-many).
     */
    public final GithubIssueAgencyIdListManifest GITHUB_ISSUE_AGENCY_ID_LIST_MANIFEST = GithubIssueAgencyIdListManifest.GITHUB_ISSUE_AGENCY_ID_LIST_MANIFEST;

    /**
     * Links an ASCCP manifest to a GitHub issue (many-to-many).
     */
    public final GithubIssueAsccpManifest GITHUB_ISSUE_ASCCP_MANIFEST = GithubIssueAsccpManifest.GITHUB_ISSUE_ASCCP_MANIFEST;

    /**
     * Links a BCCP manifest to a GitHub issue (many-to-many).
     */
    public final GithubIssueBccpManifest GITHUB_ISSUE_BCCP_MANIFEST = GithubIssueBccpManifest.GITHUB_ISSUE_BCCP_MANIFEST;

    /**
     * Links a code list manifest to a GitHub issue (many-to-many).
     */
    public final GithubIssueCodeListManifest GITHUB_ISSUE_CODE_LIST_MANIFEST = GithubIssueCodeListManifest.GITHUB_ISSUE_CODE_LIST_MANIFEST;

    /**
     * Links a DT manifest to a GitHub issue (many-to-many).
     */
    public final GithubIssueDtManifest GITHUB_ISSUE_DT_MANIFEST = GithubIssueDtManifest.GITHUB_ISSUE_DT_MANIFEST;

    /**
     * This table stores information about a library, the top-level workspace
     * that groups the components, code lists, and releases managed within it.
     * It captures the library's name, type, owning organization, description,
     * application domain, and state, and flags whether the library is read-only
     * or the default shown to users without a preference.
     */
    public final Library LIBRARY = Library.LIBRARY;

    /**
     * The LOG table records the revision history of component records, storing
     * one entry per change with the component's serialized state SNAPSHOT, its
     * REVISION_NUM and REVISION_TRACKING_NUM, and the LOG_ACTION taken. Because
     * it logs many different component types, it references the target
     * component by its GUID (the REFERENCE column) rather than a foreign key,
     * and the PREV_LOG_ID and NEXT_LOG_ID columns chain the entries into a
     * per-component revision history.
     */
    public final Log LOG = Log.LOG;

    /**
     * This table stores messages exchanged between users, referencing APP_USER
     * for both the sender and the recipient, along with each message's subject,
     * body, and read status.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The module table stores information about a physical file, into which CC
     * components will be generated during the expression generation.
     */
    public final Module MODULE = Module.MODULE;

    /**
     * This intersection table assigns ACC_MANIFEST components to a MODULE
     * within a MODULE_SET_RELEASE, indicating the physical file into which each
     * ACC will be generated during the expression generation.
     */
    public final ModuleAccManifest MODULE_ACC_MANIFEST = ModuleAccManifest.MODULE_ACC_MANIFEST;

    /**
     * This table assigns an AGENCY_ID_LIST_MANIFEST to a MODULE within a
     * MODULE_SET_RELEASE, indicating the physical file into which the agency
     * identification list will be generated during the expression generation.
     */
    public final ModuleAgencyIdListManifest MODULE_AGENCY_ID_LIST_MANIFEST = ModuleAgencyIdListManifest.MODULE_AGENCY_ID_LIST_MANIFEST;

    /**
     * This table assigns ASCCP_MANIFEST components to a MODULE within a
     * MODULE_SET_RELEASE, indicating the physical file into which each ASCCP
     * will be generated during the expression generation.
     */
    public final ModuleAsccpManifest MODULE_ASCCP_MANIFEST = ModuleAsccpManifest.MODULE_ASCCP_MANIFEST;

    /**
     * This is an intersection table that assigns a BCCP_MANIFEST to a MODULE
     * within a MODULE_SET_RELEASE, indicating the physical file into which the
     * BCCP will be generated during the expression generation.
     */
    public final ModuleBccpManifest MODULE_BCCP_MANIFEST = ModuleBccpManifest.MODULE_BCCP_MANIFEST;

    /**
     * This table assigns BLOB_CONTENT_MANIFEST records to a MODULE within a
     * MODULE_SET_RELEASE, associating each imported whole-schema blob with the
     * physical file into which it is emitted during schema generation and
     * export.
     */
    public final ModuleBlobContentManifest MODULE_BLOB_CONTENT_MANIFEST = ModuleBlobContentManifest.MODULE_BLOB_CONTENT_MANIFEST;

    /**
     * This table assigns a CODE_LIST_MANIFEST to a MODULE within a
     * MODULE_SET_RELEASE, indicating the physical file into which the code list
     * is generated during the expression generation.
     */
    public final ModuleCodeListManifest MODULE_CODE_LIST_MANIFEST = ModuleCodeListManifest.MODULE_CODE_LIST_MANIFEST;

    /**
     * This intersection table assigns DT_MANIFEST components to a MODULE within
     * a MODULE_SET_RELEASE, indicating the physical file into which each data
     * type will be generated during expression generation.
     */
    public final ModuleDtManifest MODULE_DT_MANIFEST = ModuleDtManifest.MODULE_DT_MANIFEST;

    /**
     * This table stores information about a module set, which is a named,
     * library-scoped collection of MODULE records that organizes CC components
     * into physical schema files. A module set is pinned to a RELEASE through
     * the MODULE_SET_RELEASE table for use in expression/schema generation.
     */
    public final ModuleSet MODULE_SET = ModuleSet.MODULE_SET;

    /**
     * This table pairs a MODULE_SET with a RELEASE, associating a set of
     * MODULEs with a particular release for schema generation and export. Each
     * pairing has its own name and description, and the IS_DEFAULT indicator
     * marks the default module set to be used for a release.
     */
    public final ModuleSetRelease MODULE_SET_RELEASE = ModuleSetRelease.MODULE_SET_RELEASE;

    /**
     * This table assigns XBT_MANIFEST components (the XML Schema and OAGIS
     * built-in types) to a MODULE within a MODULE_SET_RELEASE, so that they are
     * generated into the appropriate physical schema file during expression
     * generation.
     */
    public final ModuleXbtManifest MODULE_XBT_MANIFEST = ModuleXbtManifest.MODULE_XBT_MANIFEST;

    /**
     * This table stores information about a namespace. Namespace is the
     * namespace as in the XML schema specification.
     */
    public final Namespace NAMESPACE = Namespace.NAMESPACE;

    /**
     * The root of the OpenAPI Specification document object model that the
     * other OAS_* tables hang off; each row is an OpenAPI Object holding the
     * openapi version string together with the Info Object metadata (title,
     * description, terms of service, version, and contact and license details).
     */
    public final OasDoc OAS_DOC = OasDoc.OAS_DOC;

    /**
     * Root-level Security Requirement entry for an OpenAPI document.
     */
    public final OasDocSecurity OAS_DOC_SECURITY = OasDocSecurity.OAS_DOC_SECURITY;

    /**
     * Scope of a root-level Security Requirement entry.
     */
    public final OasDocSecurityScope OAS_DOC_SECURITY_SCOPE = OasDocSecurityScope.OAS_DOC_SECURITY_SCOPE;

    /**
     * A many-to-many join assigning OAS_TAG rows to an OAS_DOC, populating the
     * OpenAPI document's root-level tags array.
     */
    public final OasDocTag OAS_DOC_TAG = OasDocTag.OAS_DOC_TAG;

    /**
     * OpenAPI Example Object holding a single example, either an embedded
     * literal in the value field or a reference to an external example via the
     * ref (externalValue) field; the two are mutually exclusive.
     */
    public final OasExample OAS_EXAMPLE = OasExample.OAS_EXAMPLE;

    /**
     * Allows referencing an external resource for extended documentation.
     */
    public final OasExternalDoc OAS_EXTERNAL_DOC = OasExternalDoc.OAS_EXTERNAL_DOC;

    /**
     * A many-to-many join that attaches OAS_EXTERNAL_DOC external documentation
     * references to OAS_DOC OpenAPI documents.
     */
    public final OasExternalDocDoc OAS_EXTERNAL_DOC_DOC = OasExternalDocDoc.OAS_EXTERNAL_DOC_DOC;

    /**
     * OpenAPI Header Object, defining an HTTP header by its name, description,
     * and schema type reference ($ref); attached to an OAS_RESPONSE through the
     * OAS_RESPONSE_HEADERS join and referenced by an OAS_PARAMETER when the
     * parameter location is header.
     */
    public final OasHttpHeader OAS_HTTP_HEADER = OasHttpHeader.OAS_HTTP_HEADER;

    /**
     * OpenAPI Media Type Object, which represents a media type (such as
     * application/json) used within the content of a request body or response
     * in an OpenAPI document.
     */
    public final OasMediaType OAS_MEDIA_TYPE = OasMediaType.OAS_MEDIA_TYPE;

    /**
     * The OAS_MESSAGE_BODY table holds an OpenAPI message body whose schema is
     * defined by the referenced TOP_LEVEL_ASBIEP. The OAS_REQUEST and
     * OAS_RESPONSE tables both reference this table to bind that BIE as the
     * content of an operation's request or response body.
     */
    public final OasMessageBody OAS_MESSAGE_BODY = OasMessageBody.OAS_MESSAGE_BODY;

    /**
     * OpenAPI OAuth Flow Object for an oauth2 security scheme (one entry of
     * components.securitySchemes.&lt;name&gt;.flows).
     */
    public final OasOauthFlow OAS_OAUTH_FLOW = OasOauthFlow.OAS_OAUTH_FLOW;

    /**
     * OpenAPI OAuth Flow scope (name -&gt; description) for an oauth2 flow.
     */
    public final OasOauthScope OAS_OAUTH_SCOPE = OasOauthScope.OAS_OAUTH_SCOPE;

    /**
     * OpenAPI Operation Object; a single HTTP verb (get, put, post, delete,
     * etc.) exposed on an OAS_RESOURCE path item, carrying its operationId,
     * summary, description, deprecation flag, and defaulted error-response body
     * settings, with any per-operation security overrides captured in
     * OAS_OPERATION_SECURITY.
     */
    public final OasOperation OAS_OPERATION = OasOperation.OAS_OPERATION;

    /**
     * Operation-level Security Requirement entry (overrides document-level).
     */
    public final OasOperationSecurity OAS_OPERATION_SECURITY = OasOperationSecurity.OAS_OPERATION_SECURITY;

    /**
     * Scope of an operation-level Security Requirement entry.
     */
    public final OasOperationSecurityScope OAS_OPERATION_SECURITY_SCOPE = OasOperationSecurityScope.OAS_OPERATION_SECURITY_SCOPE;

    /**
     * OpenAPI Parameter Object describing a single operation parameter,
     * identified by its name and location (in = query, header, path, or cookie)
     * along with its required, schema type, and serialization settings; when in
     * = header it may reference an OAS_HTTP_HEADER.
     */
    public final OasParameter OAS_PARAMETER = OasParameter.OAS_PARAMETER;

    /**
     * OpenAPI Link Object parameter binding declared on an OAS_RESPONSE; each
     * row ties an OAS_PARAMETER to a runtime EXPRESSION that supplies its
     * value, optionally targeting the linked OAS_OPERATION.
     */
    public final OasParameterLink OAS_PARAMETER_LINK = OasParameterLink.OAS_PARAMETER_LINK;

    /**
     * OpenAPI Request Body Object for an OAS_OPERATION; it defines the
     * operation's request payload from a BIE-based OAS_MESSAGE_BODY, along with
     * whether the body is required and generation options such as array
     * wrapping, root suppression, and optional meta-header and pagination
     * TOP_LEVEL_ASBIEP references.
     */
    public final OasRequest OAS_REQUEST = OasRequest.OAS_REQUEST;

    /**
     * A many-to-many join assigning OAS_PARAMETER entries (an operation's
     * query, header, path, or cookie parameters) to an OAS_REQUEST.
     */
    public final OasRequestParameter OAS_REQUEST_PARAMETER = OasRequestParameter.OAS_REQUEST_PARAMETER;

    /**
     * A resource (path) belonging to an OpenAPI document; each row is an entry
     * of the OAS_DOC Paths Object, keyed by PATH (the OpenAPI path, defaulting
     * to the BIE name) and optionally pointing to an externally defined Path
     * Item Object via the REF ($ref) column.
     */
    public final OasResource OAS_RESOURCE = OasResource.OAS_RESOURCE;

    /**
     * A many-to-many join assigning OAS_TAG entries to an OAS_OPERATION,
     * representing the tags list of an OpenAPI Operation Object that groups the
     * operation under those tags.
     */
    public final OasResourceTag OAS_RESOURCE_TAG = OasResourceTag.OAS_RESOURCE_TAG;

    /**
     * OpenAPI Response Object owned by an OAS_OPERATION; one entry of the
     * operation's responses map keyed by HTTP status code, binding the response
     * body to an OAS_MESSAGE_BODY (which references a BIE) with optional
     * meta-header and pagination TOP_LEVEL_ASBIEP references.
     */
    public final OasResponse OAS_RESPONSE = OasResponse.OAS_RESPONSE;

    /**
     * The headers map of an OpenAPI Response Object; a many-to-many join
     * assigning OAS_HTTP_HEADER definitions to an OAS_RESPONSE.
     */
    public final OasResponseHeaders OAS_RESPONSE_HEADERS = OasResponseHeaders.OAS_RESPONSE_HEADERS;

    /**
     * OpenAPI Security Scheme Object (OAS 3.0.3 through 3.2.0); one named entry
     * of a document components.securitySchemes map.
     */
    public final OasSecurityScheme OAS_SECURITY_SCHEME = OasSecurityScheme.OAS_SECURITY_SCHEME;

    /**
     * OpenAPI Server Object; one entry of the servers array of an OAS_DOC,
     * providing connectivity information to a target host via a URL (optionally
     * with a description and URL-template variables).
     */
    public final OasServer OAS_SERVER = OasServer.OAS_SERVER;

    /**
     * OpenAPI Server Variable Object; one named entry of an OAS_SERVER's
     * variables map, holding the default value, optional enum, and description
     * used for server URL template substitution.
     */
    public final OasServerVariable OAS_SERVER_VARIABLE = OasServerVariable.OAS_SERVER_VARIABLE;

    /**
     * OpenAPI Tag Object; adds metadata to a single tag (a name and an optional
     * description) that is used to group the Operation Objects of an OpenAPI
     * document.
     */
    public final OasTag OAS_TAG = OasTag.OAS_TAG;

    /**
     * This table stores OAuth 2.0 / OpenID Connect provider registrations,
     * including client credentials, endpoint URIs, and login-button display
     * settings, used to authenticate end users.
     */
    public final Oauth2App OAUTH2_APP = Oauth2App.OAUTH2_APP;

    /**
     * This table captures the OAuth2 scopes requested for an OAUTH2_APP,
     * storing one scope value per row.
     */
    public final Oauth2AppScope OAUTH2_APP_SCOPE = Oauth2AppScope.OAUTH2_APP_SCOPE;

    /**
     * The is table store the release information.
     */
    public final Release RELEASE = Release.RELEASE;

    /**
     * This table stores release dependency information.
     */
    public final ReleaseDep RELEASE_DEP = ReleaseDep.RELEASE_DEP;

    /**
     * This table stores the ordering of the associations (ASCC and BCC) that
     * belong to an ACC. Each record points, through FROM_ACC_MANIFEST_ID, to
     * the owning ACC via ACC_MANIFEST and, through exactly one of
     * ASCC_MANIFEST_ID or BCC_MANIFEST_ID, to the ordered association; the
     * PREV_SEQ_KEY_ID and NEXT_SEQ_KEY_ID columns form a doubly-linked chain
     * that defines the sequence of these associations within the ACC.
     */
    public final SeqKey SEQ_KEY = SeqKey.SEQ_KEY;

    /**
     * The TAG table stores the tags (each with a name, description, and text
     * and background color) that can be attached to core component and data
     * type manifests through the intersection tables ACC_MANIFEST_TAG,
     * ASCCP_MANIFEST_TAG, BCCP_MANIFEST_TAG, and DT_MANIFEST_TAG.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * This table about the user tenant role.
     */
    public final Tenant TENANT = Tenant.TENANT;

    /**
     * This table captures the tenant role and theirs business contexts.
     */
    public final TenantBusinessCtx TENANT_BUSINESS_CTX = TenantBusinessCtx.TENANT_BUSINESS_CTX;

    /**
     * This table stores named text templates, each with a subject, content
     * type, and body containing placeholders that are substituted at rendering
     * time. Templates are looked up by name to compose output such as email
     * messages.
     */
    public final TextTemplate TEXT_TEMPLATE = TextTemplate.TEXT_TEMPLATE;

    /**
     * This table indexes the ASBIEP which is a top-level ASBIEP. This table and
     * the owner_top_level_asbiep_id column in all BIE tables allow all related
     * BIEs to be retrieved all at once speeding up the profile BOD
     * transactions.
     */
    public final TopLevelAsbiep TOP_LEVEL_ASBIEP = TopLevelAsbiep.TOP_LEVEL_ASBIEP;

    /**
     * This table captures a usage rule information. A usage rule may be
     * expressed in multiple expressions. Each expression is captured in the
     * USAGE_RULE_EXPRESSION table. To capture a description of a usage rule,
     * create a usage rule expression with the unstructured constraint type.
     */
    public final UsageRule USAGE_RULE = UsageRule.USAGE_RULE;

    /**
     * The USAGE_RULE_EXPRESSION provides a representation of a usage rule in a
     * particular syntax indicated by the CONSTRAINT_TYPE column. One of the
     * syntaxes can be unstructured, which works a description of the usage
     * rule.
     */
    public final UsageRuleExpression USAGE_RULE_EXPRESSION = UsageRuleExpression.USAGE_RULE_EXPRESSION;

    /**
     * This table captures the tenant roles of the user
     */
    public final UserTenant USER_TENANT = UserTenant.USER_TENANT;

    /**
     * This table stores XML schema built-in types and OAGIS built-in types.
     * OAGIS built-in types are those types defined in the XMLSchemaBuiltinType
     * and the XMLSchemaBuiltinType Patterns schemas.
     */
    public final Xbt XBT = Xbt.XBT;

    /**
     * A release-specific handle to an XBT record, pinning an XML schema
     * built-in type or OAGIS built-in type to a RELEASE and carrying the
     * revision chain (PREV_XBT_MANIFEST_ID and NEXT_XBT_MANIFEST_ID) across
     * releases. It also records how the built-in type maps to an allowed CDT
     * primitive via CDT_PRI.
     */
    public final XbtManifest XBT_MANIFEST = XbtManifest.XBT_MANIFEST;

    /**
     * No further instances allowed
     */
    private Oagi() {
        super(DSL.name("oagi"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Abie.ABIE,
            Acc.ACC,
            AccManifest.ACC_MANIFEST,
            AccManifestTag.ACC_MANIFEST_TAG,
            AgencyIdList.AGENCY_ID_LIST,
            AgencyIdListManifest.AGENCY_ID_LIST_MANIFEST,
            AgencyIdListValue.AGENCY_ID_LIST_VALUE,
            AgencyIdListValueManifest.AGENCY_ID_LIST_VALUE_MANIFEST,
            AiChatConversation.AI_CHAT_CONVERSATION,
            AiChatMemory.AI_CHAT_MEMORY,
            AiChatMutationConfirmation.AI_CHAT_MUTATION_CONFIRMATION,
            AiChatStep.AI_CHAT_STEP,
            AppOauth2User.APP_OAUTH2_USER,
            AppUser.APP_USER,
            Asbie.ASBIE,
            AsbieBizterm.ASBIE_BIZTERM,
            Asbiep.ASBIEP,
            AsbiepSupportDoc.ASBIEP_SUPPORT_DOC,
            Ascc.ASCC,
            AsccBizterm.ASCC_BIZTERM,
            AsccManifest.ASCC_MANIFEST,
            Asccp.ASCCP,
            AsccpManifest.ASCCP_MANIFEST,
            AsccpManifestTag.ASCCP_MANIFEST_TAG,
            Bbie.BBIE,
            BbieBizterm.BBIE_BIZTERM,
            BbieSc.BBIE_SC,
            Bbiep.BBIEP,
            Bcc.BCC,
            BccBizterm.BCC_BIZTERM,
            BccManifest.BCC_MANIFEST,
            Bccp.BCCP,
            BccpManifest.BCCP_MANIFEST,
            BccpManifestTag.BCCP_MANIFEST_TAG,
            BiePackage.BIE_PACKAGE,
            BiePackageTopLevelAsbiep.BIE_PACKAGE_TOP_LEVEL_ASBIEP,
            BieUsageRule.BIE_USAGE_RULE,
            BieUserExtRevision.BIE_USER_EXT_REVISION,
            BieViewOrder.BIE_VIEW_ORDER,
            BizCtx.BIZ_CTX,
            BizCtxAssignment.BIZ_CTX_ASSIGNMENT,
            BizCtxValue.BIZ_CTX_VALUE,
            BlobContent.BLOB_CONTENT,
            BlobContentManifest.BLOB_CONTENT_MANIFEST,
            BusinessTerm.BUSINESS_TERM,
            CdtPri.CDT_PRI,
            CodeList.CODE_LIST,
            CodeListManifest.CODE_LIST_MANIFEST,
            CodeListValue.CODE_LIST_VALUE,
            CodeListValueManifest.CODE_LIST_VALUE_MANIFEST,
            Comment.COMMENT,
            Configuration.CONFIGURATION,
            CtxCategory.CTX_CATEGORY,
            CtxScheme.CTX_SCHEME,
            CtxSchemeValue.CTX_SCHEME_VALUE,
            Dt.DT,
            DtAwdPri.DT_AWD_PRI,
            DtManifest.DT_MANIFEST,
            DtManifestTag.DT_MANIFEST_TAG,
            DtSc.DT_SC,
            DtScAwdPri.DT_SC_AWD_PRI,
            DtScManifest.DT_SC_MANIFEST,
            DtUsageRule.DT_USAGE_RULE,
            Exception.EXCEPTION,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            GithubIssue.GITHUB_ISSUE,
            GithubIssueAccManifest.GITHUB_ISSUE_ACC_MANIFEST,
            GithubIssueAgencyIdListManifest.GITHUB_ISSUE_AGENCY_ID_LIST_MANIFEST,
            GithubIssueAsccpManifest.GITHUB_ISSUE_ASCCP_MANIFEST,
            GithubIssueBccpManifest.GITHUB_ISSUE_BCCP_MANIFEST,
            GithubIssueCodeListManifest.GITHUB_ISSUE_CODE_LIST_MANIFEST,
            GithubIssueDtManifest.GITHUB_ISSUE_DT_MANIFEST,
            Library.LIBRARY,
            Log.LOG,
            Message.MESSAGE,
            Module.MODULE,
            ModuleAccManifest.MODULE_ACC_MANIFEST,
            ModuleAgencyIdListManifest.MODULE_AGENCY_ID_LIST_MANIFEST,
            ModuleAsccpManifest.MODULE_ASCCP_MANIFEST,
            ModuleBccpManifest.MODULE_BCCP_MANIFEST,
            ModuleBlobContentManifest.MODULE_BLOB_CONTENT_MANIFEST,
            ModuleCodeListManifest.MODULE_CODE_LIST_MANIFEST,
            ModuleDtManifest.MODULE_DT_MANIFEST,
            ModuleSet.MODULE_SET,
            ModuleSetRelease.MODULE_SET_RELEASE,
            ModuleXbtManifest.MODULE_XBT_MANIFEST,
            Namespace.NAMESPACE,
            OasDoc.OAS_DOC,
            OasDocSecurity.OAS_DOC_SECURITY,
            OasDocSecurityScope.OAS_DOC_SECURITY_SCOPE,
            OasDocTag.OAS_DOC_TAG,
            OasExample.OAS_EXAMPLE,
            OasExternalDoc.OAS_EXTERNAL_DOC,
            OasExternalDocDoc.OAS_EXTERNAL_DOC_DOC,
            OasHttpHeader.OAS_HTTP_HEADER,
            OasMediaType.OAS_MEDIA_TYPE,
            OasMessageBody.OAS_MESSAGE_BODY,
            OasOauthFlow.OAS_OAUTH_FLOW,
            OasOauthScope.OAS_OAUTH_SCOPE,
            OasOperation.OAS_OPERATION,
            OasOperationSecurity.OAS_OPERATION_SECURITY,
            OasOperationSecurityScope.OAS_OPERATION_SECURITY_SCOPE,
            OasParameter.OAS_PARAMETER,
            OasParameterLink.OAS_PARAMETER_LINK,
            OasRequest.OAS_REQUEST,
            OasRequestParameter.OAS_REQUEST_PARAMETER,
            OasResource.OAS_RESOURCE,
            OasResourceTag.OAS_RESOURCE_TAG,
            OasResponse.OAS_RESPONSE,
            OasResponseHeaders.OAS_RESPONSE_HEADERS,
            OasSecurityScheme.OAS_SECURITY_SCHEME,
            OasServer.OAS_SERVER,
            OasServerVariable.OAS_SERVER_VARIABLE,
            OasTag.OAS_TAG,
            Oauth2App.OAUTH2_APP,
            Oauth2AppScope.OAUTH2_APP_SCOPE,
            Release.RELEASE,
            ReleaseDep.RELEASE_DEP,
            SeqKey.SEQ_KEY,
            Tag.TAG,
            Tenant.TENANT,
            TenantBusinessCtx.TENANT_BUSINESS_CTX,
            TextTemplate.TEXT_TEMPLATE,
            TopLevelAsbiep.TOP_LEVEL_ASBIEP,
            UsageRule.USAGE_RULE,
            UsageRuleExpression.USAGE_RULE_EXPRESSION,
            UserTenant.USER_TENANT,
            Xbt.XBT,
            XbtManifest.XBT_MANIFEST
        );
    }
}
