/**
 * Registers core-component and data-type resources for AI-assisted navigation.
 */

import {AiResourceRoute} from '../ai-chat-panel.model';
import {
  AUTHENTICATED_ROLES,
  DEFAULT_LAST_UPDATED_PAGE,
  PAGE_PARAMS,
  UPDATED_RANGE_ALIASES,
  base64ListQuery
} from './ai-resource-route-query';

export const AI_COMPONENT_RESOURCE_ROUTES: AiResourceRoute[] = [
  {resource: 'core-component', listPath: '/core_component', listQuery: base64ListQuery('/core_component', {...DEFAULT_LAST_UPDATED_PAGE, releaseId: '0'}, {...PAGE_PARAMS, releaseId: 'release ID', states: 'states', reusable: 'true or false', deprecated: 'true or false', newComponent: 'true or false', commonlyUsed: 'true or false', ownerLoginIdList: 'owner login IDs', updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', name: 'name', den: 'DEN', definition: 'definition', module: 'module', tags: 'tags', namespaces: 'namespace IDs', componentTypes: 'ACC ASCCP BCCP EXTENSION'}, {owner: 'ownerLoginIdList', updater: 'updaterLoginIdList', state: 'states', release_id: 'releaseId', type: 'componentTypes', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/core_component/acc/', '/core_component/asccp/', '/core_component/bccp/', '/core_component/extension/'], detailPatterns: {ACC: '/core_component/acc/{manifestId}', ASCCP: '/core_component/asccp/{manifestId}', BCCP: '/core_component/bccp/{manifestId}', EXTENSION: '/core_component/extension/{manifestId}'}, idFields: ['manifestId', 'accManifestId', 'asccpManifestId', 'bccpManifestId', 'id'], linkableFields: ['den', 'name', 'manifestId'], label: 'Core Component', roles: AUTHENTICATED_ROLES},
  {resource: 'data-type', listPath: '/data_type', listQuery: base64ListQuery('/data_type', {...DEFAULT_LAST_UPDATED_PAGE, releaseId: '0'}, {...PAGE_PARAMS, releaseId: 'release ID', states: 'states', deprecated: 'true or false', newComponent: 'true or false', ownerLoginIdList: 'owner login IDs', updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', den: 'DEN', definition: 'definition', module: 'module', tags: 'tags', namespaces: 'namespace IDs', componentTypes: 'type filters'}, {owner: 'ownerLoginIdList', updater: 'updaterLoginIdList', state: 'states', release_id: 'releaseId', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/data_type/'], detailPattern: '/data_type/{id}', idFields: ['manifestId', 'dtManifestId', 'id'], linkableFields: ['den', 'name', 'manifestId'], label: 'Data Type', roles: AUTHENTICATED_ROLES},
  {resource: 'code-list', listPath: '/code_list', listQuery: base64ListQuery('/code_list', {...DEFAULT_LAST_UPDATED_PAGE, releaseId: '0'}, {...PAGE_PARAMS, releaseId: 'release ID', access: 'access', states: 'states', deprecated: 'true or false', extensible: 'true or false', newComponent: 'true or false', ownedByDeveloper: 'true or false', updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', namespaces: 'namespace IDs', name: 'name', definition: 'definition', module: 'module'}, {updater: 'updaterLoginIdList', state: 'states', release_id: 'releaseId', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/code_list/'], detailPattern: '/code_list/{id}', idFields: ['manifestId', 'codeListManifestId', 'id'], linkableFields: ['name', 'manifestId'], label: 'Code List', roles: AUTHENTICATED_ROLES},
  {resource: 'agency-id-list', listPath: '/agency_id_list', listQuery: base64ListQuery('/agency_id_list', {...DEFAULT_LAST_UPDATED_PAGE, releaseId: '0'}, {...PAGE_PARAMS, releaseId: 'release ID', access: 'access', states: 'states', deprecated: 'true or false', extensible: 'true or false', newComponent: 'true or false', ownedByDeveloper: 'true or false', updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', namespaces: 'namespace IDs', name: 'name', definition: 'definition', module: 'module'}, {updater: 'updaterLoginIdList', state: 'states', release_id: 'releaseId', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/agency_id_list/'], detailPattern: '/agency_id_list/{id}', idFields: ['manifestId', 'agencyIdListManifestId', 'id'], linkableFields: ['name', 'manifestId'], label: 'Agency ID List', roles: AUTHENTICATED_ROLES}
];
