import {AiResourceRoute} from '../ai-chat-panel.model';
import {
  AUTHENTICATED_ROLES,
  CREATED_RANGE_ALIASES,
  DEFAULT_LAST_UPDATED_PAGE,
  PAGE_PARAMS,
  UPDATED_RANGE_ALIASES,
  base64ListQuery
} from './ai-resource-route-query';

export const AI_GOVERNANCE_RESOURCE_ROUTES: AiResourceRoute[] = [
  {resource: 'release', listPath: '/release', listQuery: base64ListQuery('/release', DEFAULT_LAST_UPDATED_PAGE, {...PAGE_PARAMS, states: 'states', namespaces: 'namespace IDs', creatorLoginIdList: 'creator login IDs', createdDateStart: 'created range start', createdDateEnd: 'created range end', updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', releaseNum: 'release number'}, {creator: 'creatorLoginIdList', updater: 'updaterLoginIdList', state: 'states', release_num: 'releaseNum', namespace_id: 'namespaces', limit: 'pageSize'}, {...UPDATED_RANGE_ALIASES, ...CREATED_RANGE_ALIASES}), detailPrefixes: ['/release/'], detailPattern: '/release/{id}', idFields: ['releaseId', 'id'], linkableFields: ['releaseNum', 'name', 'releaseId'], label: 'Release', roles: AUTHENTICATED_ROLES},
  {resource: 'namespace', listPath: '/namespace', listQuery: base64ListQuery('/namespace', DEFAULT_LAST_UPDATED_PAGE, {...PAGE_PARAMS, ownerLoginIdList: 'owner login IDs', updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', standard: 'true or false', uri: 'URI', prefix: 'prefix', description: 'description'}, {owner: 'ownerLoginIdList', updater: 'updaterLoginIdList', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/namespace/'], detailPattern: '/namespace/{id}', idFields: ['namespaceId', 'id'], linkableFields: ['uri', 'prefix', 'namespaceId'], label: 'Namespace', roles: AUTHENTICATED_ROLES},
  {resource: 'module-set', listPath: '/module_management/module_set', listQuery: base64ListQuery('/module_management/module_set', DEFAULT_LAST_UPDATED_PAGE, {...PAGE_PARAMS, updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', name: 'name', description: 'description'}, {updater: 'updaterLoginIdList', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/module_management/module_set/'], detailPattern: '/module_management/module_set/{id}', idFields: ['moduleSetId', 'id'], linkableFields: ['name', 'moduleSetId'], label: 'Module Set', roles: AUTHENTICATED_ROLES},
  {resource: 'module-set-release', listPath: '/module_management/module_set_release', listQuery: base64ListQuery('/module_management/module_set_release', DEFAULT_LAST_UPDATED_PAGE, {...PAGE_PARAMS, updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', name: 'name', releaseId: 'release ID', isDefault: 'true or false'}, {updater: 'updaterLoginIdList', release_id: 'releaseId', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/module_management/module_set_release/'], detailPattern: '/module_management/module_set_release/{id}', idFields: ['moduleSetReleaseId', 'id'], linkableFields: ['name', 'moduleSetReleaseId'], label: 'Module Set Release', roles: AUTHENTICATED_ROLES},
  {resource: 'library', listPath: '/library', listQuery: base64ListQuery('/library', DEFAULT_LAST_UPDATED_PAGE, {...PAGE_PARAMS, updaterLoginIdList: 'updater login IDs', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', name: 'name', type: 'type', organization: 'organization', domain: 'domain', description: 'description', state: 'state'}, {updater: 'updaterLoginIdList', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/library/'], detailPattern: '/library/{id}', idFields: ['libraryId', 'id'], linkableFields: ['name', 'libraryId'], label: 'Library', roles: AUTHENTICATED_ROLES},
  {resource: 'business-term', listPath: '/business_term_management/business_term', listQuery: base64ListQuery('/business_term_management/business_term', DEFAULT_LAST_UPDATED_PAGE, {...PAGE_PARAMS, updaterUsernameList: 'updater usernames', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', businessTerm: 'business term', externalReferenceUri: 'external reference URI', externalReferenceId: 'external reference ID', definition: 'definition', bieId: 'BIE ID', bieType: 'BIE type', searchByCC: 'core component search', typeCode: 'type code', primaryIndicator: 'true or false'}, {updater: 'updaterUsernameList', business_term: 'businessTerm', external_reference_uri: 'externalReferenceUri', external_reference_id: 'externalReferenceId', bie_id: 'bieId', bie_type: 'bieType', type_code: 'typeCode', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/business_term_management/business_term/'], detailPattern: '/business_term_management/business_term/{id}', idFields: ['businessTermId', 'id'], linkableFields: ['businessTerm', 'businessTermId'], label: 'Business Term', roles: AUTHENTICATED_ROLES},
  {resource: 'assigned-business-term', listPath: '/business_term_management/assign_business_term', listQuery: base64ListQuery('/business_term_management/assign_business_term', DEFAULT_LAST_UPDATED_PAGE, {...PAGE_PARAMS, updaterUsernameList: 'updater usernames', updatedDateStart: 'updated range start', updatedDateEnd: 'updated range end', businessTerm: 'business term', externalReferenceUri: 'external reference URI', bieTypes: 'BIE types', bieId: 'BIE ID', bieDen: 'BIE DEN', searchByCC: 'core component search', typeCode: 'type code', primaryIndicator: 'true or false'}, {updater: 'updaterUsernameList', business_term: 'businessTerm', bie_id: 'bieId', bie_den: 'bieDen', bie_type: 'bieTypes', type_code: 'typeCode', limit: 'pageSize'}, UPDATED_RANGE_ALIASES), detailPrefixes: ['/business_term_management/assign_business_term/details/'], detailPattern: '/business_term_management/assign_business_term/details/{id}', idFields: ['assignedBizTermId', 'id'], linkableFields: ['businessTerm', 'assignedBizTermId'], label: 'Assigned Business Term', roles: AUTHENTICATED_ROLES},
  {resource: 'message', listPath: '/message', listQuery: base64ListQuery('/message', {sortActive: 'timestamp', sortDirection: 'desc', pageIndex: '0', pageSize: '10'}, {...PAGE_PARAMS, senderUsernameList: 'sender usernames', createdDateStart: 'created range start', createdDateEnd: 'created range end', subject: 'subject'}, {sender: 'senderUsernameList', limit: 'pageSize'}, CREATED_RANGE_ALIASES), detailPrefixes: ['/message/'], detailPattern: '/message/{id}', idFields: ['messageId', 'id'], linkableFields: ['subject', 'messageId'], label: 'Message', roles: AUTHENTICATED_ROLES}
];
