/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatConversation.AiChatConversationPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiChatMemoryRecord;


/**
 * Bounded connectCenter assistant model context.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatMemory extends TableImpl<AiChatMemoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_chat_memory</code>
     */
    public static final AiChatMemory AI_CHAT_MEMORY = new AiChatMemory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiChatMemoryRecord> getRecordType() {
        return AiChatMemoryRecord.class;
    }

    /**
     * The column <code>oagi.ai_chat_memory.ai_chat_memory_id</code>. The
     * primary key of the AI chat memory record.
     */
    public final TableField<AiChatMemoryRecord, ULong> AI_CHAT_MEMORY_ID = createField(DSL.name("ai_chat_memory_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "The primary key of the AI chat memory record.");

    /**
     * The column <code>oagi.ai_chat_memory.ai_chat_conversation_id</code>.
     * Foreign key to the AI_CHAT_CONVERSATION table identifying the owning
     * conversation.
     */
    public final TableField<AiChatMemoryRecord, ULong> AI_CHAT_CONVERSATION_ID = createField(DSL.name("ai_chat_conversation_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Foreign key to the AI_CHAT_CONVERSATION table identifying the owning conversation.");

    /**
     * The column <code>oagi.ai_chat_memory.memory_sequence</code>. The
     * zero-based sequence of the message in the bounded model context.
     */
    public final TableField<AiChatMemoryRecord, Long> MEMORY_SEQUENCE = createField(DSL.name("memory_sequence"), SQLDataType.BIGINT.nullable(false), this, "The zero-based sequence of the message in the bounded model context.");

    /**
     * The column <code>oagi.ai_chat_memory.message_type</code>. Expected
     * model-context roles are USER, ASSISTANT, SYSTEM, and TOOL; other values
     * are handled by the application.
     */
    public final TableField<AiChatMemoryRecord, String> MESSAGE_TYPE = createField(DSL.name("message_type"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Expected model-context roles are USER, ASSISTANT, SYSTEM, and TOOL; other values are handled by the application.");

    /**
     * The column <code>oagi.ai_chat_memory.content</code>. The text content
     * supplied to the model as conversation memory.
     */
    public final TableField<AiChatMemoryRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "The text content supplied to the model as conversation memory.");

    /**
     * The column <code>oagi.ai_chat_memory.metadata_json</code>. Optional JSON
     * metadata associated with the model-context message.
     */
    public final TableField<AiChatMemoryRecord, String> METADATA_JSON = createField(DSL.name("metadata_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "Optional JSON metadata associated with the model-context message.");

    /**
     * The column <code>oagi.ai_chat_memory.creation_timestamp</code>. The
     * timestamp when the memory record was created.
     */
    public final TableField<AiChatMemoryRecord, LocalDateTime> CREATION_TIMESTAMP = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "The timestamp when the memory record was created.");

    private AiChatMemory(Name alias, Table<AiChatMemoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiChatMemory(Name alias, Table<AiChatMemoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Bounded connectCenter assistant model context."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_memory</code> table reference
     */
    public AiChatMemory(String alias) {
        this(DSL.name(alias), AI_CHAT_MEMORY);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_memory</code> table reference
     */
    public AiChatMemory(Name alias) {
        this(alias, AI_CHAT_MEMORY);
    }

    /**
     * Create a <code>oagi.ai_chat_memory</code> table reference
     */
    public AiChatMemory() {
        this(DSL.name("ai_chat_memory"), null);
    }

    public <O extends Record> AiChatMemory(Table<O> path, ForeignKey<O, AiChatMemoryRecord> childPath, InverseForeignKey<O, AiChatMemoryRecord> parentPath) {
        super(path, childPath, parentPath, AI_CHAT_MEMORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiChatMemoryPath extends AiChatMemory implements Path<AiChatMemoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiChatMemoryPath(Table<O> path, ForeignKey<O, AiChatMemoryRecord> childPath, InverseForeignKey<O, AiChatMemoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiChatMemoryPath(Name alias, Table<AiChatMemoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiChatMemoryPath as(String alias) {
            return new AiChatMemoryPath(DSL.name(alias), this);
        }

        @Override
        public AiChatMemoryPath as(Name alias) {
            return new AiChatMemoryPath(alias, this);
        }

        @Override
        public AiChatMemoryPath as(Table<?> alias) {
            return new AiChatMemoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public Identity<AiChatMemoryRecord, ULong> getIdentity() {
        return (Identity<AiChatMemoryRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiChatMemoryRecord> getPrimaryKey() {
        return Keys.KEY_AI_CHAT_MEMORY_PRIMARY;
    }

    @Override
    public List<UniqueKey<AiChatMemoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AI_CHAT_MEMORY_AI_CHAT_MEMORY_CONVERSATION_SEQUENCE_UK);
    }

    @Override
    public List<ForeignKey<AiChatMemoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_CHAT_MEMORY_CONVERSATION_FK);
    }

    private transient AiChatConversationPath _aiChatConversation;

    /**
     * Get the implicit join path to the <code>oagi.ai_chat_conversation</code>
     * table.
     */
    public AiChatConversationPath aiChatConversation() {
        if (_aiChatConversation == null)
            _aiChatConversation = new AiChatConversationPath(this, Keys.AI_CHAT_MEMORY_CONVERSATION_FK, null);

        return _aiChatConversation;
    }

    @Override
    public List<Check<AiChatMemoryRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("metadata_json"), "json_valid(`metadata_json`)", true)
        );
    }

    @Override
    public AiChatMemory as(String alias) {
        return new AiChatMemory(DSL.name(alias), this);
    }

    @Override
    public AiChatMemory as(Name alias) {
        return new AiChatMemory(alias, this);
    }

    @Override
    public AiChatMemory as(Table<?> alias) {
        return new AiChatMemory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatMemory rename(String name) {
        return new AiChatMemory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatMemory rename(Name name) {
        return new AiChatMemory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatMemory rename(Table<?> name) {
        return new AiChatMemory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMemory where(Condition condition) {
        return new AiChatMemory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMemory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMemory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMemory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMemory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMemory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMemory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMemory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMemory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMemory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
