/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Indexes;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatArtifact.AiChatArtifactPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatConversation.AiChatConversationPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatMemory.AiChatMemoryPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatMutationConfirmation.AiChatMutationConfirmationPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatStep.AiChatStepPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppUser.AppUserPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiChatConversationRecord;


/**
 * User-owned AI chat conversation metadata.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatConversation extends TableImpl<AiChatConversationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_chat_conversation</code>
     */
    public static final AiChatConversation AI_CHAT_CONVERSATION = new AiChatConversation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiChatConversationRecord> getRecordType() {
        return AiChatConversationRecord.class;
    }

    /**
     * The column
     * <code>oagi.ai_chat_conversation.ai_chat_conversation_id</code>. The
     * primary key of the AI chat conversation record.
     */
    public final TableField<AiChatConversationRecord, ULong> AI_CHAT_CONVERSATION_ID = createField(DSL.name("ai_chat_conversation_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "The primary key of the AI chat conversation record.");

    /**
     * The column <code>oagi.ai_chat_conversation.guid</code>. The public unique
     * identifier of the AI chat conversation.
     */
    public final TableField<AiChatConversationRecord, String> GUID = createField(DSL.name("guid"), SQLDataType.CHAR(36).nullable(false), this, "The public unique identifier of the AI chat conversation.");

    /**
     * The column <code>oagi.ai_chat_conversation.app_user_id</code>. Foreign
     * key to the APP_USER table identifying the owner of the conversation.
     */
    public final TableField<AiChatConversationRecord, ULong> APP_USER_ID = createField(DSL.name("app_user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Foreign key to the APP_USER table identifying the owner of the conversation.");

    /**
     * The column
     * <code>oagi.ai_chat_conversation.parent_ai_chat_conversation_id</code>.
     * Self-reference to the root conversation that owns this child execution.
     */
    public final TableField<AiChatConversationRecord, ULong> PARENT_AI_CHAT_CONVERSATION_ID = createField(DSL.name("parent_ai_chat_conversation_id"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Self-reference to the root conversation that owns this child execution.");

    /**
     * The column <code>oagi.ai_chat_conversation.conversation_kind</code>.
     * Expected conversation kinds are ROOT, SUBAGENT, and PARALLEL; other
     * values are handled by the application.
     */
    public final TableField<AiChatConversationRecord, String> CONVERSATION_KIND = createField(DSL.name("conversation_kind"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("'ROOT'"), SQLDataType.VARCHAR)), this, "Expected conversation kinds are ROOT, SUBAGENT, and PARALLEL; other values are handled by the application.");

    /**
     * The column <code>oagi.ai_chat_conversation.agent_id</code>. Registered
     * worker identifier for a child execution conversation.
     */
    public final TableField<AiChatConversationRecord, String> AGENT_ID = createField(DSL.name("agent_id"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Registered worker identifier for a child execution conversation.");

    /**
     * The column <code>oagi.ai_chat_conversation.parent_request_id</code>. Root
     * request that created this child execution conversation.
     */
    public final TableField<AiChatConversationRecord, String> PARENT_REQUEST_ID = createField(DSL.name("parent_request_id"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Root request that created this child execution conversation.");

    /**
     * The column <code>oagi.ai_chat_conversation.title</code>. The display
     * title of the conversation, derived from its first prompt.
     */
    public final TableField<AiChatConversationRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(240).nullable(false), this, "The display title of the conversation, derived from its first prompt.");

    /**
     * The column <code>oagi.ai_chat_conversation.compacted</code>. Indicates
     * whether the conversation model context has been compacted (0 = False, 1 =
     * True).
     */
    public final TableField<AiChatConversationRecord, Byte> COMPACTED = createField(DSL.name("compacted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "Indicates whether the conversation model context has been compacted (0 = False, 1 = True).");

    /**
     * The column <code>oagi.ai_chat_conversation.created_at</code>. The
     * timestamp when the conversation was created.
     */
    public final TableField<AiChatConversationRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "The timestamp when the conversation was created.");

    /**
     * The column <code>oagi.ai_chat_conversation.updated_at</code>. The
     * timestamp of the most recent activity in the conversation.
     */
    public final TableField<AiChatConversationRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "The timestamp of the most recent activity in the conversation.");

    private AiChatConversation(Name alias, Table<AiChatConversationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiChatConversation(Name alias, Table<AiChatConversationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("User-owned AI chat conversation metadata."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_conversation</code> table reference
     */
    public AiChatConversation(String alias) {
        this(DSL.name(alias), AI_CHAT_CONVERSATION);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_conversation</code> table reference
     */
    public AiChatConversation(Name alias) {
        this(alias, AI_CHAT_CONVERSATION);
    }

    /**
     * Create a <code>oagi.ai_chat_conversation</code> table reference
     */
    public AiChatConversation() {
        this(DSL.name("ai_chat_conversation"), null);
    }

    public <O extends Record> AiChatConversation(Table<O> path, ForeignKey<O, AiChatConversationRecord> childPath, InverseForeignKey<O, AiChatConversationRecord> parentPath) {
        super(path, childPath, parentPath, AI_CHAT_CONVERSATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiChatConversationPath extends AiChatConversation implements Path<AiChatConversationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiChatConversationPath(Table<O> path, ForeignKey<O, AiChatConversationRecord> childPath, InverseForeignKey<O, AiChatConversationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiChatConversationPath(Name alias, Table<AiChatConversationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiChatConversationPath as(String alias) {
            return new AiChatConversationPath(DSL.name(alias), this);
        }

        @Override
        public AiChatConversationPath as(Name alias) {
            return new AiChatConversationPath(alias, this);
        }

        @Override
        public AiChatConversationPath as(Table<?> alias) {
            return new AiChatConversationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AI_CHAT_CONVERSATION_AI_CHAT_CONVERSATION_OWNER_UPDATED_IDX, Indexes.AI_CHAT_CONVERSATION_AI_CHAT_CONVERSATION_PARENT_IDX, Indexes.AI_CHAT_CONVERSATION_AI_CHAT_CONVERSATION_PARENT_REQUEST_IDX);
    }

    @Override
    public Identity<AiChatConversationRecord, ULong> getIdentity() {
        return (Identity<AiChatConversationRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiChatConversationRecord> getPrimaryKey() {
        return Keys.KEY_AI_CHAT_CONVERSATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<AiChatConversationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AI_CHAT_CONVERSATION_AI_CHAT_CONVERSATION_GUID_UK);
    }

    @Override
    public List<ForeignKey<AiChatConversationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_CHAT_CONVERSATION_APP_USER_FK, Keys.AI_CHAT_CONVERSATION_PARENT_FK);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.AI_CHAT_CONVERSATION_APP_USER_FK, null);

        return _appUser;
    }

    private transient AiChatConversationPath _aiChatConversation;

    /**
     * Get the implicit join path to the <code>oagi.ai_chat_conversation</code>
     * table.
     */
    public AiChatConversationPath aiChatConversation() {
        if (_aiChatConversation == null)
            _aiChatConversation = new AiChatConversationPath(this, Keys.AI_CHAT_CONVERSATION_PARENT_FK, null);

        return _aiChatConversation;
    }

    private transient AiChatArtifactPath _aiChatArtifact;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.ai_chat_artifact</code> table
     */
    public AiChatArtifactPath aiChatArtifact() {
        if (_aiChatArtifact == null)
            _aiChatArtifact = new AiChatArtifactPath(this, null, Keys.AI_CHAT_ARTIFACT_CONVERSATION_FK.getInverseKey());

        return _aiChatArtifact;
    }

    private transient AiChatMemoryPath _aiChatMemory;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.ai_chat_memory</code> table
     */
    public AiChatMemoryPath aiChatMemory() {
        if (_aiChatMemory == null)
            _aiChatMemory = new AiChatMemoryPath(this, null, Keys.AI_CHAT_MEMORY_CONVERSATION_FK.getInverseKey());

        return _aiChatMemory;
    }

    private transient AiChatMutationConfirmationPath _aiChatMutationConfirmation;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.ai_chat_mutation_confirmation</code> table
     */
    public AiChatMutationConfirmationPath aiChatMutationConfirmation() {
        if (_aiChatMutationConfirmation == null)
            _aiChatMutationConfirmation = new AiChatMutationConfirmationPath(this, null, Keys.AI_CHAT_MUTATION_CONFIRMATION_CONVERSATION_FK.getInverseKey());

        return _aiChatMutationConfirmation;
    }

    private transient AiChatStepPath _aiChatStep;

    /**
     * Get the implicit to-many join path to the <code>oagi.ai_chat_step</code>
     * table
     */
    public AiChatStepPath aiChatStep() {
        if (_aiChatStep == null)
            _aiChatStep = new AiChatStepPath(this, null, Keys.AI_CHAT_STEP_CONVERSATION_FK.getInverseKey());

        return _aiChatStep;
    }

    @Override
    public AiChatConversation as(String alias) {
        return new AiChatConversation(DSL.name(alias), this);
    }

    @Override
    public AiChatConversation as(Name alias) {
        return new AiChatConversation(alias, this);
    }

    @Override
    public AiChatConversation as(Table<?> alias) {
        return new AiChatConversation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatConversation rename(String name) {
        return new AiChatConversation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatConversation rename(Name name) {
        return new AiChatConversation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatConversation rename(Table<?> name) {
        return new AiChatConversation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatConversation where(Condition condition) {
        return new AiChatConversation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatConversation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatConversation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatConversation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatConversation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatConversation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatConversation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatConversation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatConversation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatConversation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
