/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Indexes;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatConversation.AiChatConversationPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiChatFileRecord;


/**
 * Generated Assistant file metadata and provider location history.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatFile extends TableImpl<AiChatFileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_chat_file</code>
     */
    public static final AiChatFile AI_CHAT_FILE = new AiChatFile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiChatFileRecord> getRecordType() {
        return AiChatFileRecord.class;
    }

    /**
     * The column <code>oagi.ai_chat_file.ai_chat_file_id</code>. The primary
     * key of the generated AI file.
     */
    public final TableField<AiChatFileRecord, ULong> AI_CHAT_FILE_ID = createField(DSL.name("ai_chat_file_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "The primary key of the generated AI file.");

    /**
     * The column <code>oagi.ai_chat_file.guid</code>. Public file identifier.
     */
    public final TableField<AiChatFileRecord, String> GUID = createField(DSL.name("guid"), SQLDataType.CHAR(36).nullable(false), this, "Public file identifier.");

    /**
     * The column <code>oagi.ai_chat_file.ai_chat_conversation_id</code>. Owning
     * AI chat conversation.
     */
    public final TableField<AiChatFileRecord, ULong> AI_CHAT_CONVERSATION_ID = createField(DSL.name("ai_chat_conversation_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Owning AI chat conversation.");

    /**
     * The column <code>oagi.ai_chat_file.request_id</code>. Request that
     * created the file.
     */
    public final TableField<AiChatFileRecord, String> REQUEST_ID = createField(DSL.name("request_id"), SQLDataType.VARCHAR(128).nullable(false), this, "Request that created the file.");

    /**
     * The column <code>oagi.ai_chat_file.format</code>. Renderer format
     * identifier.
     */
    public final TableField<AiChatFileRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.VARCHAR(64).nullable(false), this, "Renderer format identifier.");

    /**
     * The column <code>oagi.ai_chat_file.filename</code>. Safe download
     * filename.
     */
    public final TableField<AiChatFileRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(240).nullable(false), this, "Safe download filename.");

    /**
     * The column <code>oagi.ai_chat_file.media_type</code>. File media type.
     */
    public final TableField<AiChatFileRecord, String> MEDIA_TYPE = createField(DSL.name("media_type"), SQLDataType.VARCHAR(160).nullable(false), this, "File media type.");

    /**
     * The column <code>oagi.ai_chat_file.byte_size</code>. Stored content size
     * in bytes.
     */
    public final TableField<AiChatFileRecord, ULong> BYTE_SIZE = createField(DSL.name("byte_size"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Stored content size in bytes.");

    /**
     * The column <code>oagi.ai_chat_file.sha256</code>. SHA-256 digest of
     * stored content.
     */
    public final TableField<AiChatFileRecord, String> SHA256 = createField(DSL.name("sha256"), SQLDataType.CHAR(64).nullable(false), this, "SHA-256 digest of stored content.");

    /**
     * The column <code>oagi.ai_chat_file.storage_provider</code>. Configured
     * file storage provider identifier.
     */
    public final TableField<AiChatFileRecord, String> STORAGE_PROVIDER = createField(DSL.name("storage_provider"), SQLDataType.VARCHAR(64).nullable(false), this, "Configured file storage provider identifier.");

    /**
     * The column <code>oagi.ai_chat_file.storage_location</code>.
     * Provider-owned opaque object location.
     */
    public final TableField<AiChatFileRecord, String> STORAGE_LOCATION = createField(DSL.name("storage_location"), SQLDataType.VARCHAR(1024).nullable(false), this, "Provider-owned opaque object location.");

    /**
     * The column <code>oagi.ai_chat_file.creation_timestamp</code>. File
     * creation timestamp.
     */
    public final TableField<AiChatFileRecord, LocalDateTime> CREATION_TIMESTAMP = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "File creation timestamp.");

    /**
     * The column <code>oagi.ai_chat_file.expiration_timestamp</code>. File
     * retention deadline.
     */
    public final TableField<AiChatFileRecord, LocalDateTime> EXPIRATION_TIMESTAMP = createField(DSL.name("expiration_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "File retention deadline.");

    private AiChatFile(Name alias, Table<AiChatFileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiChatFile(Name alias, Table<AiChatFileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Generated Assistant file metadata and provider location history."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_file</code> table reference
     */
    public AiChatFile(String alias) {
        this(DSL.name(alias), AI_CHAT_FILE);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_file</code> table reference
     */
    public AiChatFile(Name alias) {
        this(alias, AI_CHAT_FILE);
    }

    /**
     * Create a <code>oagi.ai_chat_file</code> table reference
     */
    public AiChatFile() {
        this(DSL.name("ai_chat_file"), null);
    }

    public <O extends Record> AiChatFile(Table<O> path, ForeignKey<O, AiChatFileRecord> childPath, InverseForeignKey<O, AiChatFileRecord> parentPath) {
        super(path, childPath, parentPath, AI_CHAT_FILE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiChatFilePath extends AiChatFile implements Path<AiChatFileRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiChatFilePath(Table<O> path, ForeignKey<O, AiChatFileRecord> childPath, InverseForeignKey<O, AiChatFileRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiChatFilePath(Name alias, Table<AiChatFileRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiChatFilePath as(String alias) {
            return new AiChatFilePath(DSL.name(alias), this);
        }

        @Override
        public AiChatFilePath as(Name alias) {
            return new AiChatFilePath(alias, this);
        }

        @Override
        public AiChatFilePath as(Table<?> alias) {
            return new AiChatFilePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AI_CHAT_FILE_AI_CHAT_FILE_EXPIRY_IDX, Indexes.AI_CHAT_FILE_AI_CHAT_FILE_REQUEST_IDX);
    }

    @Override
    public Identity<AiChatFileRecord, ULong> getIdentity() {
        return (Identity<AiChatFileRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiChatFileRecord> getPrimaryKey() {
        return Keys.KEY_AI_CHAT_FILE_PRIMARY;
    }

    @Override
    public List<UniqueKey<AiChatFileRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AI_CHAT_FILE_AI_CHAT_FILE_GUID_UK, Keys.KEY_AI_CHAT_FILE_AI_CHAT_FILE_REQUEST_DIGEST_UK);
    }

    @Override
    public List<ForeignKey<AiChatFileRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_CHAT_FILE_CONVERSATION_FK);
    }

    private transient AiChatConversationPath _aiChatConversation;

    /**
     * Get the implicit join path to the <code>oagi.ai_chat_conversation</code>
     * table.
     */
    public AiChatConversationPath aiChatConversation() {
        if (_aiChatConversation == null)
            _aiChatConversation = new AiChatConversationPath(this, Keys.AI_CHAT_FILE_CONVERSATION_FK, null);

        return _aiChatConversation;
    }

    @Override
    public AiChatFile as(String alias) {
        return new AiChatFile(DSL.name(alias), this);
    }

    @Override
    public AiChatFile as(Name alias) {
        return new AiChatFile(alias, this);
    }

    @Override
    public AiChatFile as(Table<?> alias) {
        return new AiChatFile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatFile rename(String name) {
        return new AiChatFile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatFile rename(Name name) {
        return new AiChatFile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatFile rename(Table<?> name) {
        return new AiChatFile(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatFile where(Condition condition) {
        return new AiChatFile(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatFile where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatFile where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatFile where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatFile where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatFile where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatFile where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatFile where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatFile whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatFile whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
