/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Indexes;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatConversation.AiChatConversationPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiChatStepRecord;


/**
 * Complete connectCenter assistant trajectory in ATIF-reconstructable steps.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatStep extends TableImpl<AiChatStepRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_chat_step</code>
     */
    public static final AiChatStep AI_CHAT_STEP = new AiChatStep();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiChatStepRecord> getRecordType() {
        return AiChatStepRecord.class;
    }

    /**
     * The column <code>oagi.ai_chat_step.ai_chat_step_id</code>. The primary
     * key of the AI chat trajectory step record.
     */
    public final TableField<AiChatStepRecord, ULong> AI_CHAT_STEP_ID = createField(DSL.name("ai_chat_step_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "The primary key of the AI chat trajectory step record.");

    /**
     * The column <code>oagi.ai_chat_step.ai_chat_conversation_id</code>.
     * Foreign key to the AI_CHAT_CONVERSATION table identifying the owning
     * conversation.
     */
    public final TableField<AiChatStepRecord, ULong> AI_CHAT_CONVERSATION_ID = createField(DSL.name("ai_chat_conversation_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Foreign key to the AI_CHAT_CONVERSATION table identifying the owning conversation.");

    /**
     * The column <code>oagi.ai_chat_step.step_sequence</code>. The zero-based
     * sequence of the step within the complete conversation trajectory.
     */
    public final TableField<AiChatStepRecord, Long> STEP_SEQUENCE = createField(DSL.name("step_sequence"), SQLDataType.BIGINT.nullable(false), this, "The zero-based sequence of the step within the complete conversation trajectory.");

    /**
     * The column <code>oagi.ai_chat_step.request_id</code>. The request
     * identifier used to correlate steps produced by the same chat request.
     */
    public final TableField<AiChatStepRecord, String> REQUEST_ID = createField(DSL.name("request_id"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "The request identifier used to correlate steps produced by the same chat request.");

    /**
     * The column <code>oagi.ai_chat_step.source</code>. Expected ATIF sources
     * are system, user, and agent; other values are handled by the application.
     */
    public final TableField<AiChatStepRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("'system'"), SQLDataType.VARCHAR)), this, "Expected ATIF sources are system, user, and agent; other values are handled by the application.");

    /**
     * The column <code>oagi.ai_chat_step.message_kind</code>. The
     * application-specific kind of trajectory event represented by the step.
     */
    public final TableField<AiChatStepRecord, String> MESSAGE_KIND = createField(DSL.name("message_kind"), SQLDataType.VARCHAR(32).nullable(false), this, "The application-specific kind of trajectory event represented by the step.");

    /**
     * The column <code>oagi.ai_chat_step.visibility</code>. Expected
     * presentation scopes are visible and debug; other values are handled by
     * the application.
     */
    public final TableField<AiChatStepRecord, String> VISIBILITY = createField(DSL.name("visibility"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("'visible'"), SQLDataType.VARCHAR)), this, "Expected presentation scopes are visible and debug; other values are handled by the application.");

    /**
     * The column <code>oagi.ai_chat_step.message</code>. The textual message or
     * event content recorded for the step.
     */
    public final TableField<AiChatStepRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "The textual message or event content recorded for the step.");

    /**
     * The column <code>oagi.ai_chat_step.reasoning_content</code>. Optional
     * model reasoning content associated with the step.
     */
    public final TableField<AiChatStepRecord, String> REASONING_CONTENT = createField(DSL.name("reasoning_content"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "Optional model reasoning content associated with the step.");

    /**
     * The column <code>oagi.ai_chat_step.model_name</code>. The model used for
     * the inference represented by the step.
     */
    public final TableField<AiChatStepRecord, String> MODEL_NAME = createField(DSL.name("model_name"), SQLDataType.VARCHAR(240).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "The model used for the inference represented by the step.");

    /**
     * The column <code>oagi.ai_chat_step.reasoning_effort</code>. The
     * reasoning-effort setting used for the model inference.
     */
    public final TableField<AiChatStepRecord, String> REASONING_EFFORT = createField(DSL.name("reasoning_effort"), SQLDataType.VARCHAR(32).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "The reasoning-effort setting used for the model inference.");

    /**
     * The column <code>oagi.ai_chat_step.agent_runtime</code>. The agent
     * runtime selected for the conversation at this step.
     */
    public final TableField<AiChatStepRecord, String> AGENT_RUNTIME = createField(DSL.name("agent_runtime"), SQLDataType.VARCHAR(32).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "The agent runtime selected for the conversation at this step.");

    /**
     * The column <code>oagi.ai_chat_step.runtime_options_json</code>. JSON
     * object containing runtime-specific options used for the step.
     */
    public final TableField<AiChatStepRecord, String> RUNTIME_OPTIONS_JSON = createField(DSL.name("runtime_options_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "JSON object containing runtime-specific options used for the step.");

    /**
     * The column <code>oagi.ai_chat_step.tool_calls_json</code>. JSON array
     * containing tool calls requested by the model.
     */
    public final TableField<AiChatStepRecord, String> TOOL_CALLS_JSON = createField(DSL.name("tool_calls_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "JSON array containing tool calls requested by the model.");

    /**
     * The column <code>oagi.ai_chat_step.observation_json</code>. JSON object
     * containing tool execution results observed by the agent.
     */
    public final TableField<AiChatStepRecord, String> OBSERVATION_JSON = createField(DSL.name("observation_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "JSON object containing tool execution results observed by the agent.");

    /**
     * The column <code>oagi.ai_chat_step.metrics_json</code>. JSON object
     * containing token usage and other execution metrics.
     */
    public final TableField<AiChatStepRecord, String> METRICS_JSON = createField(DSL.name("metrics_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "JSON object containing token usage and other execution metrics.");

    /**
     * The column <code>oagi.ai_chat_step.extra_json</code>. JSON object
     * containing additional ATIF or application-specific step metadata.
     */
    public final TableField<AiChatStepRecord, String> EXTRA_JSON = createField(DSL.name("extra_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "JSON object containing additional ATIF or application-specific step metadata.");

    /**
     * The column <code>oagi.ai_chat_step.llm_call_count</code>. The number of
     * language-model calls represented by the step.
     */
    public final TableField<AiChatStepRecord, Integer> LLM_CALL_COUNT = createField(DSL.name("llm_call_count"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "The number of language-model calls represented by the step.");

    /**
     * The column <code>oagi.ai_chat_step.is_copied_context</code>. Indicates
     * whether the step was copied into the model context (0 = False, 1 = True).
     */
    public final TableField<AiChatStepRecord, Byte> IS_COPIED_CONTEXT = createField(DSL.name("is_copied_context"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "Indicates whether the step was copied into the model context (0 = False, 1 = True).");

    /**
     * The column <code>oagi.ai_chat_step.created_at</code>. The timestamp when
     * the trajectory step was created.
     */
    public final TableField<AiChatStepRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "The timestamp when the trajectory step was created.");

    private AiChatStep(Name alias, Table<AiChatStepRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiChatStep(Name alias, Table<AiChatStepRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Complete connectCenter assistant trajectory in ATIF-reconstructable steps."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_step</code> table reference
     */
    public AiChatStep(String alias) {
        this(DSL.name(alias), AI_CHAT_STEP);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_step</code> table reference
     */
    public AiChatStep(Name alias) {
        this(alias, AI_CHAT_STEP);
    }

    /**
     * Create a <code>oagi.ai_chat_step</code> table reference
     */
    public AiChatStep() {
        this(DSL.name("ai_chat_step"), null);
    }

    public <O extends Record> AiChatStep(Table<O> path, ForeignKey<O, AiChatStepRecord> childPath, InverseForeignKey<O, AiChatStepRecord> parentPath) {
        super(path, childPath, parentPath, AI_CHAT_STEP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiChatStepPath extends AiChatStep implements Path<AiChatStepRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiChatStepPath(Table<O> path, ForeignKey<O, AiChatStepRecord> childPath, InverseForeignKey<O, AiChatStepRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiChatStepPath(Name alias, Table<AiChatStepRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiChatStepPath as(String alias) {
            return new AiChatStepPath(DSL.name(alias), this);
        }

        @Override
        public AiChatStepPath as(Name alias) {
            return new AiChatStepPath(alias, this);
        }

        @Override
        public AiChatStepPath as(Table<?> alias) {
            return new AiChatStepPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AI_CHAT_STEP_AI_CHAT_STEP_CREATED_IDX, Indexes.AI_CHAT_STEP_AI_CHAT_STEP_REQUEST_IDX, Indexes.AI_CHAT_STEP_AI_CHAT_STEP_SETTINGS_IDX);
    }

    @Override
    public Identity<AiChatStepRecord, ULong> getIdentity() {
        return (Identity<AiChatStepRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiChatStepRecord> getPrimaryKey() {
        return Keys.KEY_AI_CHAT_STEP_PRIMARY;
    }

    @Override
    public List<UniqueKey<AiChatStepRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AI_CHAT_STEP_AI_CHAT_STEP_CONVERSATION_SEQUENCE_UK);
    }

    @Override
    public List<ForeignKey<AiChatStepRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_CHAT_STEP_CONVERSATION_FK);
    }

    private transient AiChatConversationPath _aiChatConversation;

    /**
     * Get the implicit join path to the <code>oagi.ai_chat_conversation</code>
     * table.
     */
    public AiChatConversationPath aiChatConversation() {
        if (_aiChatConversation == null)
            _aiChatConversation = new AiChatConversationPath(this, Keys.AI_CHAT_STEP_CONVERSATION_FK, null);

        return _aiChatConversation;
    }

    @Override
    public List<Check<AiChatStepRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("extra_json"), "json_valid(`extra_json`)", true),
            Internal.createCheck(this, DSL.name("metrics_json"), "json_valid(`metrics_json`)", true),
            Internal.createCheck(this, DSL.name("observation_json"), "json_valid(`observation_json`)", true),
            Internal.createCheck(this, DSL.name("runtime_options_json"), "json_valid(`runtime_options_json`)", true),
            Internal.createCheck(this, DSL.name("tool_calls_json"), "json_valid(`tool_calls_json`)", true)
        );
    }

    @Override
    public AiChatStep as(String alias) {
        return new AiChatStep(DSL.name(alias), this);
    }

    @Override
    public AiChatStep as(Name alias) {
        return new AiChatStep(alias, this);
    }

    @Override
    public AiChatStep as(Table<?> alias) {
        return new AiChatStep(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatStep rename(String name) {
        return new AiChatStep(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatStep rename(Name name) {
        return new AiChatStep(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatStep rename(Table<?> name) {
        return new AiChatStep(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatStep where(Condition condition) {
        return new AiChatStep(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatStep where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatStep where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatStep where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatStep where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatStep where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatStep where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatStep where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatStep whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatStep whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
