/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Indexes;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatConversation.AiChatConversationPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiChatMutationConfirmationRecord;


/**
 * One-time server-authoritative grants for AI mutation tool calls.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatMutationConfirmation extends TableImpl<AiChatMutationConfirmationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_chat_mutation_confirmation</code>
     */
    public static final AiChatMutationConfirmation AI_CHAT_MUTATION_CONFIRMATION = new AiChatMutationConfirmation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiChatMutationConfirmationRecord> getRecordType() {
        return AiChatMutationConfirmationRecord.class;
    }

    /**
     * The column
     * <code>oagi.ai_chat_mutation_confirmation.ai_chat_mutation_confirmation_id</code>.
     * The primary key of the AI mutation confirmation record.
     */
    public final TableField<AiChatMutationConfirmationRecord, ULong> AI_CHAT_MUTATION_CONFIRMATION_ID = createField(DSL.name("ai_chat_mutation_confirmation_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "The primary key of the AI mutation confirmation record.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.guid</code>. The
     * public unique identifier of the mutation confirmation request.
     */
    public final TableField<AiChatMutationConfirmationRecord, String> GUID = createField(DSL.name("guid"), SQLDataType.CHAR(36).nullable(false), this, "The public unique identifier of the mutation confirmation request.");

    /**
     * The column
     * <code>oagi.ai_chat_mutation_confirmation.ai_chat_conversation_id</code>.
     * Foreign key to the AI_CHAT_CONVERSATION table identifying the owning
     * conversation.
     */
    public final TableField<AiChatMutationConfirmationRecord, ULong> AI_CHAT_CONVERSATION_ID = createField(DSL.name("ai_chat_conversation_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Foreign key to the AI_CHAT_CONVERSATION table identifying the owning conversation.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.request_id</code>.
     * The chat request identifier that originally requested the data-changing
     * tool call.
     */
    public final TableField<AiChatMutationConfirmationRecord, String> REQUEST_ID = createField(DSL.name("request_id"), SQLDataType.VARCHAR(128).nullable(false), this, "The chat request identifier that originally requested the data-changing tool call.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.tool_name</code>. The
     * name of the data-changing tool that requires explicit user approval.
     */
    public final TableField<AiChatMutationConfirmationRecord, String> TOOL_NAME = createField(DSL.name("tool_name"), SQLDataType.VARCHAR(240).nullable(false), this, "The name of the data-changing tool that requires explicit user approval.");

    /**
     * The column
     * <code>oagi.ai_chat_mutation_confirmation.arguments_digest</code>. The
     * SHA-256 digest binding the tool name to its canonicalized arguments.
     */
    public final TableField<AiChatMutationConfirmationRecord, String> ARGUMENTS_DIGEST = createField(DSL.name("arguments_digest"), SQLDataType.CHAR(64).nullable(false), this, "The SHA-256 digest binding the tool name to its canonicalized arguments.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.status</code>.
     * Expected confirmation states are REQUESTED, APPROVED, DENIED, CONSUMED,
     * and EXPIRED; other values are handled by the application.
     */
    public final TableField<AiChatMutationConfirmationRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("'REQUESTED'"), SQLDataType.VARCHAR)), this, "Expected confirmation states are REQUESTED, APPROVED, DENIED, CONSUMED, and EXPIRED; other values are handled by the application.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.grant_digest</code>.
     * The SHA-256 digest of the one-time approval grant; cleared after
     * consumption, denial, or expiration.
     */
    public final TableField<AiChatMutationConfirmationRecord, String> GRANT_DIGEST = createField(DSL.name("grant_digest"), SQLDataType.CHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CHAR)), this, "The SHA-256 digest of the one-time approval grant; cleared after consumption, denial, or expiration.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.expires_at</code>.
     * The timestamp after which the confirmation request or approval grant is
     * invalid.
     */
    public final TableField<AiChatMutationConfirmationRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "The timestamp after which the confirmation request or approval grant is invalid.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.approved_at</code>.
     * The timestamp when the mutation request was approved.
     */
    public final TableField<AiChatMutationConfirmationRecord, LocalDateTime> APPROVED_AT = createField(DSL.name("approved_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "The timestamp when the mutation request was approved.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.denied_at</code>. The
     * timestamp when the mutation request was denied.
     */
    public final TableField<AiChatMutationConfirmationRecord, LocalDateTime> DENIED_AT = createField(DSL.name("denied_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "The timestamp when the mutation request was denied.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.consumed_at</code>.
     * The timestamp when the one-time approval grant was consumed.
     */
    public final TableField<AiChatMutationConfirmationRecord, LocalDateTime> CONSUMED_AT = createField(DSL.name("consumed_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "The timestamp when the one-time approval grant was consumed.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.expired_at</code>.
     * The timestamp when the confirmation request or approval grant expired.
     */
    public final TableField<AiChatMutationConfirmationRecord, LocalDateTime> EXPIRED_AT = createField(DSL.name("expired_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "The timestamp when the confirmation request or approval grant expired.");

    /**
     * The column <code>oagi.ai_chat_mutation_confirmation.created_at</code>.
     * The timestamp when the mutation confirmation request was created.
     */
    public final TableField<AiChatMutationConfirmationRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "The timestamp when the mutation confirmation request was created.");

    private AiChatMutationConfirmation(Name alias, Table<AiChatMutationConfirmationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiChatMutationConfirmation(Name alias, Table<AiChatMutationConfirmationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("One-time server-authoritative grants for AI mutation tool calls."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_mutation_confirmation</code> table
     * reference
     */
    public AiChatMutationConfirmation(String alias) {
        this(DSL.name(alias), AI_CHAT_MUTATION_CONFIRMATION);
    }

    /**
     * Create an aliased <code>oagi.ai_chat_mutation_confirmation</code> table
     * reference
     */
    public AiChatMutationConfirmation(Name alias) {
        this(alias, AI_CHAT_MUTATION_CONFIRMATION);
    }

    /**
     * Create a <code>oagi.ai_chat_mutation_confirmation</code> table reference
     */
    public AiChatMutationConfirmation() {
        this(DSL.name("ai_chat_mutation_confirmation"), null);
    }

    public <O extends Record> AiChatMutationConfirmation(Table<O> path, ForeignKey<O, AiChatMutationConfirmationRecord> childPath, InverseForeignKey<O, AiChatMutationConfirmationRecord> parentPath) {
        super(path, childPath, parentPath, AI_CHAT_MUTATION_CONFIRMATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiChatMutationConfirmationPath extends AiChatMutationConfirmation implements Path<AiChatMutationConfirmationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiChatMutationConfirmationPath(Table<O> path, ForeignKey<O, AiChatMutationConfirmationRecord> childPath, InverseForeignKey<O, AiChatMutationConfirmationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiChatMutationConfirmationPath(Name alias, Table<AiChatMutationConfirmationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiChatMutationConfirmationPath as(String alias) {
            return new AiChatMutationConfirmationPath(DSL.name(alias), this);
        }

        @Override
        public AiChatMutationConfirmationPath as(Name alias) {
            return new AiChatMutationConfirmationPath(alias, this);
        }

        @Override
        public AiChatMutationConfirmationPath as(Table<?> alias) {
            return new AiChatMutationConfirmationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AI_CHAT_MUTATION_CONFIRMATION_AI_CHAT_MUTATION_CONFIRMATION_EXPIRY_IDX, Indexes.AI_CHAT_MUTATION_CONFIRMATION_AI_CHAT_MUTATION_CONFIRMATION_REQUEST_IDX);
    }

    @Override
    public Identity<AiChatMutationConfirmationRecord, ULong> getIdentity() {
        return (Identity<AiChatMutationConfirmationRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiChatMutationConfirmationRecord> getPrimaryKey() {
        return Keys.KEY_AI_CHAT_MUTATION_CONFIRMATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<AiChatMutationConfirmationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AI_CHAT_MUTATION_CONFIRMATION_AI_CHAT_MUTATION_CONFIRMATION_GRANT_UK, Keys.KEY_AI_CHAT_MUTATION_CONFIRMATION_AI_CHAT_MUTATION_CONFIRMATION_GUID_UK);
    }

    @Override
    public List<ForeignKey<AiChatMutationConfirmationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_CHAT_MUTATION_CONFIRMATION_CONVERSATION_FK);
    }

    private transient AiChatConversationPath _aiChatConversation;

    /**
     * Get the implicit join path to the <code>oagi.ai_chat_conversation</code>
     * table.
     */
    public AiChatConversationPath aiChatConversation() {
        if (_aiChatConversation == null)
            _aiChatConversation = new AiChatConversationPath(this, Keys.AI_CHAT_MUTATION_CONFIRMATION_CONVERSATION_FK, null);

        return _aiChatConversation;
    }

    @Override
    public List<Check<AiChatMutationConfirmationRecord>> getChecks() {
        return Arrays.asList();
    }

    @Override
    public AiChatMutationConfirmation as(String alias) {
        return new AiChatMutationConfirmation(DSL.name(alias), this);
    }

    @Override
    public AiChatMutationConfirmation as(Name alias) {
        return new AiChatMutationConfirmation(alias, this);
    }

    @Override
    public AiChatMutationConfirmation as(Table<?> alias) {
        return new AiChatMutationConfirmation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatMutationConfirmation rename(String name) {
        return new AiChatMutationConfirmation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatMutationConfirmation rename(Name name) {
        return new AiChatMutationConfirmation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiChatMutationConfirmation rename(Table<?> name) {
        return new AiChatMutationConfirmation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMutationConfirmation where(Condition condition) {
        return new AiChatMutationConfirmation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMutationConfirmation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMutationConfirmation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMutationConfirmation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMutationConfirmation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMutationConfirmation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMutationConfirmation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiChatMutationConfirmation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMutationConfirmation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiChatMutationConfirmation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
