/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiModel.AiModelPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppSecret.AppSecretPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppUser.AppUserPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiProviderRecord;


/**
 * AI provider catalog and encrypted API key reference
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiProvider extends TableImpl<AiProviderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_provider</code>
     */
    public static final AiProvider AI_PROVIDER = new AiProvider();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiProviderRecord> getRecordType() {
        return AiProviderRecord.class;
    }

    /**
     * The column <code>oagi.ai_provider.ai_provider_id</code>. Identifier of
     * the AI provider
     */
    public final TableField<AiProviderRecord, ULong> AI_PROVIDER_ID = createField(DSL.name("ai_provider_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Identifier of the AI provider");

    /**
     * The column <code>oagi.ai_provider.provider_name</code>. Unique
     * application-facing name of the AI provider
     */
    public final TableField<AiProviderRecord, String> PROVIDER_NAME = createField(DSL.name("provider_name"), SQLDataType.VARCHAR(120).nullable(false), this, "Unique application-facing name of the AI provider");

    /**
     * The column <code>oagi.ai_provider.provider_type</code>. Provider adapter
     * type such as anthropic or azure-openai
     */
    public final TableField<AiProviderRecord, String> PROVIDER_TYPE = createField(DSL.name("provider_type"), SQLDataType.VARCHAR(32).nullable(false), this, "Provider adapter type such as anthropic or azure-openai");

    /**
     * The column <code>oagi.ai_provider.base_url</code>. Base endpoint URL of
     * the AI provider
     */
    public final TableField<AiProviderRecord, String> BASE_URL = createField(DSL.name("base_url"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Base endpoint URL of the AI provider");

    /**
     * The column <code>oagi.ai_provider.messages_url</code>. Optional
     * provider-specific messages endpoint URL
     */
    public final TableField<AiProviderRecord, String> MESSAGES_URL = createField(DSL.name("messages_url"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Optional provider-specific messages endpoint URL");

    /**
     * The column <code>oagi.ai_provider.anthropic_version</code>. Anthropic API
     * version sent to the provider
     */
    public final TableField<AiProviderRecord, String> ANTHROPIC_VERSION = createField(DSL.name("anthropic_version"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Anthropic API version sent to the provider");

    /**
     * The column <code>oagi.ai_provider.api_version</code>. Provider API
     * version such as the Azure OpenAI API version
     */
    public final TableField<AiProviderRecord, String> API_VERSION = createField(DSL.name("api_version"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Provider API version such as the Azure OpenAI API version");

    /**
     * The column <code>oagi.ai_provider.api_key_secret_id</code>. Encrypted API
     * key referenced from app_secret
     */
    public final TableField<AiProviderRecord, ULong> API_KEY_SECRET_ID = createField(DSL.name("api_key_secret_id"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Encrypted API key referenced from app_secret");

    /**
     * The column <code>oagi.ai_provider.enabled</code>. Indicates whether the
     * provider can serve model requests
     */
    public final TableField<AiProviderRecord, Byte> ENABLED = createField(DSL.name("enabled"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.TINYINT)), this, "Indicates whether the provider can serve model requests");

    /**
     * The column <code>oagi.ai_provider.catalog_version</code>. Optimistic
     * locking and cache invalidation version
     */
    public final TableField<AiProviderRecord, ULong> CATALOG_VERSION = createField(DSL.name("catalog_version"), SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINTUNSIGNED)), this, "Optimistic locking and cache invalidation version");

    /**
     * The column <code>oagi.ai_provider.created_by</code>. Identifier of the
     * administrator who created the provider
     */
    public final TableField<AiProviderRecord, ULong> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Identifier of the administrator who created the provider");

    /**
     * The column <code>oagi.ai_provider.last_updated_by</code>. Identifier of
     * the administrator who last updated the provider
     */
    public final TableField<AiProviderRecord, ULong> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Identifier of the administrator who last updated the provider");

    /**
     * The column <code>oagi.ai_provider.created_at</code>. Date and time when
     * the provider was created
     */
    public final TableField<AiProviderRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the provider was created");

    /**
     * The column <code>oagi.ai_provider.last_updated_at</code>. Date and time
     * when the provider was last updated
     */
    public final TableField<AiProviderRecord, LocalDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the provider was last updated");

    private AiProvider(Name alias, Table<AiProviderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiProvider(Name alias, Table<AiProviderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("AI provider catalog and encrypted API key reference"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_provider</code> table reference
     */
    public AiProvider(String alias) {
        this(DSL.name(alias), AI_PROVIDER);
    }

    /**
     * Create an aliased <code>oagi.ai_provider</code> table reference
     */
    public AiProvider(Name alias) {
        this(alias, AI_PROVIDER);
    }

    /**
     * Create a <code>oagi.ai_provider</code> table reference
     */
    public AiProvider() {
        this(DSL.name("ai_provider"), null);
    }

    public <O extends Record> AiProvider(Table<O> path, ForeignKey<O, AiProviderRecord> childPath, InverseForeignKey<O, AiProviderRecord> parentPath) {
        super(path, childPath, parentPath, AI_PROVIDER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiProviderPath extends AiProvider implements Path<AiProviderRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiProviderPath(Table<O> path, ForeignKey<O, AiProviderRecord> childPath, InverseForeignKey<O, AiProviderRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiProviderPath(Name alias, Table<AiProviderRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiProviderPath as(String alias) {
            return new AiProviderPath(DSL.name(alias), this);
        }

        @Override
        public AiProviderPath as(Name alias) {
            return new AiProviderPath(alias, this);
        }

        @Override
        public AiProviderPath as(Table<?> alias) {
            return new AiProviderPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public Identity<AiProviderRecord, ULong> getIdentity() {
        return (Identity<AiProviderRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiProviderRecord> getPrimaryKey() {
        return Keys.KEY_AI_PROVIDER_PRIMARY;
    }

    @Override
    public List<UniqueKey<AiProviderRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AI_PROVIDER_AI_PROVIDER_API_KEY_SECRET_UK, Keys.KEY_AI_PROVIDER_AI_PROVIDER_NAME_UK);
    }

    @Override
    public List<ForeignKey<AiProviderRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_PROVIDER_API_KEY_SECRET_FK, Keys.AI_PROVIDER_CREATED_BY_FK, Keys.AI_PROVIDER_LAST_UPDATED_BY_FK);
    }

    private transient AppSecretPath _appSecret;

    /**
     * Get the implicit join path to the <code>oagi.app_secret</code> table.
     */
    public AppSecretPath appSecret() {
        if (_appSecret == null)
            _appSecret = new AppSecretPath(this, Keys.AI_PROVIDER_API_KEY_SECRET_FK, null);

        return _appSecret;
    }

    private transient AppUserPath _aiProviderCreatedByFk;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table, via
     * the <code>ai_provider_created_by_fk</code> key.
     */
    public AppUserPath aiProviderCreatedByFk() {
        if (_aiProviderCreatedByFk == null)
            _aiProviderCreatedByFk = new AppUserPath(this, Keys.AI_PROVIDER_CREATED_BY_FK, null);

        return _aiProviderCreatedByFk;
    }

    private transient AppUserPath _aiProviderLastUpdatedByFk;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table, via
     * the <code>ai_provider_last_updated_by_fk</code> key.
     */
    public AppUserPath aiProviderLastUpdatedByFk() {
        if (_aiProviderLastUpdatedByFk == null)
            _aiProviderLastUpdatedByFk = new AppUserPath(this, Keys.AI_PROVIDER_LAST_UPDATED_BY_FK, null);

        return _aiProviderLastUpdatedByFk;
    }

    private transient AiModelPath _aiModel;

    /**
     * Get the implicit to-many join path to the <code>oagi.ai_model</code>
     * table
     */
    public AiModelPath aiModel() {
        if (_aiModel == null)
            _aiModel = new AiModelPath(this, null, Keys.AI_MODEL_PROVIDER_FK.getInverseKey());

        return _aiModel;
    }

    @Override
    public AiProvider as(String alias) {
        return new AiProvider(DSL.name(alias), this);
    }

    @Override
    public AiProvider as(Name alias) {
        return new AiProvider(alias, this);
    }

    @Override
    public AiProvider as(Table<?> alias) {
        return new AiProvider(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiProvider rename(String name) {
        return new AiProvider(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiProvider rename(Name name) {
        return new AiProvider(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiProvider rename(Table<?> name) {
        return new AiProvider(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiProvider where(Condition condition) {
        return new AiProvider(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiProvider where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiProvider where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiProvider where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiProvider where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiProvider where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiProvider where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiProvider where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiProvider whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiProvider whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
