/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Indexes;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppUser.AppUserPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiTokenQuotaAdjustmentRecord;


/**
 * History of manual user quota adjustments by administrators
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiTokenQuotaAdjustment extends TableImpl<AiTokenQuotaAdjustmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_token_quota_adjustment</code>
     */
    public static final AiTokenQuotaAdjustment AI_TOKEN_QUOTA_ADJUSTMENT = new AiTokenQuotaAdjustment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiTokenQuotaAdjustmentRecord> getRecordType() {
        return AiTokenQuotaAdjustmentRecord.class;
    }

    /**
     * The column
     * <code>oagi.ai_token_quota_adjustment.ai_token_quota_adjustment_id</code>.
     * Identifier of the token quota adjustment
     */
    public final TableField<AiTokenQuotaAdjustmentRecord, ULong> AI_TOKEN_QUOTA_ADJUSTMENT_ID = createField(DSL.name("ai_token_quota_adjustment_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Identifier of the token quota adjustment");

    /**
     * The column
     * <code>oagi.ai_token_quota_adjustment.target_app_user_id</code>.
     * Identifier of the user whose quota was adjusted
     */
    public final TableField<AiTokenQuotaAdjustmentRecord, ULong> TARGET_APP_USER_ID = createField(DSL.name("target_app_user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Identifier of the user whose quota was adjusted");

    /**
     * The column <code>oagi.ai_token_quota_adjustment.actor_app_user_id</code>.
     * Identifier of the administrator who adjusted the quota
     */
    public final TableField<AiTokenQuotaAdjustmentRecord, ULong> ACTOR_APP_USER_ID = createField(DSL.name("actor_app_user_id"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Identifier of the administrator who adjusted the quota");

    /**
     * The column <code>oagi.ai_token_quota_adjustment.period_start</code>.
     * Start of the adjusted quota period in UTC
     */
    public final TableField<AiTokenQuotaAdjustmentRecord, LocalDateTime> PERIOD_START = createField(DSL.name("period_start"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Start of the adjusted quota period in UTC");

    /**
     * The column <code>oagi.ai_token_quota_adjustment.delta_tokens</code>.
     * Positive or negative token amount applied to consumed usage
     */
    public final TableField<AiTokenQuotaAdjustmentRecord, Long> DELTA_TOKENS = createField(DSL.name("delta_tokens"), SQLDataType.BIGINT.nullable(false), this, "Positive or negative token amount applied to consumed usage");

    /**
     * The column <code>oagi.ai_token_quota_adjustment.reason</code>. Reason for
     * the quota adjustment
     */
    public final TableField<AiTokenQuotaAdjustmentRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(500).nullable(false), this, "Reason for the quota adjustment");

    /**
     * The column <code>oagi.ai_token_quota_adjustment.created_at</code>. Date
     * and time when the quota was adjusted
     */
    public final TableField<AiTokenQuotaAdjustmentRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the quota was adjusted");

    private AiTokenQuotaAdjustment(Name alias, Table<AiTokenQuotaAdjustmentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiTokenQuotaAdjustment(Name alias, Table<AiTokenQuotaAdjustmentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("History of manual user quota adjustments by administrators"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_token_quota_adjustment</code> table
     * reference
     */
    public AiTokenQuotaAdjustment(String alias) {
        this(DSL.name(alias), AI_TOKEN_QUOTA_ADJUSTMENT);
    }

    /**
     * Create an aliased <code>oagi.ai_token_quota_adjustment</code> table
     * reference
     */
    public AiTokenQuotaAdjustment(Name alias) {
        this(alias, AI_TOKEN_QUOTA_ADJUSTMENT);
    }

    /**
     * Create a <code>oagi.ai_token_quota_adjustment</code> table reference
     */
    public AiTokenQuotaAdjustment() {
        this(DSL.name("ai_token_quota_adjustment"), null);
    }

    public <O extends Record> AiTokenQuotaAdjustment(Table<O> path, ForeignKey<O, AiTokenQuotaAdjustmentRecord> childPath, InverseForeignKey<O, AiTokenQuotaAdjustmentRecord> parentPath) {
        super(path, childPath, parentPath, AI_TOKEN_QUOTA_ADJUSTMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiTokenQuotaAdjustmentPath extends AiTokenQuotaAdjustment implements Path<AiTokenQuotaAdjustmentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiTokenQuotaAdjustmentPath(Table<O> path, ForeignKey<O, AiTokenQuotaAdjustmentRecord> childPath, InverseForeignKey<O, AiTokenQuotaAdjustmentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiTokenQuotaAdjustmentPath(Name alias, Table<AiTokenQuotaAdjustmentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiTokenQuotaAdjustmentPath as(String alias) {
            return new AiTokenQuotaAdjustmentPath(DSL.name(alias), this);
        }

        @Override
        public AiTokenQuotaAdjustmentPath as(Name alias) {
            return new AiTokenQuotaAdjustmentPath(alias, this);
        }

        @Override
        public AiTokenQuotaAdjustmentPath as(Table<?> alias) {
            return new AiTokenQuotaAdjustmentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AI_TOKEN_QUOTA_ADJUSTMENT_AI_TOKEN_QUOTA_ADJUSTMENT_TARGET_TIME_IDX);
    }

    @Override
    public Identity<AiTokenQuotaAdjustmentRecord, ULong> getIdentity() {
        return (Identity<AiTokenQuotaAdjustmentRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiTokenQuotaAdjustmentRecord> getPrimaryKey() {
        return Keys.KEY_AI_TOKEN_QUOTA_ADJUSTMENT_PRIMARY;
    }

    @Override
    public List<ForeignKey<AiTokenQuotaAdjustmentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_TOKEN_QUOTA_ADJUSTMENT_ACTOR_FK);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.AI_TOKEN_QUOTA_ADJUSTMENT_ACTOR_FK, null);

        return _appUser;
    }

    @Override
    public AiTokenQuotaAdjustment as(String alias) {
        return new AiTokenQuotaAdjustment(DSL.name(alias), this);
    }

    @Override
    public AiTokenQuotaAdjustment as(Name alias) {
        return new AiTokenQuotaAdjustment(alias, this);
    }

    @Override
    public AiTokenQuotaAdjustment as(Table<?> alias) {
        return new AiTokenQuotaAdjustment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiTokenQuotaAdjustment rename(String name) {
        return new AiTokenQuotaAdjustment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiTokenQuotaAdjustment rename(Name name) {
        return new AiTokenQuotaAdjustment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiTokenQuotaAdjustment rename(Table<?> name) {
        return new AiTokenQuotaAdjustment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTokenQuotaAdjustment where(Condition condition) {
        return new AiTokenQuotaAdjustment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTokenQuotaAdjustment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTokenQuotaAdjustment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTokenQuotaAdjustment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTokenQuotaAdjustment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTokenQuotaAdjustment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTokenQuotaAdjustment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiTokenQuotaAdjustment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTokenQuotaAdjustment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiTokenQuotaAdjustment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
