/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiModel.AiModelPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiModelReasoningEffort.AiModelReasoningEffortPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiUserModelAccess.AiUserModelAccessPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiUserModelReasoningAccess.AiUserModelReasoningAccessPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppUser.AppUserPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiUserPolicyRecord;


/**
 * Per-user AI Assistant access and usage limit policy
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiUserPolicy extends TableImpl<AiUserPolicyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_user_policy</code>
     */
    public static final AiUserPolicy AI_USER_POLICY = new AiUserPolicy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiUserPolicyRecord> getRecordType() {
        return AiUserPolicyRecord.class;
    }

    /**
     * The column <code>oagi.ai_user_policy.app_user_id</code>. Identifier of
     * the user to whom the policy applies
     */
    public final TableField<AiUserPolicyRecord, ULong> APP_USER_ID = createField(DSL.name("app_user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Identifier of the user to whom the policy applies");

    /**
     * The column <code>oagi.ai_user_policy.ai_enabled</code>. Indicates whether
     * the user can use AI Assistant
     */
    public final TableField<AiUserPolicyRecord, Byte> AI_ENABLED = createField(DSL.name("ai_enabled"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.TINYINT)), this, "Indicates whether the user can use AI Assistant");

    /**
     * The column <code>oagi.ai_user_policy.model_access_mode</code>. Model
     * access mode: ALL or ALLOW_LIST
     */
    public final TableField<AiUserPolicyRecord, String> MODEL_ACCESS_MODE = createField(DSL.name("model_access_mode"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'ALL'"), SQLDataType.VARCHAR)), this, "Model access mode: ALL or ALLOW_LIST");

    /**
     * The column <code>oagi.ai_user_policy.default_ai_model_id</code>.
     * Identifier of the default AI model for the user
     */
    public final TableField<AiUserPolicyRecord, ULong> DEFAULT_AI_MODEL_ID = createField(DSL.name("default_ai_model_id"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Identifier of the default AI model for the user");

    /**
     * The column <code>oagi.ai_user_policy.multi_agent_enabled</code>.
     * Indicates whether the user can use multi-agent workflows
     */
    public final TableField<AiUserPolicyRecord, Byte> MULTI_AGENT_ENABLED = createField(DSL.name("multi_agent_enabled"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.TINYINT)), this, "Indicates whether the user can use multi-agent workflows");

    /**
     * The column <code>oagi.ai_user_policy.max_agents_per_request</code>.
     * Maximum number of agents allowed per request
     */
    public final TableField<AiUserPolicyRecord, UByte> MAX_AGENTS_PER_REQUEST = createField(DSL.name("max_agents_per_request"), SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("4"), SQLDataType.TINYINTUNSIGNED)), this, "Maximum number of agents allowed per request");

    /**
     * The column <code>oagi.ai_user_policy.max_active_requests</code>. Maximum
     * number of concurrent AI requests for the user
     */
    public final TableField<AiUserPolicyRecord, UByte> MAX_ACTIVE_REQUESTS = createField(DSL.name("max_active_requests"), SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("8"), SQLDataType.TINYINTUNSIGNED)), this, "Maximum number of concurrent AI requests for the user");

    /**
     * The column <code>oagi.ai_user_policy.max_output_tokens_per_call</code>.
     * Maximum number of output tokens allowed per model call
     */
    public final TableField<AiUserPolicyRecord, ULong> MAX_OUTPUT_TOKENS_PER_CALL = createField(DSL.name("max_output_tokens_per_call"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Maximum number of output tokens allowed per model call");

    /**
     * The column <code>oagi.ai_user_policy.max_total_tokens_per_request</code>.
     * Maximum total tokens allowed for a root request
     */
    public final TableField<AiUserPolicyRecord, ULong> MAX_TOTAL_TOKENS_PER_REQUEST = createField(DSL.name("max_total_tokens_per_request"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Maximum total tokens allowed for a root request");

    /**
     * The column <code>oagi.ai_user_policy.quota_period</code>. Cumulative
     * token quota period: DAILY or MONTHLY
     */
    public final TableField<AiUserPolicyRecord, String> QUOTA_PERIOD = createField(DSL.name("quota_period"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Cumulative token quota period: DAILY or MONTHLY");

    /**
     * The column <code>oagi.ai_user_policy.quota_tokens</code>. Maximum
     * cumulative tokens allowed during the quota period
     */
    public final TableField<AiUserPolicyRecord, ULong> QUOTA_TOKENS = createField(DSL.name("quota_tokens"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Maximum cumulative tokens allowed during the quota period");

    /**
     * The column <code>oagi.ai_user_policy.policy_version</code>. Policy
     * version used for optimistic locking
     */
    public final TableField<AiUserPolicyRecord, ULong> POLICY_VERSION = createField(DSL.name("policy_version"), SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINTUNSIGNED)), this, "Policy version used for optimistic locking");

    /**
     * The column <code>oagi.ai_user_policy.created_by</code>. Identifier of the
     * administrator who created the policy
     */
    public final TableField<AiUserPolicyRecord, ULong> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Identifier of the administrator who created the policy");

    /**
     * The column <code>oagi.ai_user_policy.last_updated_by</code>. Identifier
     * of the administrator who last updated the policy
     */
    public final TableField<AiUserPolicyRecord, ULong> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Identifier of the administrator who last updated the policy");

    /**
     * The column <code>oagi.ai_user_policy.created_at</code>. Date and time
     * when the policy was created
     */
    public final TableField<AiUserPolicyRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the policy was created");

    /**
     * The column <code>oagi.ai_user_policy.last_updated_at</code>. Date and
     * time when the policy was last updated
     */
    public final TableField<AiUserPolicyRecord, LocalDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the policy was last updated");

    private AiUserPolicy(Name alias, Table<AiUserPolicyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiUserPolicy(Name alias, Table<AiUserPolicyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Per-user AI Assistant access and usage limit policy"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_user_policy</code> table reference
     */
    public AiUserPolicy(String alias) {
        this(DSL.name(alias), AI_USER_POLICY);
    }

    /**
     * Create an aliased <code>oagi.ai_user_policy</code> table reference
     */
    public AiUserPolicy(Name alias) {
        this(alias, AI_USER_POLICY);
    }

    /**
     * Create a <code>oagi.ai_user_policy</code> table reference
     */
    public AiUserPolicy() {
        this(DSL.name("ai_user_policy"), null);
    }

    public <O extends Record> AiUserPolicy(Table<O> path, ForeignKey<O, AiUserPolicyRecord> childPath, InverseForeignKey<O, AiUserPolicyRecord> parentPath) {
        super(path, childPath, parentPath, AI_USER_POLICY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiUserPolicyPath extends AiUserPolicy implements Path<AiUserPolicyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiUserPolicyPath(Table<O> path, ForeignKey<O, AiUserPolicyRecord> childPath, InverseForeignKey<O, AiUserPolicyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiUserPolicyPath(Name alias, Table<AiUserPolicyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiUserPolicyPath as(String alias) {
            return new AiUserPolicyPath(DSL.name(alias), this);
        }

        @Override
        public AiUserPolicyPath as(Name alias) {
            return new AiUserPolicyPath(alias, this);
        }

        @Override
        public AiUserPolicyPath as(Table<?> alias) {
            return new AiUserPolicyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public UniqueKey<AiUserPolicyRecord> getPrimaryKey() {
        return Keys.KEY_AI_USER_POLICY_PRIMARY;
    }

    @Override
    public List<ForeignKey<AiUserPolicyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_USER_POLICY_CREATED_BY_FK, Keys.AI_USER_POLICY_DEFAULT_MODEL_FK, Keys.AI_USER_POLICY_LAST_UPDATED_BY_FK, Keys.AI_USER_POLICY_USER_FK);
    }

    private transient AppUserPath _aiUserPolicyCreatedByFk;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table, via
     * the <code>ai_user_policy_created_by_fk</code> key.
     */
    public AppUserPath aiUserPolicyCreatedByFk() {
        if (_aiUserPolicyCreatedByFk == null)
            _aiUserPolicyCreatedByFk = new AppUserPath(this, Keys.AI_USER_POLICY_CREATED_BY_FK, null);

        return _aiUserPolicyCreatedByFk;
    }

    private transient AiModelPath _aiModel;

    /**
     * Get the implicit join path to the <code>oagi.ai_model</code> table.
     */
    public AiModelPath aiModel() {
        if (_aiModel == null)
            _aiModel = new AiModelPath(this, Keys.AI_USER_POLICY_DEFAULT_MODEL_FK, null);

        return _aiModel;
    }

    private transient AppUserPath _aiUserPolicyLastUpdatedByFk;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table, via
     * the <code>ai_user_policy_last_updated_by_fk</code> key.
     */
    public AppUserPath aiUserPolicyLastUpdatedByFk() {
        if (_aiUserPolicyLastUpdatedByFk == null)
            _aiUserPolicyLastUpdatedByFk = new AppUserPath(this, Keys.AI_USER_POLICY_LAST_UPDATED_BY_FK, null);

        return _aiUserPolicyLastUpdatedByFk;
    }

    private transient AppUserPath _aiUserPolicyUserFk;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table, via
     * the <code>ai_user_policy_user_fk</code> key.
     */
    public AppUserPath aiUserPolicyUserFk() {
        if (_aiUserPolicyUserFk == null)
            _aiUserPolicyUserFk = new AppUserPath(this, Keys.AI_USER_POLICY_USER_FK, null);

        return _aiUserPolicyUserFk;
    }

    private transient AiUserModelAccessPath _aiUserModelAccess;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.ai_user_model_access</code> table
     */
    public AiUserModelAccessPath aiUserModelAccess() {
        if (_aiUserModelAccess == null)
            _aiUserModelAccess = new AiUserModelAccessPath(this, null, Keys.AI_USER_MODEL_ACCESS_POLICY_FK.getInverseKey());

        return _aiUserModelAccess;
    }

    private transient AiUserModelReasoningAccessPath _aiUserModelReasoningAccess;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.ai_user_model_reasoning_access</code> table
     */
    public AiUserModelReasoningAccessPath aiUserModelReasoningAccess() {
        if (_aiUserModelReasoningAccess == null)
            _aiUserModelReasoningAccess = new AiUserModelReasoningAccessPath(this, null, Keys.AI_USER_MODEL_REASONING_ACCESS_POLICY_FK.getInverseKey());

        return _aiUserModelReasoningAccess;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>oagi.ai_model_reasoning_effort</code> table
     */
    public AiModelReasoningEffortPath aiModelReasoningEffort() {
        return aiUserModelReasoningAccess().aiModelReasoningEffort();
    }

    @Override
    public AiUserPolicy as(String alias) {
        return new AiUserPolicy(DSL.name(alias), this);
    }

    @Override
    public AiUserPolicy as(Name alias) {
        return new AiUserPolicy(alias, this);
    }

    @Override
    public AiUserPolicy as(Table<?> alias) {
        return new AiUserPolicy(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserPolicy rename(String name) {
        return new AiUserPolicy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserPolicy rename(Name name) {
        return new AiUserPolicy(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserPolicy rename(Table<?> name) {
        return new AiUserPolicy(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicy where(Condition condition) {
        return new AiUserPolicy(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicy where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicy where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicy where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicy where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicy where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicy where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicy where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicy whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicy whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
