/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiModelReasoningEffort.AiModelReasoningEffortPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiUserPolicy.AiUserPolicyPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiUserModelReasoningAccessRecord;


/**
 * Per-user and per-model reasoning effort allowlist
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiUserModelReasoningAccess extends TableImpl<AiUserModelReasoningAccessRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>oagi.ai_user_model_reasoning_access</code>
     */
    public static final AiUserModelReasoningAccess AI_USER_MODEL_REASONING_ACCESS = new AiUserModelReasoningAccess();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiUserModelReasoningAccessRecord> getRecordType() {
        return AiUserModelReasoningAccessRecord.class;
    }

    /**
     * The column <code>oagi.ai_user_model_reasoning_access.app_user_id</code>.
     * Identifier of the user to whom the policy applies
     */
    public final TableField<AiUserModelReasoningAccessRecord, ULong> APP_USER_ID = createField(DSL.name("app_user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Identifier of the user to whom the policy applies");

    /**
     * The column <code>oagi.ai_user_model_reasoning_access.ai_model_id</code>.
     * Identifier of the AI model subject to the reasoning effort restriction
     */
    public final TableField<AiUserModelReasoningAccessRecord, ULong> AI_MODEL_ID = createField(DSL.name("ai_model_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Identifier of the AI model subject to the reasoning effort restriction");

    /**
     * The column
     * <code>oagi.ai_user_model_reasoning_access.reasoning_effort</code>. Name
     * of a reasoning effort allowed for the user
     */
    public final TableField<AiUserModelReasoningAccessRecord, String> REASONING_EFFORT = createField(DSL.name("reasoning_effort"), SQLDataType.VARCHAR(32).nullable(false), this, "Name of a reasoning effort allowed for the user");

    private AiUserModelReasoningAccess(Name alias, Table<AiUserModelReasoningAccessRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiUserModelReasoningAccess(Name alias, Table<AiUserModelReasoningAccessRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Per-user and per-model reasoning effort allowlist"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_user_model_reasoning_access</code> table
     * reference
     */
    public AiUserModelReasoningAccess(String alias) {
        this(DSL.name(alias), AI_USER_MODEL_REASONING_ACCESS);
    }

    /**
     * Create an aliased <code>oagi.ai_user_model_reasoning_access</code> table
     * reference
     */
    public AiUserModelReasoningAccess(Name alias) {
        this(alias, AI_USER_MODEL_REASONING_ACCESS);
    }

    /**
     * Create a <code>oagi.ai_user_model_reasoning_access</code> table reference
     */
    public AiUserModelReasoningAccess() {
        this(DSL.name("ai_user_model_reasoning_access"), null);
    }

    public <O extends Record> AiUserModelReasoningAccess(Table<O> path, ForeignKey<O, AiUserModelReasoningAccessRecord> childPath, InverseForeignKey<O, AiUserModelReasoningAccessRecord> parentPath) {
        super(path, childPath, parentPath, AI_USER_MODEL_REASONING_ACCESS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiUserModelReasoningAccessPath extends AiUserModelReasoningAccess implements Path<AiUserModelReasoningAccessRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiUserModelReasoningAccessPath(Table<O> path, ForeignKey<O, AiUserModelReasoningAccessRecord> childPath, InverseForeignKey<O, AiUserModelReasoningAccessRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiUserModelReasoningAccessPath(Name alias, Table<AiUserModelReasoningAccessRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiUserModelReasoningAccessPath as(String alias) {
            return new AiUserModelReasoningAccessPath(DSL.name(alias), this);
        }

        @Override
        public AiUserModelReasoningAccessPath as(Name alias) {
            return new AiUserModelReasoningAccessPath(alias, this);
        }

        @Override
        public AiUserModelReasoningAccessPath as(Table<?> alias) {
            return new AiUserModelReasoningAccessPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public UniqueKey<AiUserModelReasoningAccessRecord> getPrimaryKey() {
        return Keys.KEY_AI_USER_MODEL_REASONING_ACCESS_PRIMARY;
    }

    @Override
    public List<ForeignKey<AiUserModelReasoningAccessRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_USER_MODEL_REASONING_ACCESS_EFFORT_FK, Keys.AI_USER_MODEL_REASONING_ACCESS_POLICY_FK);
    }

    private transient AiModelReasoningEffortPath _aiModelReasoningEffort;

    /**
     * Get the implicit join path to the
     * <code>oagi.ai_model_reasoning_effort</code> table.
     */
    public AiModelReasoningEffortPath aiModelReasoningEffort() {
        if (_aiModelReasoningEffort == null)
            _aiModelReasoningEffort = new AiModelReasoningEffortPath(this, Keys.AI_USER_MODEL_REASONING_ACCESS_EFFORT_FK, null);

        return _aiModelReasoningEffort;
    }

    private transient AiUserPolicyPath _aiUserPolicy;

    /**
     * Get the implicit join path to the <code>oagi.ai_user_policy</code> table.
     */
    public AiUserPolicyPath aiUserPolicy() {
        if (_aiUserPolicy == null)
            _aiUserPolicy = new AiUserPolicyPath(this, Keys.AI_USER_MODEL_REASONING_ACCESS_POLICY_FK, null);

        return _aiUserPolicy;
    }

    @Override
    public AiUserModelReasoningAccess as(String alias) {
        return new AiUserModelReasoningAccess(DSL.name(alias), this);
    }

    @Override
    public AiUserModelReasoningAccess as(Name alias) {
        return new AiUserModelReasoningAccess(alias, this);
    }

    @Override
    public AiUserModelReasoningAccess as(Table<?> alias) {
        return new AiUserModelReasoningAccess(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserModelReasoningAccess rename(String name) {
        return new AiUserModelReasoningAccess(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserModelReasoningAccess rename(Name name) {
        return new AiUserModelReasoningAccess(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserModelReasoningAccess rename(Table<?> name) {
        return new AiUserModelReasoningAccess(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserModelReasoningAccess where(Condition condition) {
        return new AiUserModelReasoningAccess(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserModelReasoningAccess where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserModelReasoningAccess where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserModelReasoningAccess where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserModelReasoningAccess where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserModelReasoningAccess where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserModelReasoningAccess where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserModelReasoningAccess where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserModelReasoningAccess whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserModelReasoningAccess whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
