/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Indexes;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppUser.AppUserPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AiUserPolicyAuditRecord;


/**
 * Audit history of AI user policy changes
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiUserPolicyAudit extends TableImpl<AiUserPolicyAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.ai_user_policy_audit</code>
     */
    public static final AiUserPolicyAudit AI_USER_POLICY_AUDIT = new AiUserPolicyAudit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AiUserPolicyAuditRecord> getRecordType() {
        return AiUserPolicyAuditRecord.class;
    }

    /**
     * The column
     * <code>oagi.ai_user_policy_audit.ai_user_policy_audit_id</code>.
     * Identifier of the AI user policy audit entry
     */
    public final TableField<AiUserPolicyAuditRecord, ULong> AI_USER_POLICY_AUDIT_ID = createField(DSL.name("ai_user_policy_audit_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Identifier of the AI user policy audit entry");

    /**
     * The column <code>oagi.ai_user_policy_audit.target_app_user_id</code>.
     * Identifier of the user whose policy was changed
     */
    public final TableField<AiUserPolicyAuditRecord, ULong> TARGET_APP_USER_ID = createField(DSL.name("target_app_user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Identifier of the user whose policy was changed");

    /**
     * The column <code>oagi.ai_user_policy_audit.actor_app_user_id</code>.
     * Identifier of the administrator who changed the policy
     */
    public final TableField<AiUserPolicyAuditRecord, ULong> ACTOR_APP_USER_ID = createField(DSL.name("actor_app_user_id"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "Identifier of the administrator who changed the policy");

    /**
     * The column <code>oagi.ai_user_policy_audit.action</code>. Policy change
     * action: CREATE, UPDATE, or DELETE
     */
    public final TableField<AiUserPolicyAuditRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.VARCHAR(16).nullable(false), this, "Policy change action: CREATE, UPDATE, or DELETE");

    /**
     * The column <code>oagi.ai_user_policy_audit.before_json</code>. Canonical
     * policy snapshot before the change
     */
    public final TableField<AiUserPolicyAuditRecord, String> BEFORE_JSON = createField(DSL.name("before_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "Canonical policy snapshot before the change");

    /**
     * The column <code>oagi.ai_user_policy_audit.after_json</code>. Canonical
     * policy snapshot after the change
     */
    public final TableField<AiUserPolicyAuditRecord, String> AFTER_JSON = createField(DSL.name("after_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "Canonical policy snapshot after the change");

    /**
     * The column <code>oagi.ai_user_policy_audit.reason</code>. Reason or
     * administrator comment for the policy change
     */
    public final TableField<AiUserPolicyAuditRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "Reason or administrator comment for the policy change");

    /**
     * The column <code>oagi.ai_user_policy_audit.created_at</code>. Date and
     * time when the policy was changed
     */
    public final TableField<AiUserPolicyAuditRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the policy was changed");

    private AiUserPolicyAudit(Name alias, Table<AiUserPolicyAuditRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AiUserPolicyAudit(Name alias, Table<AiUserPolicyAuditRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Audit history of AI user policy changes"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.ai_user_policy_audit</code> table reference
     */
    public AiUserPolicyAudit(String alias) {
        this(DSL.name(alias), AI_USER_POLICY_AUDIT);
    }

    /**
     * Create an aliased <code>oagi.ai_user_policy_audit</code> table reference
     */
    public AiUserPolicyAudit(Name alias) {
        this(alias, AI_USER_POLICY_AUDIT);
    }

    /**
     * Create a <code>oagi.ai_user_policy_audit</code> table reference
     */
    public AiUserPolicyAudit() {
        this(DSL.name("ai_user_policy_audit"), null);
    }

    public <O extends Record> AiUserPolicyAudit(Table<O> path, ForeignKey<O, AiUserPolicyAuditRecord> childPath, InverseForeignKey<O, AiUserPolicyAuditRecord> parentPath) {
        super(path, childPath, parentPath, AI_USER_POLICY_AUDIT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AiUserPolicyAuditPath extends AiUserPolicyAudit implements Path<AiUserPolicyAuditRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AiUserPolicyAuditPath(Table<O> path, ForeignKey<O, AiUserPolicyAuditRecord> childPath, InverseForeignKey<O, AiUserPolicyAuditRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AiUserPolicyAuditPath(Name alias, Table<AiUserPolicyAuditRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AiUserPolicyAuditPath as(String alias) {
            return new AiUserPolicyAuditPath(DSL.name(alias), this);
        }

        @Override
        public AiUserPolicyAuditPath as(Name alias) {
            return new AiUserPolicyAuditPath(alias, this);
        }

        @Override
        public AiUserPolicyAuditPath as(Table<?> alias) {
            return new AiUserPolicyAuditPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AI_USER_POLICY_AUDIT_AI_USER_POLICY_AUDIT_TARGET_TIME_IDX);
    }

    @Override
    public Identity<AiUserPolicyAuditRecord, ULong> getIdentity() {
        return (Identity<AiUserPolicyAuditRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AiUserPolicyAuditRecord> getPrimaryKey() {
        return Keys.KEY_AI_USER_POLICY_AUDIT_PRIMARY;
    }

    @Override
    public List<ForeignKey<AiUserPolicyAuditRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AI_USER_POLICY_AUDIT_ACTOR_FK);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.AI_USER_POLICY_AUDIT_ACTOR_FK, null);

        return _appUser;
    }

    @Override
    public List<Check<AiUserPolicyAuditRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("after_json"), "json_valid(`after_json`)", true),
            Internal.createCheck(this, DSL.name("before_json"), "json_valid(`before_json`)", true)
        );
    }

    @Override
    public AiUserPolicyAudit as(String alias) {
        return new AiUserPolicyAudit(DSL.name(alias), this);
    }

    @Override
    public AiUserPolicyAudit as(Name alias) {
        return new AiUserPolicyAudit(alias, this);
    }

    @Override
    public AiUserPolicyAudit as(Table<?> alias) {
        return new AiUserPolicyAudit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserPolicyAudit rename(String name) {
        return new AiUserPolicyAudit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserPolicyAudit rename(Name name) {
        return new AiUserPolicyAudit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AiUserPolicyAudit rename(Table<?> name) {
        return new AiUserPolicyAudit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicyAudit where(Condition condition) {
        return new AiUserPolicyAudit(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicyAudit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicyAudit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicyAudit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicyAudit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicyAudit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicyAudit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AiUserPolicyAudit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicyAudit whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AiUserPolicyAudit whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
