/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.jooq.types.UShort;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Keys;
import org.oagi.score.gateway.http.common.repository.jooq.entity.Oagi;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiProvider.AiProviderPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AppUser.AppUserPath;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records.AppSecretRecord;


/**
 * Encrypted application secrets; initially limited to AI provider API keys
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppSecret extends TableImpl<AppSecretRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oagi.app_secret</code>
     */
    public static final AppSecret APP_SECRET = new AppSecret();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppSecretRecord> getRecordType() {
        return AppSecretRecord.class;
    }

    /**
     * The column <code>oagi.app_secret.app_secret_id</code>. Identifier of the
     * encrypted application secret
     */
    public final TableField<AppSecretRecord, ULong> APP_SECRET_ID = createField(DSL.name("app_secret_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Identifier of the encrypted application secret");

    /**
     * The column <code>oagi.app_secret.secret_guid</code>. Stable UUID used as
     * authenticated encryption context
     */
    public final TableField<AppSecretRecord, String> SECRET_GUID = createField(DSL.name("secret_guid"), SQLDataType.CHAR(36).nullable(false), this, "Stable UUID used as authenticated encryption context");

    /**
     * The column <code>oagi.app_secret.secret_name</code>. Unique logical name
     * of the application secret
     */
    public final TableField<AppSecretRecord, String> SECRET_NAME = createField(DSL.name("secret_name"), SQLDataType.VARCHAR(255).nullable(false), this, "Unique logical name of the application secret");

    /**
     * The column <code>oagi.app_secret.secret_type</code>. Secret type such as
     * AI_PROVIDER_API_KEY
     */
    public final TableField<AppSecretRecord, String> SECRET_TYPE = createField(DSL.name("secret_type"), SQLDataType.VARCHAR(32).nullable(false), this, "Secret type such as AI_PROVIDER_API_KEY");

    /**
     * The column <code>oagi.app_secret.encrypted_value</code>. AES-256-GCM
     * ciphertext including the authentication tag
     */
    public final TableField<AppSecretRecord, byte[]> ENCRYPTED_VALUE = createField(DSL.name("encrypted_value"), SQLDataType.BLOB(16777215).nullable(false), this, "AES-256-GCM ciphertext including the authentication tag");

    /**
     * The column <code>oagi.app_secret.nonce</code>. Unique 96-bit AES-GCM
     * nonce for this encrypted value
     */
    public final TableField<AppSecretRecord, byte[]> NONCE = createField(DSL.name("nonce"), SQLDataType.BINARY(12).nullable(false), this, "Unique 96-bit AES-GCM nonce for this encrypted value");

    /**
     * The column <code>oagi.app_secret.encryption_key_id</code>. Identifier of
     * the application encryption key used for this value
     */
    public final TableField<AppSecretRecord, String> ENCRYPTION_KEY_ID = createField(DSL.name("encryption_key_id"), SQLDataType.VARCHAR(64).nullable(false), this, "Identifier of the application encryption key used for this value");

    /**
     * The column <code>oagi.app_secret.encryption_version</code>. Version of
     * the encryption payload format
     */
    public final TableField<AppSecretRecord, UShort> ENCRYPTION_VERSION = createField(DSL.name("encryption_version"), SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINTUNSIGNED)), this, "Version of the encryption payload format");

    /**
     * The column <code>oagi.app_secret.created_by</code>. Identifier of the
     * administrator who created the secret
     */
    public final TableField<AppSecretRecord, ULong> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Identifier of the administrator who created the secret");

    /**
     * The column <code>oagi.app_secret.last_updated_by</code>. Identifier of
     * the administrator who last updated the secret
     */
    public final TableField<AppSecretRecord, ULong> LAST_UPDATED_BY = createField(DSL.name("last_updated_by"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "Identifier of the administrator who last updated the secret");

    /**
     * The column <code>oagi.app_secret.creation_timestamp</code>. Date and time
     * when the secret was created
     */
    public final TableField<AppSecretRecord, LocalDateTime> CREATION_TIMESTAMP = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the secret was created");

    /**
     * The column <code>oagi.app_secret.last_update_timestamp</code>. Date and
     * time when the secret was last updated
     */
    public final TableField<AppSecretRecord, LocalDateTime> LAST_UPDATE_TIMESTAMP = createField(DSL.name("last_update_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "Date and time when the secret was last updated");

    private AppSecret(Name alias, Table<AppSecretRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppSecret(Name alias, Table<AppSecretRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Encrypted application secrets; initially limited to AI provider API keys"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.app_secret</code> table reference
     */
    public AppSecret(String alias) {
        this(DSL.name(alias), APP_SECRET);
    }

    /**
     * Create an aliased <code>oagi.app_secret</code> table reference
     */
    public AppSecret(Name alias) {
        this(alias, APP_SECRET);
    }

    /**
     * Create a <code>oagi.app_secret</code> table reference
     */
    public AppSecret() {
        this(DSL.name("app_secret"), null);
    }

    public <O extends Record> AppSecret(Table<O> path, ForeignKey<O, AppSecretRecord> childPath, InverseForeignKey<O, AppSecretRecord> parentPath) {
        super(path, childPath, parentPath, APP_SECRET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AppSecretPath extends AppSecret implements Path<AppSecretRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppSecretPath(Table<O> path, ForeignKey<O, AppSecretRecord> childPath, InverseForeignKey<O, AppSecretRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppSecretPath(Name alias, Table<AppSecretRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppSecretPath as(String alias) {
            return new AppSecretPath(DSL.name(alias), this);
        }

        @Override
        public AppSecretPath as(Name alias) {
            return new AppSecretPath(alias, this);
        }

        @Override
        public AppSecretPath as(Table<?> alias) {
            return new AppSecretPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public Identity<AppSecretRecord, ULong> getIdentity() {
        return (Identity<AppSecretRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<AppSecretRecord> getPrimaryKey() {
        return Keys.KEY_APP_SECRET_PRIMARY;
    }

    @Override
    public List<UniqueKey<AppSecretRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_APP_SECRET_APP_SECRET_GUID_UK, Keys.KEY_APP_SECRET_APP_SECRET_NAME_UK);
    }

    @Override
    public List<ForeignKey<AppSecretRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APP_SECRET_CREATED_BY_FK, Keys.APP_SECRET_LAST_UPDATED_BY_FK);
    }

    private transient AppUserPath _appSecretCreatedByFk;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table, via
     * the <code>app_secret_created_by_fk</code> key.
     */
    public AppUserPath appSecretCreatedByFk() {
        if (_appSecretCreatedByFk == null)
            _appSecretCreatedByFk = new AppUserPath(this, Keys.APP_SECRET_CREATED_BY_FK, null);

        return _appSecretCreatedByFk;
    }

    private transient AppUserPath _appSecretLastUpdatedByFk;

    /**
     * Get the implicit join path to the <code>oagi.app_user</code> table, via
     * the <code>app_secret_last_updated_by_fk</code> key.
     */
    public AppUserPath appSecretLastUpdatedByFk() {
        if (_appSecretLastUpdatedByFk == null)
            _appSecretLastUpdatedByFk = new AppUserPath(this, Keys.APP_SECRET_LAST_UPDATED_BY_FK, null);

        return _appSecretLastUpdatedByFk;
    }

    private transient AiProviderPath _aiProvider;

    /**
     * Get the implicit to-many join path to the <code>oagi.ai_provider</code>
     * table
     */
    public AiProviderPath aiProvider() {
        if (_aiProvider == null)
            _aiProvider = new AiProviderPath(this, null, Keys.AI_PROVIDER_API_KEY_SECRET_FK.getInverseKey());

        return _aiProvider;
    }

    @Override
    public AppSecret as(String alias) {
        return new AppSecret(DSL.name(alias), this);
    }

    @Override
    public AppSecret as(Name alias) {
        return new AppSecret(alias, this);
    }

    @Override
    public AppSecret as(Table<?> alias) {
        return new AppSecret(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppSecret rename(String name) {
        return new AppSecret(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppSecret rename(Name name) {
        return new AppSecret(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppSecret rename(Table<?> name) {
        return new AppSecret(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppSecret where(Condition condition) {
        return new AppSecret(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppSecret where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppSecret where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppSecret where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppSecret where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppSecret where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppSecret where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppSecret where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppSecret whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppSecret whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
