package org.oagi.score.gateway.http.api.ai_management.policy.exception;

public enum AiPolicyErrorCode {
    AI_DISABLED_BY_POLICY,
    AI_MODEL_NOT_ALLOWED,
    AI_REASONING_EFFORT_NOT_ALLOWED,
    AI_NO_ALLOWED_MODELS,
    AI_QUOTA_EXHAUSTED,
    AI_REQUEST_TOKEN_LIMIT_EXHAUSTED,
    AI_ACTIVE_REQUEST_LIMIT,
    AI_POLICY_VERSION_CONFLICT,
    AI_CATALOG_VERSION_CONFLICT,
    AI_PROVIDER_NOT_CONFIGURED
}
