package org.oagi.score.gateway.http.api.ai_management.catalog.model.profile.openai;

import org.oagi.score.gateway.http.api.ai_management.catalog.model.profile.AiModelOption;
import org.oagi.score.gateway.http.api.ai_management.catalog.model.profile.ReasoningEffort;

import java.util.ArrayList;
import java.util.List;

/** Spring AI OpenAI reference chat options, filtered by each GPT-5 model specification. */
final class OpenAiChatOptionProfiles {
    private OpenAiChatOptionProfiles() {}

    static List<AiModelOption> options(String model, OpenAiModelProfileSpec spec) {
        List<ReasoningEffort> reasoningEfforts = spec.reasoningEfforts();
        List<AiModelOption> options = new ArrayList<>();
        options.add(string("model", model, "Name of the OpenAI model or Microsoft Foundry deployment."));
        options.add(string("baseUrl", "", "OpenAI chat API base URL inherited from the provider when empty."));
        options.add(string("apiKey", "", "OpenAI API key inherited from the provider when empty."));
        options.add(string("credential", "", "Microsoft Foundry credential configuration."));
        options.add(string("deploymentName", "", "Microsoft Foundry deployment name."));
        options.add(string("microsoftFoundryServiceVersion", "",
                "Microsoft Foundry API service version."));
        options.add(string("organizationId", "", "OpenAI organization identifier."));
        options.add(string("projectId", "", "OpenAI project identifier."));
        options.add(bool("microsoftFoundry", false, "Whether the endpoint is Microsoft Foundry."));
        options.add(bool("gitHubModels", false, "Whether the endpoint is GitHub Models."));
        options.add(string("timeout", "60s", "OpenAI client request timeout."));
        options.add(integer("maxRetries", 3, "Maximum number of SDK retry attempts."));
        options.add(string("proxy", "", "HTTP proxy configuration."));
        options.add(json("customHeaders", null, "JSON object of client-level HTTP headers."));
        options.add(json("httpHeaders", null, "JSON object of chat-completion request headers."));
        options.add(integer("topLogprobs", null,
                "Number of most likely output tokens returned at each position."));
        options.add(integer("maxCompletionTokens", spec.maxOutputTokens(),
                "Maximum visible and reasoning tokens generated by a reasoning model."));
        if (spec.structuredOutputs()) {
            options.add(enumeration("responseFormatType", "TEXT",
                    "Response format type.", "TEXT", "JSON_OBJECT", "JSON_SCHEMA"));
            options.add(string("responseFormatName", "custom_schema",
                    "Schema name used when the response format type is JSON_SCHEMA."));
            options.add(json("responseFormatSchema", null, "JSON Schema for structured output."));
            options.add(bool("responseFormatStrict", null,
                    "Whether JSON_SCHEMA output must adhere strictly to the supplied schema."));
        }
        if (spec.streaming()) {
            // The application uses OpenAI's Responses endpoint. Unlike Chat Completions,
            // Responses always reports usage and exposes no include_usage request switch.
            options.add(json("streamOptions", null,
                    "Responses API streaming configuration, including obfuscation and additional fields."));
            options.add(bool("includeObfuscation", null,
                    "Include OpenAI streaming obfuscation fields to normalize chunk sizes and timing."));
            options.add(json("streamAdditionalProperties", null,
                    "JSON additional properties forwarded in the OpenAI stream-options object."));
        }
        options.add(decimal("topP", null,
                "Nucleus-sampling probability. Avoid changing it together with temperature."));
        options.add(string("user", "",
                "Legacy end-user identifier used for abuse detection."));
        options.add(bool("store", false,
                "Allow OpenAI to store the completion for platform features."));
        options.add(json("metadata", null, "JSON developer tags stored with the completion."));
        options.add(enumeration("reasoningEffort", defaultEffort(reasoningEfforts),
                "Reasoning effort used by the GPT-5 reasoning model.", reasoningEfforts.stream()
                        .map(ReasoningEffort::name).toArray(String[]::new)));
        options.add(enumeration("verbosity", "medium", "Amount of detail in the response.",
                "low", "medium", "high"));
        options.add(enumeration("serviceTier", null, "Processing tier used to serve the request.",
                "auto", "default", "flex", "priority"));
        options.add(string("promptCacheKey", "",
                "Cache key that improves cache-hit rates for similar requests."));
        options.add(string("safetyIdentifier", "",
                "Stable hashed end-user identifier used by OpenAI for safety-policy enforcement."));
        options.add(json("extraBody", null,
                "JSON extra request fields for OpenAI-compatible providers; unknown fields are rejected by OpenAI."));
        return List.copyOf(options);
    }

    private static String defaultEffort(List<ReasoningEffort> efforts) {
        return efforts.stream().filter(ReasoningEffort::defaultEffort)
                .map(ReasoningEffort::name).findFirst().orElse(efforts.getFirst().name());
    }

    private static AiModelOption bool(String key, Boolean value, String description) {
        return new AiModelOption(key, "boolean", value, description, List.of());
    }

    private static AiModelOption integer(String key, Number value, String description) {
        return new AiModelOption(key, "integer", value, description, List.of());
    }

    private static AiModelOption decimal(String key, Number value, String description) {
        return new AiModelOption(key, "decimal", value, description, List.of());
    }

    private static AiModelOption string(String key, String value, String description) {
        return new AiModelOption(key, "string", value, description, List.of());
    }

    private static AiModelOption json(String key, Object value, String description) {
        return new AiModelOption(key, "json", value, description, List.of());
    }

    private static AiModelOption enumeration(String key, String value, String description,
                                             String... allowedValues) {
        return new AiModelOption(key, "enum", value, description, List.of(allowedValues));
    }
}
