/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.jooq.types.UShort;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ActivityEventTarget;


/**
 * Append-only resource targets associated with normalized activity events.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityEventTargetRecord extends UpdatableRecordImpl<ActivityEventTargetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.activity_event_target.activity_event_id</code>. The
     * activity event that owns this target record.
     */
    public void setActivityEventId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.activity_event_id</code>. The
     * activity event that owns this target record.
     */
    public ULong getActivityEventId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.activity_event_target.target_ordinal</code>. The
     * zero-based target order within the owning activity event.
     */
    public void setTargetOrdinal(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.target_ordinal</code>. The
     * zero-based target order within the owning activity event.
     */
    public UShort getTargetOrdinal() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>oagi.activity_event_target.target_type</code>. The
     * application-validated resource type, such as ACC, BIE, or CODE_LIST.
     */
    public void setTargetType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.target_type</code>. The
     * application-validated resource type, such as ACC, BIE, or CODE_LIST.
     */
    public String getTargetType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.activity_event_target.target_id</code>. The
     * optional internal numeric identifier of the affected resource.
     */
    public void setTargetId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.target_id</code>. The
     * optional internal numeric identifier of the affected resource.
     */
    public ULong getTargetId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.activity_event_target.target_guid</code>. The
     * optional stable public identifier of the affected resource.
     */
    public void setTargetGuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.target_guid</code>. The
     * optional stable public identifier of the affected resource.
     */
    public String getTargetGuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.activity_event_target.target_name</code>. The
     * display-name snapshot of the resource at event time.
     */
    public void setTargetName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.target_name</code>. The
     * display-name snapshot of the resource at event time.
     */
    public String getTargetName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.activity_event_target.target_role</code>. The
     * application-validated relationship of the resource to the event: PRIMARY,
     * AFFECTED, or CONTEXT.
     */
    public void setTargetRole(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.target_role</code>. The
     * application-validated relationship of the resource to the event: PRIMARY,
     * AFFECTED, or CONTEXT.
     */
    public String getTargetRole() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.activity_event_target.occurred_at</code>. The
     * denormalized UTC event timestamp used by resource-history indexes.
     */
    public void setOccurredAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.activity_event_target.occurred_at</code>. The
     * denormalized UTC event timestamp used by resource-history indexes.
     */
    public LocalDateTime getOccurredAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, UShort> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityEventTargetRecord
     */
    public ActivityEventTargetRecord() {
        super(ActivityEventTarget.ACTIVITY_EVENT_TARGET);
    }

    /**
     * Create a detached, initialised ActivityEventTargetRecord
     */
    public ActivityEventTargetRecord(ULong activityEventId, UShort targetOrdinal, String targetType, ULong targetId, String targetGuid, String targetName, String targetRole, LocalDateTime occurredAt) {
        super(ActivityEventTarget.ACTIVITY_EVENT_TARGET);

        setActivityEventId(activityEventId);
        setTargetOrdinal(targetOrdinal);
        setTargetType(targetType);
        setTargetId(targetId);
        setTargetGuid(targetGuid);
        setTargetName(targetName);
        setTargetRole(targetRole);
        setOccurredAt(occurredAt);
        resetTouchedOnNotNull();
    }
}
