/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.jooq.types.UShort;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.ActivityEvent;


/**
 * Append-only ledger of normalized user, service, and AI activity events.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityEventRecord extends UpdatableRecordImpl<ActivityEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.activity_event.activity_event_id</code>. The
     * primary key of the append-only activity event record.
     */
    public void setActivityEventId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.activity_event.activity_event_id</code>. The
     * primary key of the append-only activity event record.
     */
    public ULong getActivityEventId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.activity_event.event_guid</code>. The public UUID
     * and idempotency key of the activity event.
     */
    public void setEventGuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.activity_event.event_guid</code>. The public UUID
     * and idempotency key of the activity event.
     */
    public String getEventGuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.activity_event.actor_app_user_id</code>. The
     * application user identifier of the actor at event time; no foreign key is
     * used so historical events survive user deletion.
     */
    public void setActorAppUserId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.activity_event.actor_app_user_id</code>. The
     * application user identifier of the actor at event time; no foreign key is
     * used so historical events survive user deletion.
     */
    public ULong getActorAppUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.activity_event.actor_login_id</code>. The login
     * identifier snapshot of the actor at event time.
     */
    public void setActorLoginId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.activity_event.actor_login_id</code>. The login
     * identifier snapshot of the actor at event time.
     */
    public String getActorLoginId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.activity_event.event_scope</code>. The
     * application-validated activity scope such as JOURNEY, AUDIT, ACCESS, AI,
     * or TECHNICAL.
     */
    public void setEventScope(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.activity_event.event_scope</code>. The
     * application-validated activity scope such as JOURNEY, AUDIT, ACCESS, AI,
     * or TECHNICAL.
     */
    public String getEventScope() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.activity_event.event_name</code>. The stable
     * dot-notation event name defined by the activity event catalog.
     */
    public void setEventName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.activity_event.event_name</code>. The stable
     * dot-notation event name defined by the activity event catalog.
     */
    public String getEventName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.activity_event.source</code>. The
     * application-validated producer of the event, such as UI, SCORE_HTTP_API,
     * CONNECT_CENTER_MCP, or AI_ASSISTANT.
     */
    public void setSource(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.activity_event.source</code>. The
     * application-validated producer of the event, such as UI, SCORE_HTTP_API,
     * CONNECT_CENTER_MCP, or AI_ASSISTANT.
     */
    public String getSource() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.activity_event.outcome</code>. The
     * application-validated event outcome such as OBSERVED, STARTED, SUCCEEDED,
     * FAILED, or CANCELED.
     */
    public void setOutcome(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.activity_event.outcome</code>. The
     * application-validated event outcome such as OBSERVED, STARTED, SUCCEEDED,
     * FAILED, or CANCELED.
     */
    public String getOutcome() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oagi.activity_event.occurred_timestamp</code>. The UTC
     * timestamp when the represented activity occurred.
     */
    public void setOccurredTimestamp(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.activity_event.occurred_timestamp</code>. The UTC
     * timestamp when the represented activity occurred.
     */
    public LocalDateTime getOccurredTimestamp() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>oagi.activity_event.recorded_timestamp</code>. The UTC
     * timestamp when the server persisted the activity event.
     */
    public void setRecordedTimestamp(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.activity_event.recorded_timestamp</code>. The UTC
     * timestamp when the server persisted the activity event.
     */
    public LocalDateTime getRecordedTimestamp() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>oagi.activity_event.client_sequence</code>. The
     * monotonically increasing sequence assigned within a browser client
     * session.
     */
    public void setClientSequence(ULong value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.activity_event.client_sequence</code>. The
     * monotonically increasing sequence assigned within a browser client
     * session.
     */
    public ULong getClientSequence() {
        return (ULong) get(10);
    }

    /**
     * Setter for <code>oagi.activity_event.client_session_guid</code>. The
     * browser tab session UUID used to reconstruct recent user journey order.
     */
    public void setClientSessionGuid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>oagi.activity_event.client_session_guid</code>. The
     * browser tab session UUID used to reconstruct recent user journey order.
     */
    public String getClientSessionGuid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>oagi.activity_event.correlation_id</code>. The
     * identifier correlating UI intent, service calls, and resulting audit
     * events.
     */
    public void setCorrelationId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>oagi.activity_event.correlation_id</code>. The
     * identifier correlating UI intent, service calls, and resulting audit
     * events.
     */
    public String getCorrelationId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>oagi.activity_event.request_id</code>. The application
     * or AI request identifier associated with the event.
     */
    public void setRequestId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>oagi.activity_event.request_id</code>. The application
     * or AI request identifier associated with the event.
     */
    public String getRequestId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>oagi.activity_event.trace_id</code>. The optional
     * distributed trace identifier retained only for correlation.
     */
    public void setTraceId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>oagi.activity_event.trace_id</code>. The optional
     * distributed trace identifier retained only for correlation.
     */
    public String getTraceId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>oagi.activity_event.conversation_guid</code>. The AI
     * conversation UUID associated with the event when applicable.
     */
    public void setConversationGuid(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>oagi.activity_event.conversation_guid</code>. The AI
     * conversation UUID associated with the event when applicable.
     */
    public String getConversationGuid() {
        return (String) get(15);
    }

    /**
     * Setter for <code>oagi.activity_event.route_key</code>. The stable
     * application route key associated with the user activity.
     */
    public void setRouteKey(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>oagi.activity_event.route_key</code>. The stable
     * application route key associated with the user activity.
     */
    public String getRouteKey() {
        return (String) get(16);
    }

    /**
     * Setter for <code>oagi.activity_event.canonical_path</code>. The validated
     * root-relative application path used for safe navigation.
     */
    public void setCanonicalPath(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>oagi.activity_event.canonical_path</code>. The validated
     * root-relative application path used for safe navigation.
     */
    public String getCanonicalPath() {
        return (String) get(17);
    }

    /**
     * Setter for <code>oagi.activity_event.summary</code>. The bounded
     * human-readable summary of the activity event.
     */
    public void setSummary(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>oagi.activity_event.summary</code>. The bounded
     * human-readable summary of the activity event.
     */
    public String getSummary() {
        return (String) get(18);
    }

    /**
     * Setter for <code>oagi.activity_event.properties_json</code>. The bounded
     * allow-listed JSON properties specific to the event name.
     */
    public void setPropertiesJson(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>oagi.activity_event.properties_json</code>. The bounded
     * allow-listed JSON properties specific to the event name.
     */
    public String getPropertiesJson() {
        return (String) get(19);
    }

    /**
     * Setter for <code>oagi.activity_event.legacy_log_id</code>. The optional
     * legacy LOG identifier linked during live recording or backfill; no
     * foreign key is used.
     */
    public void setLegacyLogId(ULong value) {
        set(20, value);
    }

    /**
     * Getter for <code>oagi.activity_event.legacy_log_id</code>. The optional
     * legacy LOG identifier linked during live recording or backfill; no
     * foreign key is used.
     */
    public ULong getLegacyLogId() {
        return (ULong) get(20);
    }

    /**
     * Setter for <code>oagi.activity_event.schema_version</code>. The schema
     * version of the event payload and properties contract.
     */
    public void setSchemaVersion(UShort value) {
        set(21, value);
    }

    /**
     * Getter for <code>oagi.activity_event.schema_version</code>. The schema
     * version of the event payload and properties contract.
     */
    public UShort getSchemaVersion() {
        return (UShort) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityEventRecord
     */
    public ActivityEventRecord() {
        super(ActivityEvent.ACTIVITY_EVENT);
    }

    /**
     * Create a detached, initialised ActivityEventRecord
     */
    public ActivityEventRecord(ULong activityEventId, String eventGuid, ULong actorAppUserId, String actorLoginId, String eventScope, String eventName, String source, String outcome, LocalDateTime occurredTimestamp, LocalDateTime recordedTimestamp, ULong clientSequence, String clientSessionGuid, String correlationId, String requestId, String traceId, String conversationGuid, String routeKey, String canonicalPath, String summary, String propertiesJson, ULong legacyLogId, UShort schemaVersion) {
        super(ActivityEvent.ACTIVITY_EVENT);

        setActivityEventId(activityEventId);
        setEventGuid(eventGuid);
        setActorAppUserId(actorAppUserId);
        setActorLoginId(actorLoginId);
        setEventScope(eventScope);
        setEventName(eventName);
        setSource(source);
        setOutcome(outcome);
        setOccurredTimestamp(occurredTimestamp);
        setRecordedTimestamp(recordedTimestamp);
        setClientSequence(clientSequence);
        setClientSessionGuid(clientSessionGuid);
        setCorrelationId(correlationId);
        setRequestId(requestId);
        setTraceId(traceId);
        setConversationGuid(conversationGuid);
        setRouteKey(routeKey);
        setCanonicalPath(canonicalPath);
        setSummary(summary);
        setPropertiesJson(propertiesJson);
        setLegacyLogId(legacyLogId);
        setSchemaVersion(schemaVersion);
        resetTouchedOnNotNull();
    }
}
