/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiCatalogAudit;


/**
 * Audit history of AI provider and model catalog changes
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiCatalogAuditRecord extends UpdatableRecordImpl<AiCatalogAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_catalog_audit.ai_catalog_audit_id</code>.
     * Identifier of the AI catalog audit entry
     */
    public void setAiCatalogAuditId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.ai_catalog_audit_id</code>.
     * Identifier of the AI catalog audit entry
     */
    public ULong getAiCatalogAuditId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.entity_type</code>. Catalog entity
     * type such as PROVIDER or MODEL
     */
    public void setEntityType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.entity_type</code>. Catalog entity
     * type such as PROVIDER or MODEL
     */
    public String getEntityType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.entity_id</code>. Identifier of
     * the changed catalog entity
     */
    public void setEntityId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.entity_id</code>. Identifier of
     * the changed catalog entity
     */
    public ULong getEntityId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.actor_app_user_id</code>.
     * Identifier of the administrator who changed the catalog
     */
    public void setActorAppUserId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.actor_app_user_id</code>.
     * Identifier of the administrator who changed the catalog
     */
    public ULong getActorAppUserId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.action</code>. Catalog change
     * action such as CREATE, UPDATE, DISABLE, or ROTATE_KEY
     */
    public void setAction(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.action</code>. Catalog change
     * action such as CREATE, UPDATE, DISABLE, or ROTATE_KEY
     */
    public String getAction() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.before_json</code>. Non-secret
     * catalog snapshot before the change
     */
    public void setBeforeJson(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.before_json</code>. Non-secret
     * catalog snapshot before the change
     */
    public String getBeforeJson() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.after_json</code>. Non-secret
     * catalog snapshot after the change
     */
    public void setAfterJson(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.after_json</code>. Non-secret
     * catalog snapshot after the change
     */
    public String getAfterJson() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.reason</code>. Reason or
     * administrator comment for the catalog change
     */
    public void setReason(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.reason</code>. Reason or
     * administrator comment for the catalog change
     */
    public String getReason() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oagi.ai_catalog_audit.created_at</code>. Date and time
     * when the catalog was changed
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.ai_catalog_audit.created_at</code>. Date and time
     * when the catalog was changed
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiCatalogAuditRecord
     */
    public AiCatalogAuditRecord() {
        super(AiCatalogAudit.AI_CATALOG_AUDIT);
    }

    /**
     * Create a detached, initialised AiCatalogAuditRecord
     */
    public AiCatalogAuditRecord(ULong aiCatalogAuditId, String entityType, ULong entityId, ULong actorAppUserId, String action, String beforeJson, String afterJson, String reason, LocalDateTime createdAt) {
        super(AiCatalogAudit.AI_CATALOG_AUDIT);

        setAiCatalogAuditId(aiCatalogAuditId);
        setEntityType(entityType);
        setEntityId(entityId);
        setActorAppUserId(actorAppUserId);
        setAction(action);
        setBeforeJson(beforeJson);
        setAfterJson(afterJson);
        setReason(reason);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
