/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatArtifactObject;


/**
 * Binary objects used only when score.ai.tools.artifacts.storage.provider is
 * db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatArtifactObjectRecord extends UpdatableRecordImpl<AiChatArtifactObjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_chat_artifact_object.storage_location</code>.
     * Opaque database-storage object key.
     */
    public void setStorageLocation(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact_object.storage_location</code>.
     * Opaque database-storage object key.
     */
    public String getStorageLocation() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact_object.content</code>. Artifact
     * bytes for the database storage provider.
     */
    public void setContent(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact_object.content</code>. Artifact
     * bytes for the database storage provider.
     */
    public byte[] getContent() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact_object.created_at</code>. Object
     * creation timestamp.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact_object.created_at</code>. Object
     * creation timestamp.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiChatArtifactObjectRecord
     */
    public AiChatArtifactObjectRecord() {
        super(AiChatArtifactObject.AI_CHAT_ARTIFACT_OBJECT);
    }

    /**
     * Create a detached, initialised AiChatArtifactObjectRecord
     */
    public AiChatArtifactObjectRecord(String storageLocation, byte[] content, LocalDateTime createdAt) {
        super(AiChatArtifactObject.AI_CHAT_ARTIFACT_OBJECT);

        setStorageLocation(storageLocation);
        setContent(content);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
