/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatStep;


/**
 * Complete connectCenter assistant trajectory in ATIF-reconstructable steps.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatStepRecord extends UpdatableRecordImpl<AiChatStepRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_chat_step.ai_chat_step_id</code>. The primary
     * key of the AI chat trajectory step record.
     */
    public void setAiChatStepId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.ai_chat_step_id</code>. The primary
     * key of the AI chat trajectory step record.
     */
    public ULong getAiChatStepId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.ai_chat_conversation_id</code>.
     * Foreign key to the AI_CHAT_CONVERSATION table identifying the owning
     * conversation.
     */
    public void setAiChatConversationId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.ai_chat_conversation_id</code>.
     * Foreign key to the AI_CHAT_CONVERSATION table identifying the owning
     * conversation.
     */
    public ULong getAiChatConversationId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.step_sequence</code>. The zero-based
     * sequence of the step within the complete conversation trajectory.
     */
    public void setStepSequence(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.step_sequence</code>. The zero-based
     * sequence of the step within the complete conversation trajectory.
     */
    public Long getStepSequence() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.request_id</code>. The request
     * identifier used to correlate steps produced by the same chat request.
     */
    public void setRequestId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.request_id</code>. The request
     * identifier used to correlate steps produced by the same chat request.
     */
    public String getRequestId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.source</code>. Expected ATIF sources
     * are system, user, and agent; other values are handled by the application.
     */
    public void setSource(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.source</code>. Expected ATIF sources
     * are system, user, and agent; other values are handled by the application.
     */
    public String getSource() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.message_kind</code>. The
     * application-specific kind of trajectory event represented by the step.
     */
    public void setMessageKind(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.message_kind</code>. The
     * application-specific kind of trajectory event represented by the step.
     */
    public String getMessageKind() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.visibility</code>. Expected
     * presentation scopes are visible and debug; other values are handled by
     * the application.
     */
    public void setVisibility(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.visibility</code>. Expected
     * presentation scopes are visible and debug; other values are handled by
     * the application.
     */
    public String getVisibility() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.message</code>. The textual message or
     * event content recorded for the step.
     */
    public void setMessage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.message</code>. The textual message or
     * event content recorded for the step.
     */
    public String getMessage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.reasoning_content</code>. Optional
     * model reasoning content associated with the step.
     */
    public void setReasoningContent(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.reasoning_content</code>. Optional
     * model reasoning content associated with the step.
     */
    public String getReasoningContent() {
        return (String) get(8);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.model_name</code>. The model used for
     * the inference represented by the step.
     */
    public void setModelName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.model_name</code>. The model used for
     * the inference represented by the step.
     */
    public String getModelName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.reasoning_effort</code>. The
     * reasoning-effort setting used for the model inference.
     */
    public void setReasoningEffort(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.reasoning_effort</code>. The
     * reasoning-effort setting used for the model inference.
     */
    public String getReasoningEffort() {
        return (String) get(10);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.tool_calls_json</code>. JSON array
     * containing tool calls requested by the model.
     */
    public void setToolCallsJson(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.tool_calls_json</code>. JSON array
     * containing tool calls requested by the model.
     */
    public String getToolCallsJson() {
        return (String) get(11);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.observation_json</code>. JSON object
     * containing tool execution results observed by the agent.
     */
    public void setObservationJson(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.observation_json</code>. JSON object
     * containing tool execution results observed by the agent.
     */
    public String getObservationJson() {
        return (String) get(12);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.metrics_json</code>. JSON object
     * containing token usage and other execution metrics.
     */
    public void setMetricsJson(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.metrics_json</code>. JSON object
     * containing token usage and other execution metrics.
     */
    public String getMetricsJson() {
        return (String) get(13);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.extra_json</code>. JSON object
     * containing additional ATIF or application-specific step metadata.
     */
    public void setExtraJson(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.extra_json</code>. JSON object
     * containing additional ATIF or application-specific step metadata.
     */
    public String getExtraJson() {
        return (String) get(14);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.llm_call_count</code>. The number of
     * language-model calls represented by the step.
     */
    public void setLlmCallCount(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.llm_call_count</code>. The number of
     * language-model calls represented by the step.
     */
    public Integer getLlmCallCount() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.is_copied_context</code>. Indicates
     * whether the step was copied into the model context (0 = False, 1 = True).
     */
    public void setIsCopiedContext(Byte value) {
        set(16, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.is_copied_context</code>. Indicates
     * whether the step was copied into the model context (0 = False, 1 = True).
     */
    public Byte getIsCopiedContext() {
        return (Byte) get(16);
    }

    /**
     * Setter for <code>oagi.ai_chat_step.creation_timestamp</code>. The
     * timestamp when the trajectory step was created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_step.creation_timestamp</code>. The
     * timestamp when the trajectory step was created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiChatStepRecord
     */
    public AiChatStepRecord() {
        super(AiChatStep.AI_CHAT_STEP);
    }

    /**
     * Create a detached, initialised AiChatStepRecord
     */
    public AiChatStepRecord(ULong aiChatStepId, ULong aiChatConversationId, Long stepSequence, String requestId, String source, String messageKind, String visibility, String message, String reasoningContent, String modelName, String reasoningEffort, String toolCallsJson, String observationJson, String metricsJson, String extraJson, Integer llmCallCount, Byte isCopiedContext, LocalDateTime creationTimestamp) {
        super(AiChatStep.AI_CHAT_STEP);

        setAiChatStepId(aiChatStepId);
        setAiChatConversationId(aiChatConversationId);
        setStepSequence(stepSequence);
        setRequestId(requestId);
        setSource(source);
        setMessageKind(messageKind);
        setVisibility(visibility);
        setMessage(message);
        setReasoningContent(reasoningContent);
        setModelName(modelName);
        setReasoningEffort(reasoningEffort);
        setToolCallsJson(toolCallsJson);
        setObservationJson(observationJson);
        setMetricsJson(metricsJson);
        setExtraJson(extraJson);
        setLlmCallCount(llmCallCount);
        setIsCopiedContext(isCopiedContext);
        setCreationTimestamp(creationTimestamp);
        resetTouchedOnNotNull();
    }
}
