/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatArtifact;


/**
 * Generated Assistant artifact metadata and provider location history.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatArtifactRecord extends UpdatableRecordImpl<AiChatArtifactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_chat_artifact.ai_chat_artifact_id</code>. The
     * primary key of the generated AI artifact.
     */
    public void setAiChatArtifactId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.ai_chat_artifact_id</code>. The
     * primary key of the generated AI artifact.
     */
    public ULong getAiChatArtifactId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.guid</code>. Public artifact
     * identifier.
     */
    public void setGuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.guid</code>. Public artifact
     * identifier.
     */
    public String getGuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.ai_chat_conversation_id</code>.
     * Owning AI chat conversation.
     */
    public void setAiChatConversationId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.ai_chat_conversation_id</code>.
     * Owning AI chat conversation.
     */
    public ULong getAiChatConversationId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.request_id</code>. Request that
     * created the artifact.
     */
    public void setRequestId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.request_id</code>. Request that
     * created the artifact.
     */
    public String getRequestId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.format</code>. Renderer format
     * identifier.
     */
    public void setFormat(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.format</code>. Renderer format
     * identifier.
     */
    public String getFormat() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.filename</code>. Safe download
     * filename.
     */
    public void setFilename(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.filename</code>. Safe download
     * filename.
     */
    public String getFilename() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.media_type</code>. Artifact media
     * type.
     */
    public void setMediaType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.media_type</code>. Artifact media
     * type.
     */
    public String getMediaType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.byte_size</code>. Stored content
     * size in bytes.
     */
    public void setByteSize(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.byte_size</code>. Stored content
     * size in bytes.
     */
    public ULong getByteSize() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.sha256</code>. SHA-256 digest of
     * stored content.
     */
    public void setSha256(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.sha256</code>. SHA-256 digest of
     * stored content.
     */
    public String getSha256() {
        return (String) get(8);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.storage_provider</code>.
     * Configured artifact storage provider identifier.
     */
    public void setStorageProvider(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.storage_provider</code>.
     * Configured artifact storage provider identifier.
     */
    public String getStorageProvider() {
        return (String) get(9);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.storage_location</code>.
     * Provider-owned opaque object location.
     */
    public void setStorageLocation(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.storage_location</code>.
     * Provider-owned opaque object location.
     */
    public String getStorageLocation() {
        return (String) get(10);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.created_at</code>. Artifact
     * creation timestamp.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.created_at</code>. Artifact
     * creation timestamp.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>oagi.ai_chat_artifact.expires_at</code>. Artifact
     * retention deadline.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_artifact.expires_at</code>. Artifact
     * retention deadline.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiChatArtifactRecord
     */
    public AiChatArtifactRecord() {
        super(AiChatArtifact.AI_CHAT_ARTIFACT);
    }

    /**
     * Create a detached, initialised AiChatArtifactRecord
     */
    public AiChatArtifactRecord(ULong aiChatArtifactId, String guid, ULong aiChatConversationId, String requestId, String format, String filename, String mediaType, ULong byteSize, String sha256, String storageProvider, String storageLocation, LocalDateTime createdAt, LocalDateTime expiresAt) {
        super(AiChatArtifact.AI_CHAT_ARTIFACT);

        setAiChatArtifactId(aiChatArtifactId);
        setGuid(guid);
        setAiChatConversationId(aiChatConversationId);
        setRequestId(requestId);
        setFormat(format);
        setFilename(filename);
        setMediaType(mediaType);
        setByteSize(byteSize);
        setSha256(sha256);
        setStorageProvider(storageProvider);
        setStorageLocation(storageLocation);
        setCreatedAt(createdAt);
        setExpiresAt(expiresAt);
        resetTouchedOnNotNull();
    }
}
