/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiChatConversation;


/**
 * User-owned AI chat conversation metadata.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiChatConversationRecord extends UpdatableRecordImpl<AiChatConversationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.ai_chat_conversation.ai_chat_conversation_id</code>. The
     * primary key of the AI chat conversation record.
     */
    public void setAiChatConversationId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.ai_chat_conversation.ai_chat_conversation_id</code>. The
     * primary key of the AI chat conversation record.
     */
    public ULong getAiChatConversationId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.guid</code>. The public unique
     * identifier of the AI chat conversation.
     */
    public void setGuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.guid</code>. The public unique
     * identifier of the AI chat conversation.
     */
    public String getGuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.app_user_id</code>. Foreign
     * key to the APP_USER table identifying the owner of the conversation.
     */
    public void setAppUserId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.app_user_id</code>. Foreign
     * key to the APP_USER table identifying the owner of the conversation.
     */
    public ULong getAppUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for
     * <code>oagi.ai_chat_conversation.parent_ai_chat_conversation_id</code>.
     * Self-reference to the root conversation that owns this child execution.
     */
    public void setParentAiChatConversationId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>oagi.ai_chat_conversation.parent_ai_chat_conversation_id</code>.
     * Self-reference to the root conversation that owns this child execution.
     */
    public ULong getParentAiChatConversationId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.conversation_kind</code>.
     * Expected conversation kinds are ROOT, SUBAGENT, and PARALLEL; other
     * values are handled by the application.
     */
    public void setConversationKind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.conversation_kind</code>.
     * Expected conversation kinds are ROOT, SUBAGENT, and PARALLEL; other
     * values are handled by the application.
     */
    public String getConversationKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.agent_id</code>. Registered
     * worker identifier for a child execution conversation.
     */
    public void setAgentId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.agent_id</code>. Registered
     * worker identifier for a child execution conversation.
     */
    public String getAgentId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.parent_request_id</code>. Root
     * request that created this child execution conversation.
     */
    public void setParentRequestId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.parent_request_id</code>. Root
     * request that created this child execution conversation.
     */
    public String getParentRequestId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.title</code>. The display
     * title of the conversation, derived from its first prompt.
     */
    public void setTitle(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.title</code>. The display
     * title of the conversation, derived from its first prompt.
     */
    public String getTitle() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.compacted</code>. Indicates
     * whether the conversation model context has been compacted (0 = False, 1 =
     * True).
     */
    public void setCompacted(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.compacted</code>. Indicates
     * whether the conversation model context has been compacted (0 = False, 1 =
     * True).
     */
    public Byte getCompacted() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.creation_timestamp</code>. The
     * timestamp when the conversation was created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.creation_timestamp</code>. The
     * timestamp when the conversation was created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>oagi.ai_chat_conversation.last_update_timestamp</code>.
     * The timestamp of the most recent activity in the conversation.
     */
    public void setLastUpdateTimestamp(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.ai_chat_conversation.last_update_timestamp</code>.
     * The timestamp of the most recent activity in the conversation.
     */
    public LocalDateTime getLastUpdateTimestamp() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiChatConversationRecord
     */
    public AiChatConversationRecord() {
        super(AiChatConversation.AI_CHAT_CONVERSATION);
    }

    /**
     * Create a detached, initialised AiChatConversationRecord
     */
    public AiChatConversationRecord(ULong aiChatConversationId, String guid, ULong appUserId, ULong parentAiChatConversationId, String conversationKind, String agentId, String parentRequestId, String title, Byte compacted, LocalDateTime creationTimestamp, LocalDateTime lastUpdateTimestamp) {
        super(AiChatConversation.AI_CHAT_CONVERSATION);

        setAiChatConversationId(aiChatConversationId);
        setGuid(guid);
        setAppUserId(appUserId);
        setParentAiChatConversationId(parentAiChatConversationId);
        setConversationKind(conversationKind);
        setAgentId(agentId);
        setParentRequestId(parentRequestId);
        setTitle(title);
        setCompacted(compacted);
        setCreationTimestamp(creationTimestamp);
        setLastUpdateTimestamp(lastUpdateTimestamp);
        resetTouchedOnNotNull();
    }
}
