/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiModelCatalogConfig;


/**
 * Singleton global AI model catalog configuration
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiModelCatalogConfigRecord extends UpdatableRecordImpl<AiModelCatalogConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.ai_model_catalog_config.ai_model_catalog_config_id</code>.
     * Singleton AI model catalog configuration identifier
     */
    public void setAiModelCatalogConfigId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.ai_model_catalog_config.ai_model_catalog_config_id</code>.
     * Singleton AI model catalog configuration identifier
     */
    public UByte getAiModelCatalogConfigId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>oagi.ai_model_catalog_config.default_ai_model_id</code>.
     * Identifier of the global default AI model
     */
    public void setDefaultAiModelId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_model_catalog_config.default_ai_model_id</code>.
     * Identifier of the global default AI model
     */
    public ULong getDefaultAiModelId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.ai_model_catalog_config.catalog_version</code>.
     * Optimistic locking and cache invalidation version
     */
    public void setCatalogVersion(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_model_catalog_config.catalog_version</code>.
     * Optimistic locking and cache invalidation version
     */
    public ULong getCatalogVersion() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.ai_model_catalog_config.last_updated_by</code>.
     * Identifier of the administrator who last updated the catalog
     * configuration
     */
    public void setLastUpdatedBy(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_model_catalog_config.last_updated_by</code>.
     * Identifier of the administrator who last updated the catalog
     * configuration
     */
    public ULong getLastUpdatedBy() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.ai_model_catalog_config.last_updated_at</code>.
     * Date and time when the catalog configuration was last updated
     */
    public void setLastUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_model_catalog_config.last_updated_at</code>.
     * Date and time when the catalog configuration was last updated
     */
    public LocalDateTime getLastUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiModelCatalogConfigRecord
     */
    public AiModelCatalogConfigRecord() {
        super(AiModelCatalogConfig.AI_MODEL_CATALOG_CONFIG);
    }

    /**
     * Create a detached, initialised AiModelCatalogConfigRecord
     */
    public AiModelCatalogConfigRecord(UByte aiModelCatalogConfigId, ULong defaultAiModelId, ULong catalogVersion, ULong lastUpdatedBy, LocalDateTime lastUpdatedAt) {
        super(AiModelCatalogConfig.AI_MODEL_CATALOG_CONFIG);

        setAiModelCatalogConfigId(aiModelCatalogConfigId);
        setDefaultAiModelId(defaultAiModelId);
        setCatalogVersion(catalogVersion);
        setLastUpdatedBy(lastUpdatedBy);
        setLastUpdatedAt(lastUpdatedAt);
        resetTouchedOnNotNull();
    }
}
