/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiProvider;


/**
 * AI provider catalog and encrypted API key reference
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiProviderRecord extends UpdatableRecordImpl<AiProviderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_provider.ai_provider_id</code>. Identifier of
     * the AI provider
     */
    public void setAiProviderId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.ai_provider_id</code>. Identifier of
     * the AI provider
     */
    public ULong getAiProviderId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_provider.provider_name</code>. Unique
     * application-facing name of the AI provider
     */
    public void setProviderName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.provider_name</code>. Unique
     * application-facing name of the AI provider
     */
    public String getProviderName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.ai_provider.provider_type</code>. Provider adapter
     * type such as anthropic or azure-openai
     */
    public void setProviderType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.provider_type</code>. Provider adapter
     * type such as anthropic or azure-openai
     */
    public String getProviderType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.ai_provider.base_url</code>. Base endpoint URL of
     * the AI provider
     */
    public void setBaseUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.base_url</code>. Base endpoint URL of
     * the AI provider
     */
    public String getBaseUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.ai_provider.messages_url</code>. Optional
     * provider-specific messages endpoint URL
     */
    public void setMessagesUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.messages_url</code>. Optional
     * provider-specific messages endpoint URL
     */
    public String getMessagesUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.ai_provider.anthropic_version</code>. Anthropic API
     * version sent to the provider
     */
    public void setAnthropicVersion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.anthropic_version</code>. Anthropic API
     * version sent to the provider
     */
    public String getAnthropicVersion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.ai_provider.api_version</code>. Provider API
     * version such as the Azure OpenAI API version
     */
    public void setApiVersion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.api_version</code>. Provider API
     * version such as the Azure OpenAI API version
     */
    public String getApiVersion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.ai_provider.api_key_secret_id</code>. Encrypted API
     * key referenced from app_secret
     */
    public void setApiKeySecretId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.api_key_secret_id</code>. Encrypted API
     * key referenced from app_secret
     */
    public ULong getApiKeySecretId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>oagi.ai_provider.enabled</code>. Indicates whether the
     * provider can serve model requests
     */
    public void setEnabled(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.enabled</code>. Indicates whether the
     * provider can serve model requests
     */
    public Byte getEnabled() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>oagi.ai_provider.catalog_version</code>. Optimistic
     * locking and cache invalidation version
     */
    public void setCatalogVersion(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.catalog_version</code>. Optimistic
     * locking and cache invalidation version
     */
    public ULong getCatalogVersion() {
        return (ULong) get(9);
    }

    /**
     * Setter for <code>oagi.ai_provider.created_by</code>. Identifier of the
     * administrator who created the provider
     */
    public void setCreatedBy(ULong value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.created_by</code>. Identifier of the
     * administrator who created the provider
     */
    public ULong getCreatedBy() {
        return (ULong) get(10);
    }

    /**
     * Setter for <code>oagi.ai_provider.last_updated_by</code>. Identifier of
     * the administrator who last updated the provider
     */
    public void setLastUpdatedBy(ULong value) {
        set(11, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.last_updated_by</code>. Identifier of
     * the administrator who last updated the provider
     */
    public ULong getLastUpdatedBy() {
        return (ULong) get(11);
    }

    /**
     * Setter for <code>oagi.ai_provider.created_at</code>. Date and time when
     * the provider was created
     */
    public void setCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.created_at</code>. Date and time when
     * the provider was created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>oagi.ai_provider.last_updated_at</code>. Date and time
     * when the provider was last updated
     */
    public void setLastUpdatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>oagi.ai_provider.last_updated_at</code>. Date and time
     * when the provider was last updated
     */
    public LocalDateTime getLastUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiProviderRecord
     */
    public AiProviderRecord() {
        super(AiProvider.AI_PROVIDER);
    }

    /**
     * Create a detached, initialised AiProviderRecord
     */
    public AiProviderRecord(ULong aiProviderId, String providerName, String providerType, String baseUrl, String messagesUrl, String anthropicVersion, String apiVersion, ULong apiKeySecretId, Byte enabled, ULong catalogVersion, ULong createdBy, ULong lastUpdatedBy, LocalDateTime createdAt, LocalDateTime lastUpdatedAt) {
        super(AiProvider.AI_PROVIDER);

        setAiProviderId(aiProviderId);
        setProviderName(providerName);
        setProviderType(providerType);
        setBaseUrl(baseUrl);
        setMessagesUrl(messagesUrl);
        setAnthropicVersion(anthropicVersion);
        setApiVersion(apiVersion);
        setApiKeySecretId(apiKeySecretId);
        setEnabled(enabled);
        setCatalogVersion(catalogVersion);
        setCreatedBy(createdBy);
        setLastUpdatedBy(lastUpdatedBy);
        setCreatedAt(createdAt);
        setLastUpdatedAt(lastUpdatedAt);
        resetTouchedOnNotNull();
    }
}
