/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiTokenUsagePeriod;


/**
 * Per-user token counter for a quota period
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiTokenUsagePeriodRecord extends UpdatableRecordImpl<AiTokenUsagePeriodRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_token_usage_period.app_user_id</code>.
     * Identifier of the user whose token usage is aggregated
     */
    public void setAppUserId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_token_usage_period.app_user_id</code>.
     * Identifier of the user whose token usage is aggregated
     */
    public ULong getAppUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_token_usage_period.period_start</code>.
     * Inclusive start of the quota period in UTC
     */
    public void setPeriodStart(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_token_usage_period.period_start</code>.
     * Inclusive start of the quota period in UTC
     */
    public LocalDateTime getPeriodStart() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>oagi.ai_token_usage_period.period_end</code>. Exclusive
     * end of the quota period in UTC
     */
    public void setPeriodEnd(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_token_usage_period.period_end</code>. Exclusive
     * end of the quota period in UTC
     */
    public LocalDateTime getPeriodEnd() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>oagi.ai_token_usage_period.consumed_tokens</code>.
     * Number of tokens consumed during the period
     */
    public void setConsumedTokens(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_token_usage_period.consumed_tokens</code>.
     * Number of tokens consumed during the period
     */
    public ULong getConsumedTokens() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.ai_token_usage_period.reserved_tokens</code>.
     * Number of tokens reserved by in-progress calls during the period
     */
    public void setReservedTokens(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_token_usage_period.reserved_tokens</code>.
     * Number of tokens reserved by in-progress calls during the period
     */
    public ULong getReservedTokens() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.ai_token_usage_period.updated_at</code>. Date and
     * time when the period counter was last updated
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_token_usage_period.updated_at</code>. Date and
     * time when the period counter was last updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, LocalDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiTokenUsagePeriodRecord
     */
    public AiTokenUsagePeriodRecord() {
        super(AiTokenUsagePeriod.AI_TOKEN_USAGE_PERIOD);
    }

    /**
     * Create a detached, initialised AiTokenUsagePeriodRecord
     */
    public AiTokenUsagePeriodRecord(ULong appUserId, LocalDateTime periodStart, LocalDateTime periodEnd, ULong consumedTokens, ULong reservedTokens, LocalDateTime updatedAt) {
        super(AiTokenUsagePeriod.AI_TOKEN_USAGE_PERIOD);

        setAppUserId(appUserId);
        setPeriodStart(periodStart);
        setPeriodEnd(periodEnd);
        setConsumedTokens(consumedTokens);
        setReservedTokens(reservedTokens);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
