/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiTokenQuotaAdjustment;


/**
 * History of manual user quota adjustments by administrators
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiTokenQuotaAdjustmentRecord extends UpdatableRecordImpl<AiTokenQuotaAdjustmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.ai_token_quota_adjustment.ai_token_quota_adjustment_id</code>.
     * Identifier of the token quota adjustment
     */
    public void setAiTokenQuotaAdjustmentId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.ai_token_quota_adjustment.ai_token_quota_adjustment_id</code>.
     * Identifier of the token quota adjustment
     */
    public ULong getAiTokenQuotaAdjustmentId() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>oagi.ai_token_quota_adjustment.target_app_user_id</code>.
     * Identifier of the user whose quota was adjusted
     */
    public void setTargetAppUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>oagi.ai_token_quota_adjustment.target_app_user_id</code>.
     * Identifier of the user whose quota was adjusted
     */
    public ULong getTargetAppUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.ai_token_quota_adjustment.actor_app_user_id</code>.
     * Identifier of the administrator who adjusted the quota
     */
    public void setActorAppUserId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_token_quota_adjustment.actor_app_user_id</code>.
     * Identifier of the administrator who adjusted the quota
     */
    public ULong getActorAppUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for
     * <code>oagi.ai_token_quota_adjustment.period_start_timestamp</code>. Start
     * of the adjusted quota period in UTC
     */
    public void setPeriodStartTimestamp(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>oagi.ai_token_quota_adjustment.period_start_timestamp</code>. Start
     * of the adjusted quota period in UTC
     */
    public LocalDateTime getPeriodStartTimestamp() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>oagi.ai_token_quota_adjustment.delta_tokens</code>.
     * Positive or negative token amount applied to consumed usage
     */
    public void setDeltaTokens(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_token_quota_adjustment.delta_tokens</code>.
     * Positive or negative token amount applied to consumed usage
     */
    public Long getDeltaTokens() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>oagi.ai_token_quota_adjustment.reason</code>. Reason for
     * the quota adjustment
     */
    public void setReason(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_token_quota_adjustment.reason</code>. Reason for
     * the quota adjustment
     */
    public String getReason() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>oagi.ai_token_quota_adjustment.creation_timestamp</code>. Date and
     * time when the quota was adjusted
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>oagi.ai_token_quota_adjustment.creation_timestamp</code>. Date and
     * time when the quota was adjusted
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiTokenQuotaAdjustmentRecord
     */
    public AiTokenQuotaAdjustmentRecord() {
        super(AiTokenQuotaAdjustment.AI_TOKEN_QUOTA_ADJUSTMENT);
    }

    /**
     * Create a detached, initialised AiTokenQuotaAdjustmentRecord
     */
    public AiTokenQuotaAdjustmentRecord(ULong aiTokenQuotaAdjustmentId, ULong targetAppUserId, ULong actorAppUserId, LocalDateTime periodStartTimestamp, Long deltaTokens, String reason, LocalDateTime creationTimestamp) {
        super(AiTokenQuotaAdjustment.AI_TOKEN_QUOTA_ADJUSTMENT);

        setAiTokenQuotaAdjustmentId(aiTokenQuotaAdjustmentId);
        setTargetAppUserId(targetAppUserId);
        setActorAppUserId(actorAppUserId);
        setPeriodStartTimestamp(periodStartTimestamp);
        setDeltaTokens(deltaTokens);
        setReason(reason);
        setCreationTimestamp(creationTimestamp);
        resetTouchedOnNotNull();
    }
}
