/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiTokenRequestUsage;


/**
 * Token counter for each root AI request
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiTokenRequestUsageRecord extends UpdatableRecordImpl<AiTokenRequestUsageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_token_request_usage.request_id</code>.
     * Identifier of the root AI request
     */
    public void setRequestId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_token_request_usage.request_id</code>.
     * Identifier of the root AI request
     */
    public String getRequestId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.ai_token_request_usage.app_user_id</code>.
     * Identifier of the user who submitted the AI request
     */
    public void setAppUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_token_request_usage.app_user_id</code>.
     * Identifier of the user who submitted the AI request
     */
    public ULong getAppUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.ai_token_request_usage.consumed_tokens</code>.
     * Number of tokens consumed by the request
     */
    public void setConsumedTokens(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_token_request_usage.consumed_tokens</code>.
     * Number of tokens consumed by the request
     */
    public ULong getConsumedTokens() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.ai_token_request_usage.reserved_tokens</code>.
     * Number of tokens reserved by in-progress calls for the request
     */
    public void setReservedTokens(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_token_request_usage.reserved_tokens</code>.
     * Number of tokens reserved by in-progress calls for the request
     */
    public ULong getReservedTokens() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.ai_token_request_usage.created_at</code>. Date and
     * time when the request usage counter was created
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_token_request_usage.created_at</code>. Date and
     * time when the request usage counter was created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>oagi.ai_token_request_usage.updated_at</code>. Date and
     * time when the request usage counter was last updated
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_token_request_usage.updated_at</code>. Date and
     * time when the request usage counter was last updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiTokenRequestUsageRecord
     */
    public AiTokenRequestUsageRecord() {
        super(AiTokenRequestUsage.AI_TOKEN_REQUEST_USAGE);
    }

    /**
     * Create a detached, initialised AiTokenRequestUsageRecord
     */
    public AiTokenRequestUsageRecord(String requestId, ULong appUserId, ULong consumedTokens, ULong reservedTokens, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(AiTokenRequestUsage.AI_TOKEN_REQUEST_USAGE);

        setRequestId(requestId);
        setAppUserId(appUserId);
        setConsumedTokens(consumedTokens);
        setReservedTokens(reservedTokens);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
