/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiUserPolicy;


/**
 * Per-user AI Assistant access and usage limit policy
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiUserPolicyRecord extends UpdatableRecordImpl<AiUserPolicyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_user_policy.app_user_id</code>. Identifier of
     * the user to whom the policy applies
     */
    public void setAppUserId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.app_user_id</code>. Identifier of
     * the user to whom the policy applies
     */
    public ULong getAppUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.ai_enabled</code>. Indicates whether
     * the user can use AI Assistant
     */
    public void setAiEnabled(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.ai_enabled</code>. Indicates whether
     * the user can use AI Assistant
     */
    public Byte getAiEnabled() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.model_access_mode</code>. Model
     * access mode: ALL or ALLOW_LIST
     */
    public void setModelAccessMode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.model_access_mode</code>. Model
     * access mode: ALL or ALLOW_LIST
     */
    public String getModelAccessMode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.default_ai_model_id</code>.
     * Identifier of the default AI model for the user
     */
    public void setDefaultAiModelId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.default_ai_model_id</code>.
     * Identifier of the default AI model for the user
     */
    public ULong getDefaultAiModelId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.multi_agent_enabled</code>.
     * Indicates whether the user can use multi-agent workflows
     */
    public void setMultiAgentEnabled(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.multi_agent_enabled</code>.
     * Indicates whether the user can use multi-agent workflows
     */
    public Byte getMultiAgentEnabled() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.max_agents_per_request</code>.
     * Maximum number of agents allowed per request
     */
    public void setMaxAgentsPerRequest(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.max_agents_per_request</code>.
     * Maximum number of agents allowed per request
     */
    public UByte getMaxAgentsPerRequest() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.max_active_requests</code>. Maximum
     * number of concurrent AI requests for the user
     */
    public void setMaxActiveRequests(UByte value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.max_active_requests</code>. Maximum
     * number of concurrent AI requests for the user
     */
    public UByte getMaxActiveRequests() {
        return (UByte) get(6);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.max_output_tokens_per_call</code>.
     * Maximum number of output tokens allowed per model call
     */
    public void setMaxOutputTokensPerCall(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.max_output_tokens_per_call</code>.
     * Maximum number of output tokens allowed per model call
     */
    public ULong getMaxOutputTokensPerCall() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.max_total_tokens_per_request</code>.
     * Maximum total tokens allowed for a root request
     */
    public void setMaxTotalTokensPerRequest(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.max_total_tokens_per_request</code>.
     * Maximum total tokens allowed for a root request
     */
    public ULong getMaxTotalTokensPerRequest() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.quota_period</code>. Cumulative
     * token quota period: DAILY or MONTHLY
     */
    public void setQuotaPeriod(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.quota_period</code>. Cumulative
     * token quota period: DAILY or MONTHLY
     */
    public String getQuotaPeriod() {
        return (String) get(9);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.quota_tokens</code>. Maximum
     * cumulative tokens allowed during the quota period
     */
    public void setQuotaTokens(ULong value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.quota_tokens</code>. Maximum
     * cumulative tokens allowed during the quota period
     */
    public ULong getQuotaTokens() {
        return (ULong) get(10);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.policy_version</code>. Policy
     * version used for optimistic locking
     */
    public void setPolicyVersion(ULong value) {
        set(11, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.policy_version</code>. Policy
     * version used for optimistic locking
     */
    public ULong getPolicyVersion() {
        return (ULong) get(11);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.created_by</code>. Identifier of the
     * administrator who created the policy
     */
    public void setCreatedBy(ULong value) {
        set(12, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.created_by</code>. Identifier of the
     * administrator who created the policy
     */
    public ULong getCreatedBy() {
        return (ULong) get(12);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.last_updated_by</code>. Identifier
     * of the administrator who last updated the policy
     */
    public void setLastUpdatedBy(ULong value) {
        set(13, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.last_updated_by</code>. Identifier
     * of the administrator who last updated the policy
     */
    public ULong getLastUpdatedBy() {
        return (ULong) get(13);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.created_at</code>. Date and time
     * when the policy was created
     */
    public void setCreatedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.created_at</code>. Date and time
     * when the policy was created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>oagi.ai_user_policy.last_updated_at</code>. Date and
     * time when the policy was last updated
     */
    public void setLastUpdatedAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>oagi.ai_user_policy.last_updated_at</code>. Date and
     * time when the policy was last updated
     */
    public LocalDateTime getLastUpdatedAt() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiUserPolicyRecord
     */
    public AiUserPolicyRecord() {
        super(AiUserPolicy.AI_USER_POLICY);
    }

    /**
     * Create a detached, initialised AiUserPolicyRecord
     */
    public AiUserPolicyRecord(ULong appUserId, Byte aiEnabled, String modelAccessMode, ULong defaultAiModelId, Byte multiAgentEnabled, UByte maxAgentsPerRequest, UByte maxActiveRequests, ULong maxOutputTokensPerCall, ULong maxTotalTokensPerRequest, String quotaPeriod, ULong quotaTokens, ULong policyVersion, ULong createdBy, ULong lastUpdatedBy, LocalDateTime createdAt, LocalDateTime lastUpdatedAt) {
        super(AiUserPolicy.AI_USER_POLICY);

        setAppUserId(appUserId);
        setAiEnabled(aiEnabled);
        setModelAccessMode(modelAccessMode);
        setDefaultAiModelId(defaultAiModelId);
        setMultiAgentEnabled(multiAgentEnabled);
        setMaxAgentsPerRequest(maxAgentsPerRequest);
        setMaxActiveRequests(maxActiveRequests);
        setMaxOutputTokensPerCall(maxOutputTokensPerCall);
        setMaxTotalTokensPerRequest(maxTotalTokensPerRequest);
        setQuotaPeriod(quotaPeriod);
        setQuotaTokens(quotaTokens);
        setPolicyVersion(policyVersion);
        setCreatedBy(createdBy);
        setLastUpdatedBy(lastUpdatedBy);
        setCreatedAt(createdAt);
        setLastUpdatedAt(lastUpdatedAt);
        resetTouchedOnNotNull();
    }
}
