/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.AiUserModelAccess;


/**
 * Per-user AI model allowlist
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiUserModelAccessRecord extends UpdatableRecordImpl<AiUserModelAccessRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ai_user_model_access.app_user_id</code>. Identifier
     * of the user to whom the policy applies
     */
    public void setAppUserId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ai_user_model_access.app_user_id</code>. Identifier
     * of the user to whom the policy applies
     */
    public ULong getAppUserId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ai_user_model_access.ai_model_id</code>. Identifier
     * of an AI model allowed for the user
     */
    public void setAiModelId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ai_user_model_access.ai_model_id</code>. Identifier
     * of an AI model allowed for the user
     */
    public ULong getAiModelId() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiUserModelAccessRecord
     */
    public AiUserModelAccessRecord() {
        super(AiUserModelAccess.AI_USER_MODEL_ACCESS);
    }

    /**
     * Create a detached, initialised AiUserModelAccessRecord
     */
    public AiUserModelAccessRecord(ULong appUserId, ULong aiModelId) {
        super(AiUserModelAccess.AI_USER_MODEL_ACCESS);

        setAppUserId(appUserId);
        setAiModelId(aiModelId);
        resetTouchedOnNotNull();
    }
}
