/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.BccpManifest;


/**
 * A BCCP_MANIFEST is a release-specific handle to a BCCP record, pinning it to
 * a RELEASE and carrying the revision chain to the corresponding BCCP_MANIFEST
 * in the previous and next releases. A BCCP specifies a property concept and
 * the data type associated with it, which can then be added as a property of an
 * ACC; the manifest also binds the BCCP to the BDT that specifies its data
 * format through BDT_MANIFEST_ID (DT_MANIFEST).
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BccpManifestRecord extends UpdatableRecordImpl<BccpManifestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.bccp_manifest.bccp_manifest_id</code>. An internal,
     * primary database key of a BCCP_MANIFEST record.
     */
    public void setBccpManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.bccp_manifest_id</code>. An internal,
     * primary database key of a BCCP_MANIFEST record.
     */
    public ULong getBccpManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.release_id</code>. Foreign key to the
     * RELEASE table.
     */
    public void setReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.release_id</code>. Foreign key to the
     * RELEASE table.
     */
    public ULong getReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.bccp_id</code>. Foreign key to the
     * BCCP table.
     */
    public void setBccpId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.bccp_id</code>. Foreign key to the
     * BCCP table.
     */
    public ULong getBccpId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.bdt_manifest_id</code>. Foreign key
     * to the DT_MANIFEST table for the BDT (business data type) that specifies
     * the data format of the BCCP. Only a DT whose type is BDT can be used.
     */
    public void setBdtManifestId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.bdt_manifest_id</code>. Foreign key
     * to the DT_MANIFEST table for the BDT (business data type) that specifies
     * the data format of the BCCP. Only a DT whose type is BDT can be used.
     */
    public ULong getBdtManifestId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.den</code>. The dictionary entry name
     * of the BCCP. It is derived by PROPERTY_TERM + ". " + REPRESENTATION_TERM.
     */
    public void setDen(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.den</code>. The dictionary entry name
     * of the BCCP. It is derived by PROPERTY_TERM + ". " + REPRESENTATION_TERM.
     */
    public String getDen() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.conflict</code>. This indicates that
     * there is a conflict between self and relationship.
     */
    public void setConflict(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.conflict</code>. This indicates that
     * there is a conflict between self and relationship.
     */
    public Byte getConflict() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.log_id</code>. A foreign key pointed
     * to a log for the current record.
     */
    public void setLogId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.log_id</code>. A foreign key pointed
     * to a log for the current record.
     */
    public ULong getLogId() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.replacement_bccp_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public void setReplacementBccpManifestId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.replacement_bccp_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public ULong getReplacementBccpManifestId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.prev_bccp_manifest_id</code>. A
     * self-reference to the corresponding BCCP_MANIFEST record in the previous
     * release (revision chain). NULL for the first revision.
     */
    public void setPrevBccpManifestId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.prev_bccp_manifest_id</code>. A
     * self-reference to the corresponding BCCP_MANIFEST record in the previous
     * release (revision chain). NULL for the first revision.
     */
    public ULong getPrevBccpManifestId() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>oagi.bccp_manifest.next_bccp_manifest_id</code>. A
     * self-reference to the corresponding BCCP_MANIFEST record in the next
     * release (revision chain). NULL for the latest revision.
     */
    public void setNextBccpManifestId(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.bccp_manifest.next_bccp_manifest_id</code>. A
     * self-reference to the corresponding BCCP_MANIFEST record in the next
     * release (revision chain). NULL for the latest revision.
     */
    public ULong getNextBccpManifestId() {
        return (ULong) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BccpManifestRecord
     */
    public BccpManifestRecord() {
        super(BccpManifest.BCCP_MANIFEST);
    }

    /**
     * Create a detached, initialised BccpManifestRecord
     */
    public BccpManifestRecord(ULong bccpManifestId, ULong releaseId, ULong bccpId, ULong bdtManifestId, String den, Byte conflict, ULong logId, ULong replacementBccpManifestId, ULong prevBccpManifestId, ULong nextBccpManifestId) {
        super(BccpManifest.BCCP_MANIFEST);

        setBccpManifestId(bccpManifestId);
        setReleaseId(releaseId);
        setBccpId(bccpId);
        setBdtManifestId(bdtManifestId);
        setDen(den);
        setConflict(conflict);
        setLogId(logId);
        setReplacementBccpManifestId(replacementBccpManifestId);
        setPrevBccpManifestId(prevBccpManifestId);
        setNextBccpManifestId(nextBccpManifestId);
        resetTouchedOnNotNull();
    }
}
