/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.CodeListValueManifest;


/**
 * A release-specific handle to a CODE_LIST_VALUE record, pinning a code list
 * value of a code list to a RELEASE (and to its owning CODE_LIST_MANIFEST) and
 * carrying the revision chain via the PREV/NEXT self-references across
 * releases.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeListValueManifestRecord extends UpdatableRecordImpl<CodeListValueManifestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.code_list_value_manifest_id</code>.
     * An internal, primary database key of a CODE_LIST_VALUE_MANIFEST record.
     */
    public void setCodeListValueManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.code_list_value_manifest_id</code>.
     * An internal, primary database key of a CODE_LIST_VALUE_MANIFEST record.
     */
    public ULong getCodeListValueManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.code_list_value_manifest.release_id</code>. Foreign
     * key to the RELEASE table.
     */
    public void setReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.code_list_value_manifest.release_id</code>. Foreign
     * key to the RELEASE table.
     */
    public ULong getReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.code_list_value_manifest.code_list_value_id</code>.
     * Foreign key to the CODE_LIST_VALUE table.
     */
    public void setCodeListValueId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.code_list_value_manifest.code_list_value_id</code>.
     * Foreign key to the CODE_LIST_VALUE table.
     */
    public ULong getCodeListValueId() {
        return (ULong) get(2);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.code_list_manifest_id</code>. Foreign
     * key to the CODE_LIST_MANIFEST table.
     */
    public void setCodeListManifestId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.code_list_manifest_id</code>. Foreign
     * key to the CODE_LIST_MANIFEST table.
     */
    public ULong getCodeListManifestId() {
        return (ULong) get(3);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.based_code_list_value_manifest_id</code>.
     * A self-reference to the CODE_LIST_VALUE_MANIFEST record that this record
     * is based on (its base/supertype from which it was derived).
     */
    public void setBasedCodeListValueManifestId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.based_code_list_value_manifest_id</code>.
     * A self-reference to the CODE_LIST_VALUE_MANIFEST record that this record
     * is based on (its base/supertype from which it was derived).
     */
    public ULong getBasedCodeListValueManifestId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.code_list_value_manifest.conflict</code>. This
     * indicates that there is a conflict between self and relationship.
     */
    public void setConflict(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.code_list_value_manifest.conflict</code>. This
     * indicates that there is a conflict between self and relationship.
     */
    public Byte getConflict() {
        return (Byte) get(5);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.replacement_code_list_value_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public void setReplacementCodeListValueManifestId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.replacement_code_list_value_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public ULong getReplacementCodeListValueManifestId() {
        return (ULong) get(6);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.prev_code_list_value_manifest_id</code>.
     * A self-reference to the corresponding CODE_LIST_VALUE_MANIFEST record in
     * the previous release (revision chain). NULL for the first revision.
     */
    public void setPrevCodeListValueManifestId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.prev_code_list_value_manifest_id</code>.
     * A self-reference to the corresponding CODE_LIST_VALUE_MANIFEST record in
     * the previous release (revision chain). NULL for the first revision.
     */
    public ULong getPrevCodeListValueManifestId() {
        return (ULong) get(7);
    }

    /**
     * Setter for
     * <code>oagi.code_list_value_manifest.next_code_list_value_manifest_id</code>.
     * A self-reference to the corresponding CODE_LIST_VALUE_MANIFEST record in
     * the next release (revision chain). NULL for the latest revision.
     */
    public void setNextCodeListValueManifestId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>oagi.code_list_value_manifest.next_code_list_value_manifest_id</code>.
     * A self-reference to the corresponding CODE_LIST_VALUE_MANIFEST record in
     * the next release (revision chain). NULL for the latest revision.
     */
    public ULong getNextCodeListValueManifestId() {
        return (ULong) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeListValueManifestRecord
     */
    public CodeListValueManifestRecord() {
        super(CodeListValueManifest.CODE_LIST_VALUE_MANIFEST);
    }

    /**
     * Create a detached, initialised CodeListValueManifestRecord
     */
    public CodeListValueManifestRecord(ULong codeListValueManifestId, ULong releaseId, ULong codeListValueId, ULong codeListManifestId, ULong basedCodeListValueManifestId, Byte conflict, ULong replacementCodeListValueManifestId, ULong prevCodeListValueManifestId, ULong nextCodeListValueManifestId) {
        super(CodeListValueManifest.CODE_LIST_VALUE_MANIFEST);

        setCodeListValueManifestId(codeListValueManifestId);
        setReleaseId(releaseId);
        setCodeListValueId(codeListValueId);
        setCodeListManifestId(codeListManifestId);
        setBasedCodeListValueManifestId(basedCodeListValueManifestId);
        setConflict(conflict);
        setReplacementCodeListValueManifestId(replacementCodeListValueManifestId);
        setPrevCodeListValueManifestId(prevCodeListValueManifestId);
        setNextCodeListValueManifestId(nextCodeListValueManifestId);
        resetTouchedOnNotNull();
    }
}
