/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Comment;


/**
 * This table stores user comments associated with a component, where the
 * associated component is identified by the REFERENCE column in the form of the
 * component type and its manifest ID (e.g., 'CODE_LIST-123'). Replies are
 * captured through the self-referencing PREV_COMMENT_ID chain, and a comment
 * with replies is hidden via IS_HIDDEN instead of being deleted so the reply
 * chain is preserved, while IS_DELETED marks a comment as soft-deleted and
 * excluded from queries rather than physically removing it.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CommentRecord extends UpdatableRecordImpl<CommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.comment.comment_id</code>. An internal, primary
     * database key of a COMMENT record.
     */
    public void setCommentId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.comment.comment_id</code>. An internal, primary
     * database key of a COMMENT record.
     */
    public ULong getCommentId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.comment.reference</code>. The reference to the
     * component the comment is associated with, in the form of the component
     * type and its manifest ID (e.g., 'CODE_LIST-123').
     */
    public void setReference(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.comment.reference</code>. The reference to the
     * component the comment is associated with, in the form of the component
     * type and its manifest ID (e.g., 'CODE_LIST-123').
     */
    public String getReference() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.comment.comment</code>. The text content of the
     * comment.
     */
    public void setComment(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.comment.comment</code>. The text content of the
     * comment.
     */
    public String getComment() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.comment.is_hidden</code>. A boolean flag indicating
     * whether the comment is hidden. It is set instead of deletion when the
     * comment has replies, so the reply chain is preserved.
     */
    public void setIsHidden(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.comment.is_hidden</code>. A boolean flag indicating
     * whether the comment is hidden. It is set instead of deletion when the
     * comment has replies, so the reply chain is preserved.
     */
    public Byte getIsHidden() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>oagi.comment.is_deleted</code>. A boolean flag
     * indicating whether the comment has been soft-deleted. Soft-deleted
     * comments are excluded from queries.
     */
    public void setIsDeleted(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.comment.is_deleted</code>. A boolean flag
     * indicating whether the comment has been soft-deleted. Soft-deleted
     * comments are excluded from queries.
     */
    public Byte getIsDeleted() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>oagi.comment.prev_comment_id</code>. A self-reference to
     * the previous COMMENT record in the chain.
     */
    public void setPrevCommentId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.comment.prev_comment_id</code>. A self-reference to
     * the previous COMMENT record in the chain.
     */
    public ULong getPrevCommentId() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>oagi.comment.created_by</code>. The user who creates the
     * record.
     */
    public void setCreatedBy(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.comment.created_by</code>. The user who creates the
     * record.
     */
    public ULong getCreatedBy() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>oagi.comment.creation_timestamp</code>. The timestamp
     * when the record is created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.comment.creation_timestamp</code>. The timestamp
     * when the record is created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>oagi.comment.last_update_timestamp</code>. The timestamp
     * when the record is last updated.
     */
    public void setLastUpdateTimestamp(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.comment.last_update_timestamp</code>. The timestamp
     * when the record is last updated.
     */
    public LocalDateTime getLastUpdateTimestamp() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentRecord
     */
    public CommentRecord() {
        super(Comment.COMMENT);
    }

    /**
     * Create a detached, initialised CommentRecord
     */
    public CommentRecord(ULong commentId, String reference, String comment, Byte isHidden, Byte isDeleted, ULong prevCommentId, ULong createdBy, LocalDateTime creationTimestamp, LocalDateTime lastUpdateTimestamp) {
        super(Comment.COMMENT);

        setCommentId(commentId);
        setReference(reference);
        setComment(comment);
        setIsHidden(isHidden);
        setIsDeleted(isDeleted);
        setPrevCommentId(prevCommentId);
        setCreatedBy(createdBy);
        setCreationTimestamp(creationTimestamp);
        setLastUpdateTimestamp(lastUpdateTimestamp);
        resetTouchedOnNotNull();
    }
}
