/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Log;


/**
 * The LOG table records the revision history of component records, storing one
 * entry per change with the component's serialized state SNAPSHOT, its
 * REVISION_NUM and REVISION_TRACKING_NUM, and the LOG_ACTION taken. Because it
 * logs many different component types, it references the target component by
 * its GUID (the REFERENCE column) rather than a foreign key, and the
 * PREV_LOG_ID and NEXT_LOG_ID columns chain the entries into a per-component
 * revision history.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LogRecord extends UpdatableRecordImpl<LogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.log.log_id</code>. An internal, primary database
     * key of a LOG record.
     */
    public void setLogId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.log.log_id</code>. An internal, primary database
     * key of a LOG record.
     */
    public ULong getLogId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.log.hash</code>. The unique hash to identify the
     * log.
     */
    public void setHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.log.hash</code>. The unique hash to identify the
     * log.
     */
    public String getHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.log.revision_num</code>. This is an incremental
     * integer. It tracks changes in each component. If a change is made to a
     * component after it has been published, the component receives a new
     * revision number. Revision number can be 1, 2, and so on.
     */
    public void setRevisionNum(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.log.revision_num</code>. This is an incremental
     * integer. It tracks changes in each component. If a change is made to a
     * component after it has been published, the component receives a new
     * revision number. Revision number can be 1, 2, and so on.
     */
    public UInteger getRevisionNum() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>oagi.log.revision_tracking_num</code>. This supports the
     * ability to undo changes during a revision (life cycle of a revision is
     * from the component's WIP state to PUBLISHED state). REVISION_TRACKING_NUM
     * can be 1, 2, and so on.
     */
    public void setRevisionTrackingNum(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.log.revision_tracking_num</code>. This supports the
     * ability to undo changes during a revision (life cycle of a revision is
     * from the component's WIP state to PUBLISHED state). REVISION_TRACKING_NUM
     * can be 1, 2, and so on.
     */
    public UInteger getRevisionTrackingNum() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>oagi.log.log_action</code>. This indicates the action
     * associated with the record.
     */
    public void setLogAction(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.log.log_action</code>. This indicates the action
     * associated with the record.
     */
    public String getLogAction() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.log.reference</code>. A reference to the record for
     * which this log is created. Because the LOG table stores logs for various
     * component types, it cannot use a foreign key; instead it stores the GUID
     * of the referenced component.
     */
    public void setReference(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.log.reference</code>. A reference to the record for
     * which this log is created. Because the LOG table stores logs for various
     * component types, it cannot use a foreign key; instead it stores the GUID
     * of the referenced component.
     */
    public String getReference() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.log.snapshot</code>.
     */
    public void setSnapshot(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.log.snapshot</code>.
     */
    public String getSnapshot() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.log.prev_log_id</code>. A self-reference to the
     * previous LOG record in the chain.
     */
    public void setPrevLogId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.log.prev_log_id</code>. A self-reference to the
     * previous LOG record in the chain.
     */
    public ULong getPrevLogId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>oagi.log.next_log_id</code>. A self-reference to the
     * next LOG record in the chain.
     */
    public void setNextLogId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.log.next_log_id</code>. A self-reference to the
     * next LOG record in the chain.
     */
    public ULong getNextLogId() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>oagi.log.created_by</code>. The user who creates the
     * record.
     */
    public void setCreatedBy(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.log.created_by</code>. The user who creates the
     * record.
     */
    public ULong getCreatedBy() {
        return (ULong) get(9);
    }

    /**
     * Setter for <code>oagi.log.creation_timestamp</code>. The timestamp when
     * the record is created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.log.creation_timestamp</code>. The timestamp when
     * the record is created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogRecord
     */
    public LogRecord() {
        super(Log.LOG);
    }

    /**
     * Create a detached, initialised LogRecord
     */
    public LogRecord(ULong logId, String hash, UInteger revisionNum, UInteger revisionTrackingNum, String logAction, String reference, String snapshot, ULong prevLogId, ULong nextLogId, ULong createdBy, LocalDateTime creationTimestamp) {
        super(Log.LOG);

        setLogId(logId);
        setHash(hash);
        setRevisionNum(revisionNum);
        setRevisionTrackingNum(revisionTrackingNum);
        setLogAction(logAction);
        setReference(reference);
        setSnapshot(snapshot);
        setPrevLogId(prevLogId);
        setNextLogId(nextLogId);
        setCreatedBy(createdBy);
        setCreationTimestamp(creationTimestamp);
        resetTouchedOnNotNull();
    }
}
