/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.Oauth2App;


/**
 * This table stores OAuth 2.0 / OpenID Connect provider registrations,
 * including client credentials, endpoint URIs, and login-button display
 * settings, used to authenticate end users.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Oauth2AppRecord extends UpdatableRecordImpl<Oauth2AppRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.oauth2_app.oauth2_app_id</code>. An internal,
     * primary database key of a OAUTH2_APP record.
     */
    public void setOauth2AppId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.oauth2_app_id</code>. An internal,
     * primary database key of a OAUTH2_APP record.
     */
    public ULong getOauth2AppId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.oauth2_app.provider_name</code>. The unique name
     * identifying this OAuth 2.0 provider; used as the client registration ID.
     */
    public void setProviderName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.provider_name</code>. The unique name
     * identifying this OAuth 2.0 provider; used as the client registration ID.
     */
    public String getProviderName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.oauth2_app.issuer_uri</code>. The OpenID Connect
     * issuer URI; when set, the provider's endpoints are discovered from its
     * metadata.
     */
    public void setIssuerUri(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.issuer_uri</code>. The OpenID Connect
     * issuer URI; when set, the provider's endpoints are discovered from its
     * metadata.
     */
    public String getIssuerUri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.oauth2_app.authorization_uri</code>. The
     * authorization endpoint URI of the OAuth 2.0 provider.
     */
    public void setAuthorizationUri(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.authorization_uri</code>. The
     * authorization endpoint URI of the OAuth 2.0 provider.
     */
    public String getAuthorizationUri() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.oauth2_app.token_uri</code>. The token endpoint URI
     * of the OAuth 2.0 provider.
     */
    public void setTokenUri(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.token_uri</code>. The token endpoint URI
     * of the OAuth 2.0 provider.
     */
    public String getTokenUri() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.oauth2_app.user_info_uri</code>. The UserInfo
     * endpoint URI of the OAuth 2.0 provider.
     */
    public void setUserInfoUri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.user_info_uri</code>. The UserInfo
     * endpoint URI of the OAuth 2.0 provider.
     */
    public String getUserInfoUri() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oagi.oauth2_app.jwk_set_uri</code>. The JSON Web Key
     * (JWK) Set URI of the OAuth 2.0 provider, used to validate tokens.
     */
    public void setJwkSetUri(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.jwk_set_uri</code>. The JSON Web Key
     * (JWK) Set URI of the OAuth 2.0 provider, used to validate tokens.
     */
    public String getJwkSetUri() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oagi.oauth2_app.redirect_uri</code>. The redirect URI to
     * which the OAuth 2.0 provider returns the end user after authorization.
     */
    public void setRedirectUri(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.redirect_uri</code>. The redirect URI to
     * which the OAuth 2.0 provider returns the end user after authorization.
     */
    public String getRedirectUri() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oagi.oauth2_app.end_session_endpoint</code>. The
     * end-session (logout) endpoint URI of the OAuth 2.0 provider.
     */
    public void setEndSessionEndpoint(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.end_session_endpoint</code>. The
     * end-session (logout) endpoint URI of the OAuth 2.0 provider.
     */
    public String getEndSessionEndpoint() {
        return (String) get(8);
    }

    /**
     * Setter for <code>oagi.oauth2_app.client_id</code>. The client identifier
     * issued to this application by the OAuth 2.0 provider.
     */
    public void setClientId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.client_id</code>. The client identifier
     * issued to this application by the OAuth 2.0 provider.
     */
    public String getClientId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>oagi.oauth2_app.client_secret</code>. The client secret
     * issued to this application by the OAuth 2.0 provider.
     */
    public void setClientSecret(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.client_secret</code>. The client secret
     * issued to this application by the OAuth 2.0 provider.
     */
    public String getClientSecret() {
        return (String) get(10);
    }

    /**
     * Setter for <code>oagi.oauth2_app.client_authentication_method</code>. The
     * client authentication method used with the provider (e.g.
     * client_secret_basic, client_secret_post).
     */
    public void setClientAuthenticationMethod(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.client_authentication_method</code>. The
     * client authentication method used with the provider (e.g.
     * client_secret_basic, client_secret_post).
     */
    public String getClientAuthenticationMethod() {
        return (String) get(11);
    }

    /**
     * Setter for <code>oagi.oauth2_app.authorization_grant_type</code>. The
     * OAuth 2.0 authorization grant type used with the provider (e.g.
     * authorization_code).
     */
    public void setAuthorizationGrantType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.authorization_grant_type</code>. The
     * OAuth 2.0 authorization grant type used with the provider (e.g.
     * authorization_code).
     */
    public String getAuthorizationGrantType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>oagi.oauth2_app.prompt</code>. The OpenID Connect
     * 'prompt' parameter sent to the provider's authorization endpoint.
     */
    public void setPrompt(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.prompt</code>. The OpenID Connect
     * 'prompt' parameter sent to the provider's authorization endpoint.
     */
    public String getPrompt() {
        return (String) get(13);
    }

    /**
     * Setter for <code>oagi.oauth2_app.display_provider_name</code>. The
     * provider name displayed on the login button in the user interface.
     */
    public void setDisplayProviderName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.display_provider_name</code>. The
     * provider name displayed on the login button in the user interface.
     */
    public String getDisplayProviderName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>oagi.oauth2_app.background_color</code>. The background
     * color of the provider's login button in the user interface.
     */
    public void setBackgroundColor(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.background_color</code>. The background
     * color of the provider's login button in the user interface.
     */
    public String getBackgroundColor() {
        return (String) get(15);
    }

    /**
     * Setter for <code>oagi.oauth2_app.font_color</code>. The font color of the
     * provider's login button in the user interface.
     */
    public void setFontColor(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.font_color</code>. The font color of the
     * provider's login button in the user interface.
     */
    public String getFontColor() {
        return (String) get(16);
    }

    /**
     * Setter for <code>oagi.oauth2_app.display_order</code>. The order in which
     * this provider is displayed among the login options.
     */
    public void setDisplayOrder(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.display_order</code>. The order in which
     * this provider is displayed among the login options.
     */
    public Integer getDisplayOrder() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>oagi.oauth2_app.is_disabled</code>. A flag indicating
     * whether this OAuth 2.0 provider is disabled (1 = disabled, 0 = enabled).
     */
    public void setIsDisabled(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>oagi.oauth2_app.is_disabled</code>. A flag indicating
     * whether this OAuth 2.0 provider is disabled (1 = disabled, 0 = enabled).
     */
    public Byte getIsDisabled() {
        return (Byte) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Oauth2AppRecord
     */
    public Oauth2AppRecord() {
        super(Oauth2App.OAUTH2_APP);
    }

    /**
     * Create a detached, initialised Oauth2AppRecord
     */
    public Oauth2AppRecord(ULong oauth2AppId, String providerName, String issuerUri, String authorizationUri, String tokenUri, String userInfoUri, String jwkSetUri, String redirectUri, String endSessionEndpoint, String clientId, String clientSecret, String clientAuthenticationMethod, String authorizationGrantType, String prompt, String displayProviderName, String backgroundColor, String fontColor, Integer displayOrder, Byte isDisabled) {
        super(Oauth2App.OAUTH2_APP);

        setOauth2AppId(oauth2AppId);
        setProviderName(providerName);
        setIssuerUri(issuerUri);
        setAuthorizationUri(authorizationUri);
        setTokenUri(tokenUri);
        setUserInfoUri(userInfoUri);
        setJwkSetUri(jwkSetUri);
        setRedirectUri(redirectUri);
        setEndSessionEndpoint(endSessionEndpoint);
        setClientId(clientId);
        setClientSecret(clientSecret);
        setClientAuthenticationMethod(clientAuthenticationMethod);
        setAuthorizationGrantType(authorizationGrantType);
        setPrompt(prompt);
        setDisplayProviderName(displayProviderName);
        setBackgroundColor(backgroundColor);
        setFontColor(fontColor);
        setDisplayOrder(displayOrder);
        setIsDisabled(isDisabled);
        resetTouchedOnNotNull();
    }
}
