/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.SeqKey;


/**
 * This table stores the ordering of the associations (ASCC and BCC) that belong
 * to an ACC. Each record points, through FROM_ACC_MANIFEST_ID, to the owning
 * ACC via ACC_MANIFEST and, through exactly one of ASCC_MANIFEST_ID or
 * BCC_MANIFEST_ID, to the ordered association; the PREV_SEQ_KEY_ID and
 * NEXT_SEQ_KEY_ID columns form a doubly-linked chain that defines the sequence
 * of these associations within the ACC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeqKeyRecord extends UpdatableRecordImpl<SeqKeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.seq_key.seq_key_id</code>. An internal, primary
     * database key of a SEQ_KEY record.
     */
    public void setSeqKeyId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.seq_key.seq_key_id</code>. An internal, primary
     * database key of a SEQ_KEY record.
     */
    public ULong getSeqKeyId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.seq_key.from_acc_manifest_id</code>. Foreign key to
     * the ACC_MANIFEST table pointing to the ACC that owns the association
     * (ASCC/BCC) ordered by this sequence key.
     */
    public void setFromAccManifestId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.seq_key.from_acc_manifest_id</code>. Foreign key to
     * the ACC_MANIFEST table pointing to the ACC that owns the association
     * (ASCC/BCC) ordered by this sequence key.
     */
    public ULong getFromAccManifestId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.seq_key.ascc_manifest_id</code>. Foreign key to the
     * ASCC_MANIFEST table for the ASCC association ordered by this record.
     * Exactly one of ASCC_MANIFEST_ID / BCC_MANIFEST_ID is non-null.
     */
    public void setAsccManifestId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.seq_key.ascc_manifest_id</code>. Foreign key to the
     * ASCC_MANIFEST table for the ASCC association ordered by this record.
     * Exactly one of ASCC_MANIFEST_ID / BCC_MANIFEST_ID is non-null.
     */
    public ULong getAsccManifestId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.seq_key.bcc_manifest_id</code>. Foreign key to the
     * BCC_MANIFEST table for the BCC association ordered by this record.
     * Exactly one of ASCC_MANIFEST_ID / BCC_MANIFEST_ID is non-null.
     */
    public void setBccManifestId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.seq_key.bcc_manifest_id</code>. Foreign key to the
     * BCC_MANIFEST table for the BCC association ordered by this record.
     * Exactly one of ASCC_MANIFEST_ID / BCC_MANIFEST_ID is non-null.
     */
    public ULong getBccManifestId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.seq_key.prev_seq_key_id</code>. A self-reference to
     * the previous SEQ_KEY record in the ordering chain; NULL for the first
     * association.
     */
    public void setPrevSeqKeyId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.seq_key.prev_seq_key_id</code>. A self-reference to
     * the previous SEQ_KEY record in the ordering chain; NULL for the first
     * association.
     */
    public ULong getPrevSeqKeyId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.seq_key.next_seq_key_id</code>. A self-reference to
     * the next SEQ_KEY record in the ordering chain; NULL for the last
     * association.
     */
    public void setNextSeqKeyId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.seq_key.next_seq_key_id</code>. A self-reference to
     * the next SEQ_KEY record in the ordering chain; NULL for the last
     * association.
     */
    public ULong getNextSeqKeyId() {
        return (ULong) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeqKeyRecord
     */
    public SeqKeyRecord() {
        super(SeqKey.SEQ_KEY);
    }

    /**
     * Create a detached, initialised SeqKeyRecord
     */
    public SeqKeyRecord(ULong seqKeyId, ULong fromAccManifestId, ULong asccManifestId, ULong bccManifestId, ULong prevSeqKeyId, ULong nextSeqKeyId) {
        super(SeqKey.SEQ_KEY);

        setSeqKeyId(seqKeyId);
        setFromAccManifestId(fromAccManifestId);
        setAsccManifestId(asccManifestId);
        setBccManifestId(bccManifestId);
        setPrevSeqKeyId(prevSeqKeyId);
        setNextSeqKeyId(nextSeqKeyId);
        resetTouchedOnNotNull();
    }
}
